### ISSUE TITLE
"operation for Name object attempted on object of wrong type" 

### ISSUE THREAD

**Issue by Kurara** [pikepdf/pikepdf#1]
I would like to know which version of qpdf are u using, because I find this problem merging some pdfs. It can be found here: https://github.com/qpdf/qpdf/issues/74 but it is solved since version 7.0.0 I think.

My code is:
```
new_pdf = Pdf.new()
        for filename in self.filepaths:
            pdf = Pdf.open(filename, password="")
            for page in pdf.pages:
                new_pdf.pages.append(page)

        new_pdf.save(outfilepath)

```

**Comment by jbarlow83** [comment]
qpdf >= 7.0.0 is required

**Comment by Kurara** [comment]
Don't you wrapper qpdf so it's not needed to be installed? It is not in the dependencies of your whl as a pip packet. Should I install it from pip? Sorry but I'm not familiar with c++

**Comment by jbarlow83** [comment]
If you're using the wheel then you should have 7.0.0. You can check ``pikepdf._qpdf.qpdf_version()`` to confirm what qpdf version is in use. 

Failing that, attach the PDF and I'll see if there's something odd about it.

**Comment by Kurara** [comment]
Thanks. I checked and it's version 7.0.0 as you said. I will attach the pdf when I have more information. It gave me different errors. I tried to evade the pages with problems and merge the rest but the program stops without errors (at least not in console) when I try to save the pdf with `pdf.save(outfilepath)` So when I understand more about the problem I'll contact you.

**Comment by jbarlow83** [comment]
Closing due to age
