### ISSUE TITLE
Saving an emplaced pdf

### ISSUE THREAD

**Issue by hebeallrusty** [pikepdf/pikepdf#102]
Hi, I would like to use the emplace function to "substitue" pages within pdf files whilst keeping the table of contents in place, however when saving the pdf back, I'm getting the following error:

`RuntimeError: QPDFObjectHandle from different QPDF found while writing.  Use QPDF::copyForeignObject to add objects from another file.` 

My method of using this function is as follows:
`import pikepdf`
`pdf = pikepdf.Pdf.open(PDF_FILE)`
`subpdf = pikepdf.Pdf.open(SUBS)`
`pdf.pages[PAGE].emplace(subpdf.pages[0])`
`output = f'{OUT_FILENAME}.pdf'`
`pdf.save(output)`

Is there something that I'm doing incorrectly?

I can create a new pdf object `doc`, and use `doc.pages.extend(pdf.pages)` and save that, however it loses all the table of contents, which I wish to keep.

If you could help me out, that would be appreciated.
Thanks

**Comment by jbarlow83** [comment]
You'll need to copy the page from `subpdf` into `pdf` first, then emplace it.

Something like this (not tested):

```python
import pikepdf
pdf = pikepdf.Pdf.open(PDF_FILE)
subpdf = pikepdf.Pdf.open(SUBS)
pdf.pages.append(subpdf.pages[0])
pdf.pages[PAGE].emplace(pdf.pages[-1])
del pdf.pages[-1]
output = f'{OUT_FILENAME}.pdf'
pdf.save(output)
```

I added a small change for the next release that will raise a more specific error in this case.

**Comment by hebeallrusty** [comment]
Hi @jbarlow83 that worked perfectly.
I was following the emplace example at [https://pikepdf.readthedocs.io/en/latest/topics/pages.html](url) which is missing this extra step

**Comment by jbarlow83** [comment]
Thanks, I will fix the example too.
