### ISSUE TITLE
Optimizing PDF

### ISSUE THREAD

**Issue by Sreevkanth** [pikepdf/pikepdf#106]
I am unable to find the syntax to be used for optimizing PDF. Is there a documentation available which I can refer to. Here the need is to compress the PDF for size.

**Comment by jbarlow83** [comment]
Most of it is documented here
https://pikepdf.readthedocs.io/en/latest/api/main.html#pikepdf.Pdf.save

See also here for options to "upgrade" existing compression:
https://pikepdf.readthedocs.io/en/latest/api/main.html#pikepdf.StreamDecodeLevel

You can also set `object_stream_mode` to get a little better compression in exchange for PDF 1.5 output.

If you want to optimize the images within a PDF, have a look at github.com/jbarlow83/OCRmyPDF

**Comment by Sreevkanth** [comment]
Thanks much for the reply, will check on it and will get back if needed.

**Comment by jbarlow83** [comment]
I'll close the issue now. If you have further related questions feel free to reopen it.
