### ISSUE TITLE
missing requirement

### ISSUE THREAD

**Issue by carlodri** [pikepdf/pikepdf#107]
it seems that from here:
https://github.com/pikepdf/pikepdf/blob/6c0280315c68328b635438204854f1f2d6d317b4/src/pikepdf/jbig2.py#L11

a `pillow` entry should be added in the `install_requires` section here:
https://github.com/pikepdf/pikepdf/blob/6c0280315c68328b635438204854f1f2d6d317b4/setup.py#L168

**Comment by jbarlow83** [comment]
I've been treating PIL as optional since it's only required for working with images. But maybe it is better to make it a full  dependency anyway, and let people know they can easily opt out if they don't need it.
