### ISSUE TITLE
Provenance of new image files

### ISSUE THREAD

**Issue by spwhitton** [pikepdf/pikepdf#11]
Hello,

Kindly clarify the licensing/copyright status of the following new files:

- docs/images/pike-cartoon.png
- docs/images/pikemen.jpg
- tests/resources/cmyk-jpeg.pdf

Thank you.

**Comment by jbarlow83** [comment]
Added the first two. cmyk-jpeg.pdf was created by me so falls under the tests/resources/* wildcard.

**Comment by spwhitton** [comment]
Thank you.
