### ISSUE TITLE
Need an example of apply watermark

### ISSUE THREAD

**Issue by StevenLOL** [pikepdf/pikepdf#110]
hi,

Need an example of applying watermark.

Tested with following code, It doesn't work as I exptected, the "watermark" was not on the right location. 

```python
from reportlab.pdfgen import canvas
from pikepdf import Array, Dictionary, Name, Pdf, PdfMatrix, Stream


INPUT_PDF="./test3.pdf"
WATERMARK_PDF='./test4.pdf'
OUTPUT_PDF='./test3_test4.pdf'

def generate_watermark(msg,fileName,x=55,y=220):
    c = canvas.Canvas(fileName, bottomup=0)
    c.setFontSize(32)
    c.setFillColorCMYK(0, 0, 0, 0, alpha=0.7)
    c.rect(204, 199, 157, 15, stroke=0, fill=1)
    c.setFillColorCMYK(0, 0, 0, 100, alpha=0.7)
    c.drawString(x, y,msg )
    c.save()
   
# generate two pdfs
generate_watermark('file3',INPUT_PDF,100,100)
generate_watermark('file4',WATERMARK_PDF)


with pikepdf.open(INPUT_PDF) as input_pdf, \
            pikepdf.open(WATERMARK_PDF) as watermark_pdf, \
            open(OUTPUT_PDF, 'wb') as output_stream:
        
        # Create new output PDF
        output_pdf = pikepdf.new()


        for i in range(len(input_pdf.pages)):
            #load and insert watermark
            input_pdf.pages[i].page_contents_add(watermark_pdf.pages[0].Contents)
            input_pdf.pages[i].page_contents_coalesce()

        output_pdf.pages.extend(input_pdf.pages)
        output_pdf.save(output_stream)  # save to a new file

```

**Comment by jbarlow83** [comment]
It's usually best to capture a page as a Form XObject:

```python
dictpage = watermark_pdf.pages[0]
page = pikepdf.Page(dictpage)
formx = page.as_form_xobject()
```

Then attach it to `input_pdf` as a resource and draw it. 

The reason it's not working is likely the alpha channel. Transparency, like so many PDF features, was awkwardly bolted on after the original spec. The alpha channel information goes into a /Resources /ExtGState object (extended graphics state), and the content stream will activate it. However, if you merge with the input page, you need to check its resource dictionary for name conflicts and possibly edit the content stream. It may be that reportlab put other interesting details in to ExtGState as well.

**Comment by pmg007** [comment]
Hello @jbarlow83 
I am trying to add a watermark to a pdf.
I have created a watermark pdf using `reportlab` and now I am trying to add that to the input pdf using page_contents_add almost just like mentioned in the code snippet above by Steven. I am having no luck getting it to watermark all pages, the first page which is simple one gets watermarked while others do not.
Referred following:
https://github.com/pikepdf/pikepdf/issues/110
https://github.com/pikepdf/pikepdf/issues/95
https://github.com/pikepdf/pikepdf/issues/42
https://github.com/pikepdf/pikepdf/issues/43

All of them are trying to use page_contents_add but have no luck. I see that it is recommended in some comments which say that we need to somehow add that as a resource or copy it into the input pdf, but I am not sure how to achieve that. The usage is not clear. Could you please provide some examples or sample code snippet/template on how to do that?
Thanks. 
References:
https://github.com/pikepdf/pikepdf/issues/42#issuecomment-493790014 
https://github.com/pikepdf/pikepdf/issues/110#issuecomment-662100651

Also, @StevenLOL if you were able to get the pdf watermarked, any of your help is appreciated!

**Comment by jbarlow83** [comment]
Here's an improved, fully functioning example. This is also an improved over the past versions that combined the content streams. This one instead captures the watermark in a "form XObject" (sort of like a sub-page) to isolate it from the rest of the document and makes it less likely to alter the rest of the document.

In a future release I will add `add_resource` to pikepdf's codebase (or some variation thereof) which will simplify this.

```python

import pikepdf
from pikepdf import Name, Pdf, Object, Dictionary
from reportlab.pdfgen import canvas
from typing import Optional
from secrets import token_urlsafe

def generate_watermark(msg,xy):
    x, y = xy
    buf = BytesIO()
    c = canvas.Canvas(buf, bottomup=0)
    c.setFontSize(32)
    c.setFillColorCMYK(0, 0, 0, 0, alpha=0.7)
    c.rect(204, 199, 157, 15, stroke=0, fill=1)
    c.setFillColorCMYK(0, 0, 0, 100, alpha=0.7)
    c.drawString(x, y, msg)
    c.save()
    buf.seek(0)
    return buf

def add_resource(
        obj: Object,
        res: Object,
        res_type: Name,
        name: Optional[Name] = None,
        *,
        prefix: str = '',
        replace_existing: bool = True,
    ) -> str:
        """Adds a new resource to the page's Resources dictionary.

        If the Resources dictionary does not exist, it will be created. If the
        appropriate

        Args:
            obj: The object to add to the resources dictionary.
            name: The name of the object. If omitted, a random name will be
                generated with enough randomness to be globally unique.
            prefix: A prefix for the name of the object. Allows conveniently
                namespacing when using random names, e.g. prefix="Im" for images.
            replace_existing: If the name already exists in one of the resource
                dictionaries, remove it.
        Returns:
            The name of the object.

        Example:
            resource_name = Page(pdf.pages[0]).add_resource(formxobj, Name.XObject)
        """
        if not Name.Resources in obj:
            obj.Resources = Dictionary()
        elif not isinstance(obj.Resources, Dictionary):
            raise TypeError("Page /Resources exists but is not a dictionary")
        resources = obj.Resources

        if not res_type in resources:
            resources[res_type] = Dictionary()
        if not name:
            name = Name(f'/{prefix}{token_urlsafe(16)}')

        for key in resources.keys():
            if isinstance(resources[key], Dictionary) and name in resources[key]:
                if replace_existing:
                    del resources[key][name]
                else:
                    raise ValueError(f"Name {name} already exists in page /Resources")

        resources[res_type][name] = res
        return name

wm = generate_watermark('Watermark', (100, 100))
txt = generate_watermark('Document text', (200, 200))

with pikepdf.open(wm) as pdf_wm, pikepdf.open(txt) as pdf_txt:
    wm_page = pikepdf.Page(pdf_wm.pages[0])
    wm_formx = wm_page.as_form_xobject()

    formx = pdf_txt.copy_foreign(wm_formx)
    page = pdf_txt.pages[0]
    formx_name = add_resource(page, formx, Name.XObject)
    
    draw_watermark_content_stream = pdf_txt.make_stream(b'q 1 0 0 1 0 0 cm %s Do Q' % formx_name)

    pdf_txt.pages[0].page_contents_add(draw_watermark_content_stream, prepend=True)
    pdf_txt.save('out.pdf')

```

**Comment by pmg007** [comment]
Thanks @jbarlow83, I will try this out.

**Comment by pmg007** [comment]
Hi, 
I tried this template out and it has helped up to an extent, thanks! Although for some pdfs I see that I am not able to see the watermark, when I search using Cmd+F I can see that text is present at the bottom of the pdf but is not visible to eye. Any hints or guess so as to what might be the cause for that?

**Comment by jbarlow83** [comment]
If a document completely draws it over the page it will hide the watermark.
It might do this by drawing an image or filled rectangle.

You could draw the watermark last, as a transparent overlay, or make
whatever is on top of the watermark use a transparent background.

Could also be a page with an unusual weird MediaBox or CropBox.

**Comment by pmg007** [comment]
Thanks for the quick reply. What do you mean by adding the watermark last? In the code template above, we are adding a watermark to the existing page afterward, or am I mistaken?

**Comment by jbarlow83** [comment]
prepend=True, so the watermark is placed before all other drawing
operations.

**Comment by pmg007** [comment]
Got it thanks, it mostly works now except in one of the faulty PDFs where it shows a mirror image of the watermark on the next page. Anyways, thanks a lot @jbarlow83

**Comment by jbarlow83** [comment]
I updated the example to demonstrate the use pikepdf.Page.add_resource which is available in pikepdf 2.3.0.

**Comment by pmg007** [comment]
That's great! Thanks for the new release with `add_resource` in it!

**Comment by basileos** [comment]
Thank you very much, @jbarlow83 you rock!

**Comment by jbarlow83** [comment]
It's PDF content stream operators.
q - push graphics stack
1 0 0 1 0 0 cm - multiply current transform matrix by identify matrix
%s Do - draw named object here
Q - pop stack

The identity matrix isn't strictly necessary. It's a clue that you could
use a different matrix to perform rotation, scale, translation.

See PDF manual on content streams.

**Comment by jbarlow83** [comment]
Now implemented officially https://pikepdf.readthedocs.io/en/latest/topics/overlays.html
