### ISSUE TITLE
Feature request: allow to edit input file directly

### ISSUE THREAD

**Issue by Lucas-C** [pikepdf/pikepdf#113]
Currently the following code:
```python
filepath = 'any.pdf'
pdf = pikepdf.open(filepath)
with pdf.open_metadata() as meta:
    meta['dc:title'] = 'Dummy Title'
pdf.save(filepath)
```
generates this error:
`ValueError: Cannot overwrite input file`

This exception is generated here: [qpdf.cpp:404](https://github.com/pikepdf/pikepdf/blob/master/src/qpdf/qpdf.cpp#L404)

Could it be possible to allow for this kind of usage, and remove this limitation please ?

**Comment by Lucas-C** [comment]
My current workaround:
```python
def set_metadata(filepath, meta):
    with io.open(filepath, 'rb') as pdf_file:
        tmp_stream = io.BytesIO()
        copyfileobj(pdf_file, tmp_stream)
    pdf = pikepdf.open(tmp_stream)
    with pdf.open_metadata() as meta:
        meta.update(meta)
    pdf.save(filepath)
    pdf.close()
    tmp_stream.close()
```

**Comment by jbarlow83** [comment]
The problem is you can get data corruption or a crash fairly easily if you retain a `pikepdf.Object` (particularly a `Stream`) that came from the input file after rewriting the file. Some of the data in the PDF is lazily loaded and would be invalidated if the file is updated.

I suppose I could do an "open for modification in place" option, that would create a temporary file behind the scenes, formalizing the workaround you are doing.

**Comment by Lucas-C** [comment]
I think I can submit a PR that would give `pikepdf.open` a 2nd optional usage as a context manager, implementing this workaround:
```
with pikepdf.open('file.pdf') as pdf:
     ...
```
`pikepdf.open` usage as a function would not change.
Would you be open to this ?

**Comment by jbarlow83** [comment]
`pikepdf.open` already works as a context manager. It will close the file without modifying it; to modify it you need to do an explicit save, just like you do with Pillow (PIL).

**Comment by Lucas-C** [comment]
Ok thanks I missed that.

Then I suggest this usage:
```
with pikepdf.open('file.pdf', save_on_close=True) as pdf:
    ...
```

**Comment by jbarlow83** [comment]
The change would still require an explicit `.save()` and naming would reflect that. `allow_overwriting_input` or something.

**Comment by Lucas-C** [comment]
I submitted this PR to implement this: https://github.com/pikepdf/pikepdf/pull/115
