### ISSUE TITLE
unparse_content_stream break commands string

### ISSUE THREAD

**Issue by jeromerobert** [pikepdf/pikepdf#120]
I'm trying to scale a page content. To do so I'm inserting a `cm` command at the beginning of the content stream:
```python
import pikepdf
mydoc = pikepdf.open("mydoc.pdf")
page = mydoc.pages[0]
commands = pikepdf.parse_content_stream(page)
commands.insert(0, ([2, 0, 0, 2, 0, 0], 'cm')) # make the content 2 time larger
new_content_stream = pikepdf.unparse_content_stream(commands)
page.Contents = mydoc.make_stream(new_content_stream)
mydoc.save("/tmp/test.pdf")
```
This does not work. I would have expected `2 0 0 2 0 0 cm` in `test.pdf` but I get `2 0 0 2 0 0 <feff0063006d>`. There seems to be an issue with `_qpdf.unparse`. What does work (but is not very nice) is:

```python
import pikepdf
mydoc = pikepdf.open("/home/jerome/cgv.pdf")
page = mydoc.pages[0]
# get and existing "cm" string in qpdf (hopefuly there is one)
_, cm = pikepdf.parse_content_stream(page, 'cm')[0]
commands = pikepdf.parse_content_stream(page)
# we cannot use a python string ('cm') here else _qpdf.unparse will not work
# see https://github.com/pikepdf/pikepdf/blob/7bbc01b4d523281c73407516769767cfa4ac2790/src/pikepdf/models/__init__.py#L106
commands.insert(0, ([2, 0, 0, 2, 0, 0], cm))
new_content_stream = pikepdf.unparse_content_stream(commands)
page.Contents = mydoc.make_stream(new_content_stream)
mydoc.save("/tmp/test.pdf")
```

**Comment by jbarlow83** [comment]
`b'cm'` or `Operator('cm')` should do the string. `Operator('cm')`, I suppose, is most correct. `<feff0063006d>` is the UTF-16 encoding of `cm`, so it's just doing a Unicode conversion in the wrong place and needs a hint to not do that.

But I should address this. I made some design mistakes by not using stricter typing from the beginning.

**Comment by jeromerobert** [comment]
`b'cm'` leads to `2 0 0 2 0 0 <636d>`. `Operator('cm')` does work, thanks.
