### ISSUE TITLE
[Question] About "blanking" already existing page.

### ISSUE THREAD

**Issue by Nokia808** [pikepdf/pikepdf#121]
Hi. 
I read from the developer of pdfarranger the following statement:

We could also consider blanking existing pages. To blank a page with pikepdf:

`ydoc.pages[pageid].Contents = mydoc.make_stream(pikepdf.unparse_content_stream([]))`

I would like to ask: does this mean that pikepdf has ability to SECURELY remove contents within a page ? If yes, then this mean that pikepdf has ability for secure redaction, isn't it ?

Thank you.

**Comment by jbarlow83** [comment]
pikepdf could be used as a library to implement redaction but doing it
comprehensively would take a lot more effort than just deleting the content
stream.

At minimum you'd also want to call remove_unreferenced_resources before
saving, delete the page's Resources dictionary.

Hunting for objects used on multiple pages - which is allowed - is more
tricky. Subsetted fonts can also reveal sensitive information because they
disclose the subset of letters used.

**Comment by Nokia808** [comment]
@jbarlow83 
This is too much exiting !! To my knowledge - till your replay - that we have only the following 2 open source PDF redaction libraries:
1) https://itextpdf.com/en/products/itext-7/pdf-redaction-pdfsweep
2) Ghostscript

Ghostscript is of limited (& destructive power). While pdfsweep is Java.

Before closing this issue, I have one further question: from programming language point of view, does pikepdf compatible with "PDF Mix Tool" which it's repository at:
https://gitlab.com/scarpetta/pdfmixtool
If it is compatible, then I will open a request for "PDF Mix Tool" taking in mind the fact that it's developer working currently on adding built-in PDF viewer, which is a key element to implement redaction feature.

**Comment by jbarlow83** [comment]
Ghostscript's destructiveness is a possible benefit for redaction.

PDF Mix Tool looks to be a C++ program that uses QPDF as its editor. As such pikepdf is of no use to it.

**Comment by Nokia808** [comment]
@jbarlow83 
Thank you too much for this orientation .... This mean that currently pdfarranger is the only front-end for pikepdf available currently at hand. Unfortunately, it's design not allow it to implement such great functions like outlines & redaction .... Hope that, in future, some one will create more reliable front-end to your powerful program ....
