### ISSUE TITLE
[DOC] Comparison with pymupdf

### ISSUE THREAD

**Issue by MartinThoma** [pikepdf/pikepdf#123]
Maybe the comparison with pdfrw in the readme can be replaced by a comparison with [pymupdf](https://pypi.org/project/PyMuPDF/) and [pdfminer.six](https://pypi.org/project/pdfminer.six/), as pdfrw seems to be dead for a while?

**Comment by dreua** [comment]
pdfminer.six: I don't think it can write PDFs so it is not really comparable to pikepdf imo. Could be mentioned as a library for the special purpose of text extracting though.

pymupdf: Sounds like an interesting comparison.
