### ISSUE TITLE
[Question] How can I delete objects / streams from a PDF file?

### ISSUE THREAD

**Issue by MartinThoma** [pikepdf/pikepdf#124]
Can somebody maybe help me with this one: [How can I delete streams / objects from a PDF file?](https://stackoverflow.com/q/63533504/562769) ?

**Comment by jbarlow83** [comment]
Answered at SO

**Comment by jbarlow83** [comment]
I'll close the issue now. If you have further related questions feel free to reopen it.

**Comment by MartinThoma** [comment]
Thank you for your help!
