### ISSUE TITLE
Removing some/all images from PDF.

### ISSUE THREAD

**Issue by lookasu** [pikepdf/pikepdf#126]
Hi I'm trying to remove some / all images from a PDF.

Can you suggest the best strategy for that?

So far I've tried:

1. Write b"" into an rawimage, and change Height, Width = 0,0 to "hide it"
    - it stops displaying it, but when I open the PDF it shows a message:

![image](https://user-images.githubusercontent.com/10092186/91037810-8e997980-e601-11ea-8dea-4fc39fb5a08e.png)

2. Use a custom TokenFilter* to remove '/Im0 Do\n' via `add_content_token_filter`
    - it also kind of "works" but when I open the PDF it also tells me "An error exists on this page." (as above)

3. Use custom TokenFilter* to remove '/Im0 Do\n' via `get_filtered_contents` and `make_stream` to replace `Contents`
    - this actually messes up the whole PDF removing a lot of the text etc

I've tried calling `remove_unreferenced_resources` to compensate but no luck.

*Working with TokenFilter has actually been a bit problematic/intermittent due to this error:
`error decoding stream data for object 20 0: Tried to call pure virtual function "TokenFilter::handle_token"']`
It's coming up more when there are multiple pages, duplicated images involved. 

Can you advice?

**Comment by jbarlow83** [comment]
The easiest way is similar to #1, but instead changing it to a 1x1 transparent pixel image.
* Delete /Filter
* Delete /ColorSpace
* Delete any keys other than /Type, /Subtype, /Length
* Set /Width, /Height to 0, 0
* Replace stream data with b'\xff' (for transparent)
* Set /BitsPerComponent to 1
* Set /ImageMask to true - this is needed for transparency
* Set /Decode to `[0, 1]`

Editing the content stream is more work. It's also much easier to use `parse_content_stream` API than `TokenFilter`.

**Comment by jbarlow83** [comment]
I added an example of this to the documentation.

**Comment by lookasu** [comment]
@jbarlow83 Much appreciated! 

FYI the example in the documentation only worked for me after I added "/Subtype": Name("/Image"), and "/Type": Name("/XObject") as well.

**Comment by jbarlow83** [comment]
I'll close the issue now. If you have further related questions feel free to reopen it.
