### ISSUE TITLE
How can I get a page as a pixel map?

### ISSUE THREAD

**Issue by MartinThoma** [pikepdf/pikepdf#127]
As a follow-up to https://github.com/pikepdf/pikepdf/issues/125 , I would like to know if pikepdf can render a page to an image. With pymupdf, I can do this:

```
pix1 = page.getPixmap(alpha=False)  # render page to an image
pix1.writePNG(f"page-{page.number}.png")  # store image as a PNG
```

Ideally, it would return something that pillow or numpy can work with as I want to compare two images for identity. I don't really need to write the result, but for mupdf that was the simplest way.

**Comment by jbarlow83** [comment]
pikepdf does not have a PDF rasterizer like pymupdf, and it likely never will. You can use pymupdf, or command line tools like Ghostscript and pdftoppm to rasterize PDFs.
