### ISSUE TITLE
pdf.Open no longer takes BytesIO object as parameter

### ISSUE THREAD

**Issue by cdkmoose** [pikepdf/pikepdf#128]
Using version 1.13.0, I could pass a BytesIO object in the open call, when I upgraded to 1.19.0, I get a type error indicating:
```
"_open(): incompatible function arguments. The following argument types are supported:
    1. (filename_or_stream: object, password: str = '', hex_password: bool = False, ignore_xref_streams: bool = False, suppress_warnings: bool = True, attempt_recovery: bool = True, inherit_page_attributes: bool = True, access_mode: pikepdf._qpdf.AccessMode = AccessMode.default) -> pikepdf._qpdf.Pdf

    Invoked with: <pikepdf.Pdf description='empty PDF'>; kwargs: password=<_io.BytesIO object at 0x7fe4f0331770>, hex_password=False, ignore_xref_streams=False, suppress_warnings=True, attempt_recovery=True, inherit_page_attributes=True, access_mode=AccessMode.default
```

**Comment by jbarlow83** [comment]
It looks like you did something like:

```python
p = pikepdf.Pdf.new()
p.open(BytesIO())
```

Instead use:
```python
p = pikepdf.Pdf.open(BytesIO())
```

If it worked before, *that* was a bug. `.open` is a `@staticmethod` so it should be called from the class (`Pdf.open()`) not an object of the class.

Please include a reproducible code example next time - it saves time.

**Comment by jbarlow83** [comment]
You'll need to use a `BytesIO` that is initialized to valid PDF data for my version to actually work. I'm just demonstrating the syntax that does what you need.

**Comment by cdkmoose** [comment]
I'm processing a Zip file in memory so I have initialized a BytesIO from a file in the zip.  

Updated my code to match your syntax and it now works with 1.19.0.  Thanks for the quick feedback.
