### ISSUE TITLE
How to READ bookmarks / outlines?

### ISSUE THREAD

**Issue by Sunny-Engineer** [pikepdf/pikepdf#129]
There were some good examples and documentation on how to create outlines, but nothing about how to read/navigate existing outlines.  Is there any documentation that would help?

**Comment by jbarlow83** [comment]
You could have a look at test_outlines.py in this project where there are some examples of editing.

**Comment by jbarlow83** [comment]
I'll close the issue now. If you have further related questions feel free to reopen it.
