### ISSUE TITLE
Can't import pikepdf (1.19.0, Windows 8.1 x64, pip 20.2.2, Python 3.8.5)

### ISSUE THREAD

**Issue by mara004** [pikepdf/pikepdf#130]
I have installed pikepdf 1.19.0 as described in the documentation via pip 20.2.2 on Windows 8.1 x64 like this:
<begin installation>
C:\Users\mara\AppData\Local\Programs\Python\Python38>python.exe -m pip install --user pikepdf
Collecting pikepdf
  Downloading pikepdf-1.19.0-cp38-cp38-win_amd64.whl (1.4 MB)
     |████████████████████████████████| 1.4 MB 1.7 MB/s
Collecting lxml>=4.0
  Downloading lxml-4.5.2-cp38-cp38-win_amd64.whl (3.5 MB)
     |████████████████████████████████| 3.5 MB 3.3 MB/s
Collecting Pillow>=6
  Downloading Pillow-7.2.0-cp38-cp38-win_amd64.whl (2.1 MB)
     |████████████████████████████████| 2.1 MB 2.2 MB/s
Installing collected packages: lxml, Pillow, pikepdf
Successfully installed Pillow-7.2.0 lxml-4.5.2 pikepdf-1.19.0
<end installation>

But when I try to use pikepdf (for instance with the example code provided on the first page of the docs), I get this error:
<begin error>
Traceback (most recent call last):
  File "C:\Users\mara\AppData\Roaming\Python\Python38\site-packages\pikepdf\__init__.py", line 21, in <module>
    from ._version import __version__
  File "C:\Users\mara\AppData\Roaming\Python\Python38\site-packages\pikepdf\_version.py", line 7, in <module>
    from pkg_resources import DistributionNotFound
ModuleNotFoundError: No module named 'pkg_resources'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Users\mara\Desktop\rotate.py", line 2, in <module>
    import pikepdf
  File "C:\Users\mara\AppData\Roaming\Python\Python38\site-packages\pikepdf\__init__.py", line 23, in <module>
    raise ImportError("Failed to determine version") from _e
ImportError: Failed to determine version
<end error>

Why is that happening? Have I done something wrong with the installation?

Kind regards and thank you for developing pikepdf
mara

**Comment by dreua** [comment]
> ModuleNotFoundError: No module named 'pkg_resources'

This is part of the `setuptools` package which should be installed. (If I had to guess I'd say as a dependency of pip.) I'd try `pip install --user setuptools` and see if that fixes it.

**Comment by mara004** [comment]
Yes, that fixed the issue! Many thanks for the quick reply :) But I wonder why the setuptools package was not installed...
