### ISSUE TITLE
pikepdf can't save in byteIO stream

### ISSUE THREAD

**Issue by Arnaud-Francois-Fausse** [pikepdf/pikepdf#132]
Hi,
this code snippet doesn't work: when saving in a io.BytesIO. It works perfect when a path string is given as parameter to dest.save

```python
                        dest = Pdf.new()
                        
                        for pageIndex in range(startPage, endPage):
                            dest.pages.append(toCutPdfDoc.pages[pageIndex])
                    
                        cutFileByteStream = io.BytesIO()
                        dest.save(cutFileByteStream)
```

cutFileByteStream is empty, no error. It fails silently.
pikepdf doc says that i's possible to save in a stream.  I have not been able to find a code example.
Any clue is welcome.
Thanks a lot

**Comment by jbarlow83** [comment]
I wrote the following new test:

```python
def test_save_bytesio(resources, outpdf):
    with Pdf.open(resources / 'fourpages.pdf') as input_:
        pdf = Pdf.new()
        for page in input_.pages:
            pdf.pages.append(page)
        bio = BytesIO()
        pdf.save(bio)
        bio_value = bio.getvalue()
        assert bio_value != b''
        pdf.save(outpdf)
        assert outpdf.read_bytes() == bio_value
```

This passes as of v1.19.1.

pikepdf is almost indifferent as to the type of object provided to `.save()`. There is one branch: if the first argument to .save looks like a filename, then we try to open it. Once we have a writable stream (whether pikepdf opened it or the caller), then the exact same code is used to write to it.

Can you reproduce the issue when `toCutPdfDoc` is `tests/resources/fourpages.pdf`?

**Comment by Arnaud-Francois-Fausse** [comment]
Thanks @jbarlow83 

This code works on my box:
import io
from pikepdf import Pdf

def test_save_bytesio():
    with Pdf.open('hamlet_PDF_FolgerShakespeare.pdf') as input_:
        pdf = Pdf.new()
        for page in input_.pages:
            pdf.pages.append(page)
        bio = io.BytesIO()
        pdf.save(bio)
        bio_value = bio.getvalue()
        if bio_value != b'':
            print('Yes, non empty :-) !')
        else:
            print('empty :-(')

if __name__ == "__main__":
    test_save_bytesio()

However, I feel stupid because I don't understand **what's the type of the "outpdf" object** you set in the function parameters ?

So I don't understand why my original code doesn't work... 
Best regards

**Comment by jbarlow83** [comment]
`outpdf` will be a temporary filename, i.e. a `pathlib.Path`. (It's actually a `pytest.fixture` defined elsewhere in the test suite.) I can understand this would be confusing - pytest uses some "magic" to make it easier to write tests, but which also makes them less readable.

If you called `cutFileByteStream.read()` you would get an empty `bytes()` back, because that reads from the cursor to the end of the file... and after `.save()` the cursor will already be at the end of the file. You'd need to use `cutFileByteStream.seek(0)` to move the curosr back to the beginning of the stream, or use `.getvalue()` which ignores the cursor.

**Comment by Arnaud-Francois-Fausse** [comment]
Thanks @jbarlow83, for you explanation that I understand. I didn't notice the cursor that must be reset.
I try it in my original code and tell you.
Best regards
