### ISSUE TITLE
Forms ineditable after rotation

### ISSUE THREAD

**Issue by angsch** [pikepdf/pikepdf#137]
Hi,
I want to rotate the pages of a PDF with forms, take for example http://foersom.com/net/HowTo/data/OoPdfFormExample.pdf

~~~
my_pdf = pikepdf.Pdf.open('OoPdfFormExample.pdf')
for page in my_pdf.pages:
   page.Rotate = 180
my_pdf.save('test.pdf')
~~~

The forms in the output PDF are not longer editable. Opening and directly saving without the rotation preserves the forms. In both cases the size of the output PDF is identical. Are the forms possibly mistranslated?

**Comment by jbarlow83** [comment]
I tried this procedure and found that I *could* edit the forms in Acrobat DC. To be precise, I could select form fields and type in them, and check checkboxes. I did not try to save the form. Could you clarify what software you are using to edit the form, and provide steps to reproduce what you are seeing?

I also visually inspected the input and output PDFs. When decompressed, the contents are very similar, as would be expected.

**Comment by angsch** [comment]
I use evince 3.28.4. By clicking around in the upside-down PDF I managed to catch one form. The offset between input field and display area is not the same for all forms.

![image](https://user-images.githubusercontent.com/17718454/93756322-31471700-fc05-11ea-8c4a-db3b663b6e6b.png)

**Comment by jbarlow83** [comment]
I suspect this is an issue with Evince itself failing to position the textbox correctly when a form element is rotated.

It works fine in macOS Preview too.

PDF viewers are still like web browsers were in the IE6 era: the first party option has nonstandard or underspecified extensions, and the third party alternatives always behind in functionality.
