### ISSUE TITLE
how to use pikepdf to extract pdf to txt?

### ISSUE THREAD

**Issue by waitingfy** [pikepdf/pikepdf#14]
how to use pikepdf to extract pdf to txt?

**Comment by jbarlow83** [comment]
pikepdf can get the sequence of glyphs to print out of a pdf but cannot convert map the glyphs to Unicode. It does not have this implemented. (As a warning, there are some cases where the glyphs are exactly equal to ASCII or Unicode, but this is not true in general, so naively processing the PDF content stream for 'text like information' will often fail.)

If you have a digital PDF and you want to extract the text, use pdfminer. There are some cases where pdfminer cannot find the Unicode mapping and returns gibberish.

If you have a PDF with images that you want to OCR and convert to text, or if the Unicode mapping is gibberish, use ocrmypdf to fix the text, and then pdfminer to extract the text.

**Comment by waitingfy** [comment]
thanks
