### ISSUE TITLE
[Feature Request ] Binary Format output 

### ISSUE THREAD

**Issue by Hemal-Mamtora** [pikepdf/pikepdf#141]
Currenty, the output is a Pdf Object

I would like to unlock the pdf by providing the password and use pdf2image on top of it.

One way is: pikepdf unlock -> save file -> read in pdf2image
I want to avoid I/O

If there is a method .to_binary_format(), it would help in integrating with other libs as well

**Comment by jbarlow83** [comment]
You can save a Pdf object to a memory object like `BytesIO`, or to a pipe created with `os.pipe` and `os.fdopen`, and then pass that as the input to a pdf2image subprocess.
