### ISSUE TITLE
Python 3.9 wheel not available yet

### ISSUE THREAD

**Issue by jbarlow83** [pikepdf/pikepdf#142]
Currently blocked by:
* lxml not having a 3.9 wheel - https://github.com/lxml/lxml/pull/311
* ~~Pillow not having a 3.9 wheel - https://github.com/python-pillow/Pillow/issues/4953~~
* Any issues hidden by Pillow not having a Python 3.9 wheel

lxml can be built with `yum install -y libxslt-devel libxml2-devel` added to `linux-build-deps.bash`.

**Comment by hugovk** [comment]
Pillow 8.0.0 supporting Python 3.9 is now out!

* https://pillow.readthedocs.io/en/stable/releasenotes/8.0.0.html
* https://pypi.org/project/Pillow/8.0.0/
* https://twitter.com/PythonPillow/status/1316452445824921602

**Comment by jbarlow83** [comment]
Done for v2
