### ISSUE TITLE
Unable to install on windows 10

### ISSUE THREAD

**Issue by seahorseshoes** [pikepdf/pikepdf#144]
Apologies if this is something very basic, but I can't seem to get pikepdf installed on Windows 10. 

I have python 3.9.0, pip 20.2.3, Ghostscript v9.53.3, and tesseract v5.0.0-alpha.20200328.
Is this caused by the same issues as #142 , or something else? I tried downgrading to python v3.8.6 but got the same error.

I seem to be missing qpdf/Constants.h, but I'm not sure if that's the core problem.

Any help would be appreciated. Thank you!

```
PS C:\WINDOWS\system32> pip install pikepdf
Collecting pikepdf
  Using cached pikepdf-1.19.3.tar.gz (2.4 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting lxml>=4.0
  Using cached lxml-4.5.2.tar.gz (4.5 MB)
Collecting Pillow>=6
  Using cached Pillow-7.2.0.tar.gz (39.1 MB)
Using legacy 'setup.py install' for lxml, since package 'wheel' is not installed.
Using legacy 'setup.py install' for Pillow, since package 'wheel' is not installed.
Building wheels for collected packages: pikepdf
  Building wheel for pikepdf (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: 'c:\python39\python.exe' 'c:\python39\lib\site-packages\pip\_vendor\pep517\_in_process.py' build_wheel 'C:\Users\PANSEE~1\AppData\Local\Temp\tmpp_6mtd99'
       cwd: C:\Users\PanseeAtta\AppData\Local\Temp\pip-install-bk0v5b25\pikepdf
  Complete output (30 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.9
  creating build\lib.win-amd64-3.9\pikepdf
  copying src\pikepdf\codec.py -> build\lib.win-amd64-3.9\pikepdf
  copying src\pikepdf\jbig2.py -> build\lib.win-amd64-3.9\pikepdf
  copying src\pikepdf\objects.py -> build\lib.win-amd64-3.9\pikepdf
  copying src\pikepdf\_cpphelpers.py -> build\lib.win-amd64-3.9\pikepdf
  copying src\pikepdf\_methods.py -> build\lib.win-amd64-3.9\pikepdf
  copying src\pikepdf\_version.py -> build\lib.win-amd64-3.9\pikepdf
  copying src\pikepdf\__init__.py -> build\lib.win-amd64-3.9\pikepdf
  creating build\lib.win-amd64-3.9\pikepdf\models
  copying src\pikepdf\models\encryption.py -> build\lib.win-amd64-3.9\pikepdf\models
  copying src\pikepdf\models\image.py -> build\lib.win-amd64-3.9\pikepdf\models
  copying src\pikepdf\models\matrix.py -> build\lib.win-amd64-3.9\pikepdf\models
  copying src\pikepdf\models\metadata.py -> build\lib.win-amd64-3.9\pikepdf\models
  copying src\pikepdf\models\outlines.py -> build\lib.win-amd64-3.9\pikepdf\models
  copying src\pikepdf\models\__init__.py -> build\lib.win-amd64-3.9\pikepdf\models
  running build_ext
  building 'pikepdf._qpdf' extension
  creating build\temp.win-amd64-3.9
  creating build\temp.win-amd64-3.9\Release
  creating build\temp.win-amd64-3.9\Release\src
  creating build\temp.win-amd64-3.9\Release\src\qpdf
  C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.27.29110\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -DVERSION_INFO="1.19.3" -IC:\Users\PanseeAtta\AppData\Local\Temp\pip-build-env-t4fb2fci\overlay\Lib\site-packages\pybind11\include -Ic:\python39\include -Ic:\python39\include -IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.27.29110\include -IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\shared -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\winrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\cppwinrt /EHsc /Tpsrc/qpdf\annotation.cpp /Fobuild\temp.win-amd64-3.9\Release\src/qpdf\annotation.obj /EHsc
  annotation.cpp
  src/qpdf\annotation.cpp(11): fatal error C1083: Cannot open include file: 'qpdf/Constants.h': No such file or directory
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.27.29110\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
  ----------------------------------------
  ERROR: Failed building wheel for pikepdf
Failed to build pikepdf
ERROR: Could not build wheels for pikepdf which use PEP 517 and cannot be installed directly
```

**Comment by jbarlow83** [comment]
Try "pip install wheel" so that Windows can use wheels instead of source
builds.

**Comment by seahorseshoes** [comment]
@jbarlow83 Yes, I think that did it!! 
(Well, either that or manually installing qpdf -- to be honest I didn't think to test it in between steps)
In either case it's working perfectly now. Thanks for the help!

**Comment by jbarlow83** [comment]
The Windows 10 wheel of pikepdf includes a compiled copy of libqpdf, so it
should be independent of your qpdf install.

**Comment by xiaopang0v0** [comment]
> 抱歉，如果这是非常基本的东西，但我似乎无法在 Windows 10 上安装 pikepdf。
> 
> 我有 python 3.9.0、pip 20.2.3、Ghostscript v9.53.3 和 tesseract v5.0.0-alpha.20200328。 这是由与#142相同的问题还是其他原因引起的？我尝试降级到 python v3.8.6 但得到了同样的错误。
> 
> 我似乎缺少 qpdf/Constants.h，但我不确定这是否是核心问题。
> 
> 任何帮助，将不胜感激。谢谢！
> 
> ```
> PS C:\WINDOWS\system32> pip install pikepdf
> Collecting pikepdf
>   Using cached pikepdf-1.19.3.tar.gz (2.4 MB)
>   Installing build dependencies ... done
>   Getting requirements to build wheel ... done
>     Preparing wheel metadata ... done
> Collecting lxml>=4.0
>   Using cached lxml-4.5.2.tar.gz (4.5 MB)
> Collecting Pillow>=6
>   Using cached Pillow-7.2.0.tar.gz (39.1 MB)
> Using legacy 'setup.py install' for lxml, since package 'wheel' is not installed.
> Using legacy 'setup.py install' for Pillow, since package 'wheel' is not installed.
> Building wheels for collected packages: pikepdf
>   Building wheel for pikepdf (PEP 517) ... error
>   ERROR: Command errored out with exit status 1:
>    command: 'c:\python39\python.exe' 'c:\python39\lib\site-packages\pip\_vendor\pep517\_in_process.py' build_wheel 'C:\Users\PANSEE~1\AppData\Local\Temp\tmpp_6mtd99'
>        cwd: C:\Users\PanseeAtta\AppData\Local\Temp\pip-install-bk0v5b25\pikepdf
>   Complete output (30 lines):
>   running bdist_wheel
>   running build
>   running build_py
>   creating build
>   creating build\lib.win-amd64-3.9
>   creating build\lib.win-amd64-3.9\pikepdf
>   copying src\pikepdf\codec.py -> build\lib.win-amd64-3.9\pikepdf
>   copying src\pikepdf\jbig2.py -> build\lib.win-amd64-3.9\pikepdf
>   copying src\pikepdf\objects.py -> build\lib.win-amd64-3.9\pikepdf
>   copying src\pikepdf\_cpphelpers.py -> build\lib.win-amd64-3.9\pikepdf
>   copying src\pikepdf\_methods.py -> build\lib.win-amd64-3.9\pikepdf
>   copying src\pikepdf\_version.py -> build\lib.win-amd64-3.9\pikepdf
>   copying src\pikepdf\__init__.py -> build\lib.win-amd64-3.9\pikepdf
>   creating build\lib.win-amd64-3.9\pikepdf\models
>   copying src\pikepdf\models\encryption.py -> build\lib.win-amd64-3.9\pikepdf\models
>   copying src\pikepdf\models\image.py -> build\lib.win-amd64-3.9\pikepdf\models
>   copying src\pikepdf\models\matrix.py -> build\lib.win-amd64-3.9\pikepdf\models
>   copying src\pikepdf\models\metadata.py -> build\lib.win-amd64-3.9\pikepdf\models
>   copying src\pikepdf\models\outlines.py -> build\lib.win-amd64-3.9\pikepdf\models
>   copying src\pikepdf\models\__init__.py -> build\lib.win-amd64-3.9\pikepdf\models
>   running build_ext
>   building 'pikepdf._qpdf' extension
>   creating build\temp.win-amd64-3.9
>   creating build\temp.win-amd64-3.9\Release
>   creating build\temp.win-amd64-3.9\Release\src
>   creating build\temp.win-amd64-3.9\Release\src\qpdf
>   C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.27.29110\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -DVERSION_INFO="1.19.3" -IC:\Users\PanseeAtta\AppData\Local\Temp\pip-build-env-t4fb2fci\overlay\Lib\site-packages\pybind11\include -Ic:\python39\include -Ic:\python39\include -IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.27.29110\include -IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\shared -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\winrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\cppwinrt /EHsc /Tpsrc/qpdf\annotation.cpp /Fobuild\temp.win-amd64-3.9\Release\src/qpdf\annotation.obj /EHsc
>   annotation.cpp
>   src/qpdf\annotation.cpp(11): fatal error C1083: Cannot open include file: 'qpdf/Constants.h': No such file or directory
>   error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.27.29110\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
>   ----------------------------------------
>   ERROR: Failed building wheel for pikepdf
> Failed to build pikepdf
> ERROR: Could not build wheels for pikepdf which use PEP 517 and cannot be installed directly
> ```
Please try my solution
https://github.com/ocrmypdf/OCRmyPDF/issues/460#issuecomment-1320849709

-------------------------------

请试试我的解决方案
https://github.com/ocrmypdf/OCRmyPDF/issues/460#issuecomment-1320849709
