### ISSUE TITLE
[Question] Cropping pdf page

### ISSUE THREAD

**Issue by KlemenVrhovec** [pikepdf/pikepdf#145]
This is a great library. I just decided to replace PyPDF2 with pikepdf for my project, but I stumbled on one issue.

How can I crop the page. I did not find anything in documentation.

I want something similar as in PyPDF2 below code

```
from PyPDF2 import PdfFileReader, PdfFileWriter
pdfFileObj = open('file.pdf', 'rb')
# read the pdf object
pdfReader = PdfFileReader(pdfFileObj)
# create pdf writer object
writerObj = PdfFileWriter()
page = pdfReader.getPage(page_num)
# crop from coordinates
page.cropBox.setLowerLeft(25, 25)
page.cropBox.setLowerRight(225, 225)
page.cropBox.setUpperLeft(50, 50)
page.cropBox.setUpperRight(200, 200)
pages = 0
# Write the new page
writerObj.addPage(page)
```

Thank you for any response

**Comment by jbarlow83** [comment]
Just change the TrimBox on the page, e.g. `page.TrimBox = [25, 25, 200, 200]`.

(Or MediaBox, or CropBox. See PDF reference manual if the differences matter to you; they're not exactly the same.)

Note that this merely hides content (just like PyPDF2 does). It does not redact content that is hidden by the cropping operation. You could use Ghostscript pdfwrite to re-fry the PDF.

**Comment by KlemenVrhovec** [comment]
Thank you for quick response. For me purpose MediaBox worked.

The purpose is to extract part of pdf to image and then put in into report. I do it by creating cropped pdf and then convert it to jpg with another library.

Is there maybe a possibility to use this library to extract part of the page directly to jpg? In documentation I saw that for image.

**Comment by jbarlow83** [comment]
Conversion to JPEG is not possible - pikepdf knows how to manipulate PDF data, but is not capable of rendering a PDF to image, which is a very complex task that a solo maintainer like me could never complete. Use a program like Ghostscript, MuPDF, or pdftoppm to do that.

**Comment by KlemenVrhovec** [comment]
Thank you for clarification.
