### ISSUE TITLE
How to extract contents of the pdf file?

### ISSUE THREAD

**Issue by patel33hardik** [pikepdf/pikepdf#146]
Thanks for the library
How do I extract the contents of the pdf file (excluding metadata)? I wish to get the content of the entire pdf file and calculate the md5 hash value to check the integrity of the pdf file.
I can do md5 hash calculation for entire pdf but once we save the pdf file the metadata also changes which gives me the different output.
Following is my question and I have done through the PyPdf2 library, but that library not allow to read password protected files. https://stackoverflow.com/questions/64566153/how-do-i-calculate-the-md5-checksum-of-a-file-contents-in-python
```file = open(file_path, 'rb+')
reader = PdfFileReader(file)
writer = PdfFileWriter()
count = reader.numPages
# extract the text from the pdf file and store in the extracted_data variable
extracted_data = ''
for i in range(count):
    page = reader.getPage(i)
    extracted_data += page.extractText()
# calculate the md5 hash for the data in the extracted_data variable
md5_returned = self.createMd5CheckSum(extracted_data)
```
So, I move to the pikepdf but I need to calculate md5 checksum for the content of the PDF file only not with metadata.

Can anyone help to extract content from the pdf file using pikepdf?

**Comment by jbarlow83** [comment]
PyPDF2's extractText feature is broken. To be precise, it works in situations where the font glyph ID is equal to the Unicode character point. That is true as often as not. One could *easily* construct a PDF that is completely different visually yet matches your checksum.

`pdf.trailer.ID` contains a pair of values which already contain a cryptographic hash as defined in the PDF reference manual. These may be suitable for your use case. You can also save with `.save(...static_id=True, fix_metadata_version=False...)` to make saving more deterministic.

To hash contents excluding metadata, you could also iterate through all objects in the PDF (`pdf.get_object()`) and feed their `pdfobj.encode()` representation to a hash function, skipping those that you consider metadata.

**Comment by jbarlow83** [comment]
A more detailed description of the text extraction issue:
https://pikepdf.readthedocs.io/en/latest/topics/content_streams.html#extracting-text-from-pdfs

**Comment by patel33hardik** [comment]
Thanks for quick reply @jbarlow83 
Would you please add an example code? 

I was thinking to write as follows.

```
pdf = pikepdf.open(filepath)
# extract the text from the pdf file and store in the extracted_data variable
extracted_data = ''
for i in range(len(pdf.pages)):
    page = reader.getPage(i)
    extracted_data += pdf.pages[i].Content()

# calculate the md5 hash for the data in the extracted_data variable
md5_returned = self.createMd5CheckSum(extracted_data)
# update custom matadata with the calculated md5 hashs 
pdf.docinfo['HashKey] = md5_returned 
pdf.save()
```
Now the client can download this file from my server (they can be modified). When I received the file back from any of my clients, I want to check the integrity of that file. Weather file data is modified or not. So I will read the pdf file metadata as following.
```
pdf = pikepdf.open(upload_file_path_of_client_modified_pdf)
meta = dict(pdf.docinfo)
original_has_key = None
for key, val in meta.items():
    if key = 'HashKey':
        original_has_key = val

extracted_data = ''
for i in range(len(pdf.pages)):
    page = reader.getPage(i)
    extracted_data += pdf.pages[i].Content()

#Now calculate md5 hash key for new uploaded file content
md5_returned = self.createMd5CheckSum(extracted_data)

if original_has_key != md5_returned:
    print('File modified by someone')
else:
   print('File not modified')
```

Can you please correct me If I am wrong? Do you think the above can be improved?

**Comment by jbarlow83** [comment]
If you want me to solve specific problems for you we would need to discuss
a consulting agreement.

Otherwise, my recommendations remain as outlined in the previous answer. I
believe they could solve your problem.

I will add that hashing the content streams is not enough to confirm a PDF
is unmodified. You'll have to also check if images, fonts and widgets were
modified.

**Comment by nonprofittechy** [comment]
I found this thread but it took some digging to see that `pdfminer.six` is the right tool to use here.

```
pip install pdfminer.six
```

```
from pdfminer.high_level import extract_text
extract_text("path_to_pdf_file.pdf")
```
