### ISSUE TITLE
repositioning content

### ISSUE THREAD

**Issue by capntrips** [pikepdf/pikepdf#15]
One of the features listed in the docs is the ability to reposition content, but I'm not seeing any docs or tests dealing with that specific topic.  Would you mind adding some documentation on how to get started with that?  Thanks.

**Comment by jbarlow83** [comment]
Will do...
There's an example of repositioning here, in the context of aligning two layers of content so that their rotations match:
https://github.com/jbarlow83/OCRmyPDF/blob/master/src/ocrmypdf/_weave.py#L91

The technique would be same.

**Comment by capntrips** [comment]
Thanks, that link led me to exactly what I needed.

This is a great library you have here. The only one I found that implemented more than the encryption side of QPDF, I really didn't want to brush up on my C++ skill, such that they are.
