### ISSUE TITLE
add author to metadata destroys pdf/a conformance

### ISSUE THREAD

**Issue by femifrak** [pikepdf/pikepdf#150]
sorry for similar issue like #143 
When adding author info to meta data pdf/a conformance is no longer given:
```
import pikepdf, sys
# using pikepdf v.2.1.2

doc = pikepdf.open(sys.argv[1])

with doc.open_metadata() as meta:
     meta['dc:creator'] = 'Forname Surename'

doc.save('out.pdf')
doc.close()


```
[in.pdf](https://github.com/pikepdf/pikepdf/files/5655140/in.pdf)
[out.pdf](https://github.com/pikepdf/pikepdf/files/5655158/out.pdf)

Or is this not the way to add author info?
Thanks!!

**Comment by femifrak** [comment]
I can imagine that making files pdfa compliant is a thankless and unsatisfying task. Actually, all I care about is that the file will still be readable in 20, 30 years. Basically, I am only marginally interested in the metadata. The main reason for my question is that I don't know of any tool that exclusively tests my long-term readability requirements and disregards the meta-stories. In light of the fact that the metadata is probably a bit difficult to deal with, I'm wondering if I should suggest an option that deletes all (or all possible) metadata, resulting in a file that can be more easily made pdfa-compliant.

What do you think?

**Comment by jbarlow83** [comment]
Looks like the complaint is that dc:creator needs to be an ordered array of names, not a single name. But I can't find where the spec describes how to copy this information to the document info dictionary where only a single string is accepted (I think).

Unfortunately deleting the metadata won't help, because there is information in the metadata that designates the document as a PDF/A.

**Comment by jbarlow83** [comment]
So there's a simple fix: `meta['dc:creator'] = ['Forname Surename']`

**Comment by femifrak** [comment]
Sorry for the late repyly.

Thanks a lot for the solution! This is great as I can use verapdf again now :)
