### ISSUE TITLE
Provide wheels for pypy3.7 - Windows and Apple Silicon

### ISSUE THREAD

**Issue by mattip** [pikepdf/pikepdf#153]
Would it be possible to provide wheels for pypy3.7? Where would be an appopriate place to add the identifier? If you are using cibuildwheel, it [supports pypy](https://cibuildwheel.readthedocs.io/en/stable/#what-does-it-do)

**Comment by jbarlow83** [comment]
I have tried this already and it looks like some nontrivial changes are required for PyPy support beyond just flipping the switch for wheels. But it's definitely on the list and will be looked at soon.

**Comment by jbarlow83** [comment]
A source build of pikepdf for PyPy 3.6 and 3.7 should now work everywhere PyPy itself does.

We now generate wheels where possible. Currently "where possible" means "only macOS and PyPy 3.6".

* cibuildwheel, our wheel builder, does not support Windows 64bit + PyPy. I don't know why.
* cibuildwheel also calls PyPy 3.7 support "beta" and it didn't work for me, so I turned it off.
* The Linux wheel build is blocked by lxml not providing wheels for PyPy.

**Comment by mattip** [comment]
Thanks for trying this.
PyPy has not released a windows-64 version. I expect to do so in a few months. I am curious what didn't work with 3.7? As for lxml, I have submitted a request for wheels on their bug tracker. In the mean time, `pip` should be able to install from source. You may need to add `sudo apt install libxml2-dev libxslt-dev`.

**Comment by jbarlow83** [comment]
You can explore the history of my attempts over at the CI page:
https://dev.azure.com/jim0585/pikepdf/_build/results?buildId=628&view=logs&j=b2899b18-c6cb-5a9a-dc23-152274619db7&t=8cc05615-22cc-5782-c296-50c165c7a7aa

Some of my tests are randomly generated with hypothesis. I believe the pypy3.7 stumbled upon a bug in the PyPy implementation of `datetime.fromisoformat`. This function was only added in Python 3.7, so I had a workaround for 3.6. We'll try that for PyPy 3.7 and if so, macOS PyPy 3.7 might work.

Other details

* Since lxml does not provide a wheel for PyPy 3.7 on Linux 64 either, it will fail for the reason as PyPy 3.6
* win32 3.6: no wheel for Pillow, and failed to build Pillow from source
* linux32: either cibuildwheel or PyPy does not support this at all

**Comment by jbarlow83** [comment]
Checking in again, several weeks later. After changing to GitHub Actions, wheels are now generating for macOS PyPy 3.6 and 3.7. The blocking issues on other platforms have not changed.

**Comment by mattip** [comment]
In order to work around the missing lxml wheels, I wonder if there are alternatives that might be more PyPy-friendly. I realize PyPy is quite a niche use case for you, but what would you think about having a pluggable lxml interface:
```
try:
    import lxml
except ImportError:
    import lxml-mock as lxml
```

where lxml-mock could be based on something like [xmltodict](https://github.com/martinblech/xmltodict), or even pyexpat (which comes built-in in both CPython and PyPy)? Then the [setup.py](https://github.com/pikepdf/pikepdf/blob/master/setup.py#L87) would specify
```
'lxml >= 4.0; platform_python_implementation!="PyPy'   # untested
```

**Comment by jbarlow83** [comment]
If you can point me to a drop in replacement for lxml that's supported everywhere and passes all tests, I'll do it.

Or if you want to take on converting src/pikepdf/metadata.py to a better xml library, you're welcome to take a stab at it . (Make sure to pick a library that supports xmlns, processing instructions, and can handle malformed xml.) I'm not attached to lxml and would be happy to replace it, but I can't justify the effort to overhaul it at this point.

**Comment by jbarlow83** [comment]
As of 2.12.2 we will provide Linux x86-64 PyPy wheels. (cibuildwheel improved its support, and we just build lxml for PyPy.)
Windows and macOS Apple Silicon will have to wait.

**Comment by mattip** [comment]
Thanks!
