### ISSUE TITLE
no debug symbol during build on mageia Cauldron

### ISSUE THREAD

**Issue by david-geiger** [pikepdf/pikepdf#155]
Hi,

On mageia cauldron with python 3.8.7 when building latest 2.2.2 release there is an issue because of missing debug symbol.

Attached the full build log:
[build.x86_64.0.20201225090903.log](https://github.com/pikepdf/pikepdf/files/5741796/build.x86_64.0.20201225090903.log)

**Comment by jbarlow83** [comment]
Please report this to whoever maintains the build for this operating
system.
