### ISSUE TITLE
pikepdf doesn't build against qpdf master

### ISSUE THREAD

**Issue by jberkenbilt** [pikepdf/pikepdf#156]
@jbarlow83 I'm planning on releasing qpdf 10.1. Part of my release procedure is to build pikepdf and run its test suite. Current master of pikepdf fails to build against current master of qpdf right now. I'm not familiar enough with how the Python stuff works to give you pull request, but I'm guessing it will be easy for you to resolve. It is probably related to new interfaces having been added to QPDFPageObjectHandle. I have done my binary compatibility testing and am sure I haven't broken ABI.

I'll hold the release of qpdf 10.1 one day to give you a chance to look at it, in hopes that I can know pikepdf's tests pass with 10.1. Let me know if you need more time than that. 10.1 is otherwise ready to go.

**Comment by jbarlow83** [comment]
That's an easy one to fix on my end. The issue is that the address of the
function is ambiguous for the template now that there are multiple
signatures. The ABI should be fine.

**Comment by jberkenbilt** [comment]
Sounds good. Will you be able to either make the change so I can test with pikepdf tomorrow or else test qpdf on master against pikepdf? Or should I just go ahead and do the 10.1.0 release without testing pikepdf and be prepared for a 10.1.1 if I broke pikepdf?

One thing in 10.1 is the ability to register stream filters. This makes it possible for end user code to teach qpdf how to decode things like JBIG2, JP2, CCITT{3,4}, etc. that I can't do in qpdf without additional library dependencies. I'm not sure whether this would make it easy for pikepdf, with more of the Python ecosystem at its disposal, to potentially allow users to decode some of these other filters. I have the idea in mind of writing a standalone PDF optimizer that could do this and some of the other things people have requested, like using a better zlib implementation, that I don't want to do in qpdf proper because I want to keep qpdf's dependencies minimal. This is pretty low priority for me though.

I was not able to get mmap working, unfortunately. I was getting weird segfaults, sometimes seemingly upon trying to read an address I had already read before. I put a couple of hours into investigating and then decided it wasn't worth it. There will probably be a 10.2 soon too. I have to do some stuff for work that involves file attachments and form fields, and so I will probably be adding some new calls for dealing with file attachments. The next big thing for qpdf is going to be dealing with document-level structures with page operations.

**Comment by jbarlow83** [comment]
I just pushed pikepdf 2.2.5, which should fix this issue. The libqpdf ABI remains compatible.

Stream filters sounds like a good feature. I support some streams on a hard-coded basis currently - when you use a pikepdf.PdfImage wrapper it knows how to check for other formats, but having this integrated into qpdf would be more elegant.

I have an image-oriented PDF optimizer inside ocrmypdf, based on lossy quantization and JBIG2 optimization, both of which are doing by shelling out to other programs. Funny enough I've thought about making it standalone too, but it's also low priority.

Interesting about mmap. [This article](https://www.sublimetext.com/blog/articles/use-mmap-with-care) claims that you can get most of the benefits of mmap using pread, and will less cross platform complexity. I did actually see a segfault problem with mmap, but I attributed it to a known issue in pybind11.
