### ISSUE TITLE
pikepdf test failures on qpdf master

### ISSUE THREAD

**Issue by jberkenbilt** [pikepdf/pikepdf#158]
The commit https://github.com/qpdf/qpdf/commit/bedf35d6a55a9092485d56002b50bc9003ce7931 causes two test failures in pikepdf. I think the problem is actually with the pikepdf tests, not with qpdf, but this commit does introduce a subtle behavior change, specifically, that when pipeContentStreams is called on a page with multiple content streams, finish() is called only once, not repeatedly, on downstream filters. The old behavior actually caused some serious problems, including a bug in which a token filter was only applied to the first content stream when there were multiple streams. Anyway, it's possible that qpdf is calling the token filter defined in pikepdf differently.

I don't think this is a qpdf bug, so I'm going to move forward with 10.1, but if you discover that it is a qpdf bug, I'm sure you'll let me know.

**Comment by jbarlow83** [comment]
I think this is improved behavior. For reasons not quite clear to me qpdf
is propagating Python exceptions rather than Python exceptions causing new
C++ which seems "cleaner". The failing tests were just checking that
invalid subclasses of TokenFilter raised sensible errors.

**Comment by jbarlow83** [comment]
Fixed for v2.3.0
