### ISSUE TITLE
[Question] Using pikepdf together with img2pdf

### ISSUE THREAD

**Issue by mara004** [pikepdf/pikepdf#159]
I am wondering about what is the most elegant way to integrate images via img2pdf into documents being processed with pikepdf.
Currently, I create temporary files and open them with pikepdf.Pdf.open() as usual:
```
temp = tempfile.NamedTemporaryFile()
temp.write(img2pdf.convert(images))
pdf = Pdf.open(temp.name)
temp.close()
...
```
My question is: Can I avoid temporary files and instead hand over img2pdf's output to pikepdf directly, or is it good how I do it at the moment?

**Comment by jbarlow83** [comment]
You can do
```python
bio = io.Bytes()
img2pdf.convert(images, outputstream=bio)
bio.seek(0)
pdf = Pdf.open(bio)
...
```

You can also set `engine=Engine.pikepdf` to have img2pdf use pikepdf as its backend.

**Comment by mara004** [comment]
Ah, that's better, thanks!

**Comment by mara004** [comment]
I'd again have a question on this: When can I delete the `bio` variable (if that at all necessary)? Is it possible to promptly do it after opening the image, or should I wait until the final document is saved?

**Comment by jbarlow83** [comment]
Whenever you open something with `pikepdf.open`, you are pinky-swearing that the underlying stream object (`bio` in this case) will remain available and unmodified until you close it the `Pdf` object. You should either explicitly `.close()` it when you're done, or better, use a `with` block so it's perfectly clear that we can close it. To be clear, that means you have to wait until after the final document is saved.

(I wouldn't worry about the `bio` variable itself.)

**Comment by mara004** [comment]
okay, thanks for the quick response

**Comment by mara004** [comment]
interestingly, I tried it with `del bio`, and it appears to work nevertheless...

**Comment by mara004** [comment]
> [...] You should either explicitly `.close()` it when you're done, or better, use a `with` block so it's perfectly clear that we can close it. To be clear, that means you have to wait until after the final document is saved.
> 
> (I wouldn't worry about the `bio` variable itself.)

Does this mean pikepdf automatically cleans up the BytesIO when the `pikepdf.Pdf` object is closed?

**Comment by mara004** [comment]
Another question: If I have many source documents which I merge into one, is it okay to directly close each source document after having appended the required page(s) to the new document, or do I have to wait with closing until the final pdf is saved?

**Comment by jbarlow83** [comment]
I think you should read about the difference between `file.close()` and `del file` in Python generally, and for BytesIO. 

pikepdf will close any file it opens. In the case of BytesIO, it did not open that file-like object, so it will not close it.

You should be able to close Pdfs after copying contents, because add page copies the contents of the page into the target page.
