### ISSUE TITLE
RuntimeError: Tried to call pure virtual function "TokenFilter::handle_token"

### ISSUE THREAD

**Issue by Bonstra** [pikepdf/pikepdf#160]
Hi, I noticed what looks like a bug in Page.add_content_token_filter().

# Test case
I want to:

- load an existing PDF from a file
- iterate over every page, and for each page:
  -  instantiate a content token filter with per-page parameters
  - attach it to the page using Page.add_content_toker_filter()
- save the modified PDF to a file using Pdf.save()

What the filter does is not relevant for that bug, but can still be useful if someone is looking for an example: this filter replaces all the string tokens with another string token made of a single ASCII character repeated to match the length (in bytes) of the original string. That replacement character is specified when the filter is instantiated.

# Expected result
A new PDF file should be output, with each page altered according to the parameters specified when the filter was created for that page.
# Observed result
qpdf throws a C++ exception:

> $ ./testcase_ko.py in.pdf out.pdf
> Traceback (most recent call last):
>   File "./testcase_ko.py", line 33, in <module>
>     pdf.save(outfile)
>   File "/usr/lib/python3.9/site-packages/pikepdf/_methods.py", line 740, in save
>     self._save(
> RuntimeError: Tried to call pure virtual function "TokenFilter::handle_token"

The generated PDF file is invalid.

# Environment

- ArchLinux x86_64
- Python 3.9.1
- pykepdf 2.3.0
- qpdf 10.1.0

# Failing test case code (testcase_ko.py)
```python
#!/usr/bin/env python3

import sys
from pikepdf import *

class MyFilter(TokenFilter):
    def __init__(self, replace):
        super().__init__()
        self.replace = bytes(replace, 'ascii')

    def handle_token(self, tok):
        if tok.type_ == TokenType.string:
            l = len(tok.raw_value)
            s = self.replace * l
            return Token(TokenType.string, s)
        return tok

if len(sys.argv) != 3:
    print("%s infile.pdf outfile.pdf" % (sys.argv[0],))
    sys.exit(1)

infile = sys.argv[1]
outfile = sys.argv[2]

pdf = Pdf.open(infile)
pages = pdf.pages
num = 0
for page in pages:
    page = Page(page)
    f = MyFilter(('%d' % num)[-1])
    page.add_content_token_filter(f)
    num += 1
pdf.save(outfile)
```
# Workaround (testcase_ok.py)
```python
#!/usr/bin/env python3

import sys
from pikepdf import *

class MyFilter(TokenFilter):
    def __init__(self, replace):
        super().__init__()
        self.replace = bytes(replace, 'ascii')

    def handle_token(self, tok):
        if tok.type_ == TokenType.string:
            l = len(tok.raw_value)
            s = self.replace * l
            return Token(TokenType.string, s)
        return tok

if len(sys.argv) != 3:
    print("%s infile.pdf outfile.pdf" % (sys.argv[0],))
    sys.exit(1)

infile = sys.argv[1]
outfile = sys.argv[2]

pdf = Pdf.open(infile)
pages = pdf.pages
num = 0
fs = []
for page in pages:
    page = Page(page)
    f = MyFilter(('%d' % num)[-1])
    fs.append(f)
    page.add_content_token_filter(f)
    num += 1
pdf.save(outfile)
```
The workaround consists in keeping references to every instantiated filter inside an array in the parent scope, so that the filter objects outlive the scope they are instantiated from and the references stored in the Page objects are still valid when calling Pdf.save().

**Comment by jbarlow83** [comment]
Thanks for the detailed explanation. Your analysis seems to be correct - a reference gets lost here. I can probably come up with a way to attach them to the Pdf itself. 

Note to self: extract function from pikepdf.h around "if (owner)...keep_alive_impl(...)", make add_content_token_filter do this same dance.

**Comment by jbarlow83** [comment]
@Bonstra I took the liberty of including a good portion of your test code in a test case. If you have any objections or want official credit please let me know.

**Comment by Bonstra** [comment]
> @Bonstra I took the liberty of including a good portion of your test code in a test case. If you have any objections or want official credit please let me know.

No, that's fine.
I hereby release this test case code into the public domain :)

**Comment by jbarlow83** [comment]
thanks
