### ISSUE TITLE
Replacing images

### ISSUE THREAD

**Issue by oOMelhor** [pikepdf/pikepdf#161]
Thanks for this fantastic library

I am trying to create a PDF compressor, especially to compress images using ImageMagick and guetzli, externally for processing. I extract the images to disk, ImageMagick or guetzli to compress those images, and then put it back in the same position as it was in the pdf.
I am unable to use an image after it has been processed inside the python script. Is it possible to have a code example of how to use an image, after the image has been processed, and place the processed image in the pdf in the same location from which the original image was extracted?

I'm creating a GUI to be used in the office where I work, here people use a lot of pdf scanners

**Comment by jbarlow83** [comment]
See my work in OCRmyPDF: `ocrmypdf.optimize` for a PDF optimizer that mainly works by running data through external sources. My suggestion would be to start with it and extend it, and possibly contribute those changes back. pikepdf emerged from my need for better PDF tools for OCRmyPDF.

ocrmypdf.optimize could be standalone program, if I had time or funding to break it out. 

You can also run OCRmyPDF without OCR, which causes it to optimize without adding OCR: `ocrmypdf --skip-text --tesseract-timeout 0 in.pdf out.pdf`.

The pikepdf documentation provides an example of replacing the binary data in an image:
https://pikepdf.readthedocs.io/en/latest/topics/images.html#replacing-an-image
Changing the type of image (PNG <-> JPEG) or colorspace gets more complex.

**Comment by oOMelhor** [comment]
Great. I will study it

**Comment by milahu** [comment]
> See my work in OCRmyPDF: `ocrmypdf.optimize` for a PDF optimizer that mainly works by running data through external sources.

https://github.com/ocrmypdf/OCRmyPDF/blob/main/src/ocrmypdf/optimize.py

> Great. I will study it

@raylan-oliveira do you have a script for this task?
in my case, i want to: extract images from pdf, manually process images, replace images in pdf
