### ISSUE TITLE
save method taking a lot of time

### ISSUE THREAD

**Issue by pmg007** [pikepdf/pikepdf#163]
Utilizing this: 
https://github.com/pikepdf/pikepdf/blob/11471d1823b13b64cd83dc145ab566f63c3a2547/src/pikepdf/_methods.py#L614
Upon profiling my code to figure out which part is causing inefficiency, I see the `save` method, which is using `_save` from `qpdf` is taking much longer times.
I am trying to save the watermarked pdf to an output file like this:
`original_pdf_file.save(output_file.name)`
and also tried with this:
`original_pdf_file.save(output_file.name, object_stream_mode=ObjectStreamMode.generate)`
I do not see major performance improvements. Is there anything I could try from my end or the `save` method is supposed to be slow.

Note:
`output_file` is a temporary file created using:
```output_file = tempfile.NamedTemporaryFile(dir='/tmp', delete=True, suffix='.pdf')```

**Comment by pmg007** [comment]
@jbarlow83 Hey, any of your guidance would be really helpful. Thanks!

**Comment by jbarlow83** [comment]
What do you mean by "slow"?

Opening and saving are likely to be the most expensive operations. Here is sample timing I got, for open-save-close, with a local file stored in flash memory, writing to the same device. The file is 3 MB.

```
import pikepdf
p=pikepdf.open('issue149.pdf')
%timeit p.save('_.pdf')
p.close()
# 198 ms ± 616 µs per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

Depending on the input file, large amounts of data may be recompressed, for example if the file was created with obsolete compression algorithms.

**Comment by pmg007** [comment]
I have a pdf with 16 MB and has 20000 images in that which is taking around 15-20 seconds to save.

**Comment by jbarlow83** [comment]
I'd say 15-20 seconds is in line with the complexity of the file.

If you have libqpdf 10.1 or newer that has some speed improvements.

**Comment by jbarlow83** [comment]
You could try running `qpdf --check` on the file and the speed should be around the same - since most of saving happens in C++.

Unfortunately libqpdf is not threaded.

**Comment by pmg007** [comment]
Sure, thanks! I will close this for now then!
