### ISSUE TITLE
Getting compilation error while installing pikepdf, took lastest qpdf.

### ISSUE THREAD

**Issue by AnandKumar1989** [pikepdf/pikepdf#165]
building 'pikepdf._qpdf' extension
    creating build/temp.linux-x86_64-3.6
    creating build/temp.linux-x86_64-3.6/src
    creating build/temp.linux-x86_64-3.6/src/qpdf
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.6m -c src/qpdf/annotation.cpp -o build/temp.linux-x86_64-3.6/src/qpdf/annotation.o
    src/qpdf/annotation.cpp:18:10: fatal error: pybind11/pybind11.h: No such file or directory
     #include <pybind11/pybind11.h>
              ^~~~~~~~~~~~~~~~~~~~~
    compilation terminated.

**Comment by jbarlow83** [comment]
Is pybind11 installed?

**Comment by AnandKumar1989** [comment]
I have install pybind11 package and able to install pikepdf. 
Thanks.
