### ISSUE TITLE
How to use string object to manipulate a Link dictionary 

### ISSUE THREAD

**Issue by Akamad007** [pikepdf/pikepdf#170]
I want to manipulate the link/annot dictionary and rewrite part of the url with a string 

```
def main_call():
    # read your existing PDF
    existing_pdf = Pdf.open("foo.pdf")
    destination = Pdf.new()
    for page in existing_pdf.pages:
        if Name.Annots in page:

            annots = page.Annots
            for annot in annots:
                if annot.Subtype == Name.Link:
                    link_annot = annot
                    if Name.A in link_annot:
                        action = link_annot.A
                        del action[Name.URI]
                        del link_annot[Name.F]
                        link_annot[Name.A][Name.F] = **StringObject('/test/test.pdf')**
                        link_annot[Name.A][Name.S] = Name.Launch
                        link_annot[Name.A][Name.NewWindow] = True
        destination.pages.append(page)
    destination.save("destination.pdf")
```
    
    
    
   The bolded portion does not work. i.e. StringObject('/test/test.pdf') is not translated properl;y by pike pdf.  It shows up as a gibberesh object id e.g. <feff0028006100730064006100730064006100730029> in the uncompressed pdf version.

**Comment by jbarlow83** [comment]
I suppose you may have found an answer but I'll add some explanation.

That gibberish was probably the UTF-16 BE encoding of the string. If you assign the object to `'somestring'.encode('ascii')` you can force a bytes representation to be inserted into a PDF. Generally you cannot insert encoded UTF-8 bytes into a PDF; PDF predates UTF-8 and does not expect it, except in certain places where it is allowed. You can insert bytes that contain `ascii` or `pdfdoc` encoded strings in most places.

**Comment by Akamad007** [comment]
Yep adding b'test' worked as expected. Thanks
