### ISSUE TITLE
Certain characters in Annotation[/T] lead to incomplete read out of that fields content

### ISSUE THREAD

**Issue by anarchist912** [pikepdf/pikepdf#172]
We discovered that problem while building a service to fill PDF forms that have been prepared with placeholders in the name field or `/T` field.

Using a dot `.` or opening curly braces `{{` leads to parts of the content of that field being left out, if we read it with **pikepdf.** The same is true for **pdfrw** and **PyPDF2**. Which is why I guess it might be an underlying thing to handle in Python itself. The same PDF could be read out with **setalib** (PHP) just fine.

So we have `{{deliveryAddress.zip}}` in the `/T` field, and **pikepdf** reads out `zip}}` for example. Although it is really there, actually. It seems to depend on the way the file is created. When we used _MasterPDF_ (linux) to add the placeholders it works just fine. If we use _Adobe Acrobat Reader_ (Mac OS) or _Nuance Power PDF_ (Windows) it behaves as described above (w/ setalib it's fine)

We could circumvent the problem by substituting `{{` with `###` and `.` with `:`. But as soon as there is any dot or curly bracket in a `/T` field, it's all fucked up.

As pikepdf seems to be the best maintained Python lib for PDF manipulation, and also the best documented (also in terms of humour), I decided to report it here.

**Comment by jbarlow83** [comment]
Well, there are about 20 subtypes of annotation, and in each one the `/T` field has a different interpretation, because PDF is just that kind of special.

If you can provide code and a sample PDF that shows what you're trying to do, that would be helpful.

**Comment by anarchist912** [comment]
@jbarlow83 Im happy to help. That's what open source is about, isn't it?

Here is a simplified code example. In the sample PDF all annotation with `/T` are of `/Subtype` -> `widget`. Can you provide me an e-mail address or something for the PDF? I can't make it public, because it is our real customers PDF.

Currently it is with pdfrw. But I tested it with pikepdf in the Python CLI and it showed the same symptoms. If we can fix this, I'll switch to pikepdf.

```python
import pdfrw
from pdfrw import IndirectPdfDict, PdfName
from io import BytesIO
from benedict import benedict

def fill_form_pdf(pdf_list, values):
  try:
    result = []
    values = benedict(values)
    for file_object in pdf_list:
      if file_object.content_type != 'application/pdf':
        raise Exception(f'{file_object.filename} is not of type application/pdf')
      pdf = pdfrw.PdfReader(file_object.file)
      filled_pdf = BytesIO()
      for page in pdf.pages:
        for annotation in get_annotations(page):
          if not annotation['/T']:
            continue
          field_value = annotation['/T'][1:-1]
          if False:
            print("removed some other cases here")
          else:
            field_value = replace_keys(field_value, values)
          
          encoded_value = pdfrw.objects.pdfstring.PdfString.encode(field_value if field_value else '')
      
          if False:
            print("removed some other cases here")
          else:
            annotation.update(pdfrw.PdfDict(V=encoded_value, AP=create_AP(field_value, pdf), Ff=1))
      pdf.Root.AcroForm.update(pdfrw.PdfDict(NeedAppearances=pdfrw.PdfObject('true')))
      pdfrw.PdfWriter().write(filled_pdf, pdf)
    result.append((file_object.filename, filled_pdf))
    return result
  except Exception as err:
    print(repr(err), flush=True)
    raise
    
def replace_keys(field_value, values):
  keys = extract_keys(field_value)
  for key_literal in keys:
    key = key_literal.replace(':', '.')
    replace_with = values[key] if key in values else ''
    field_value = field_value.replace('###'+key_literal+'###', replace_with)
  return field_value
 
def get_annotations(page):
  return page['/Annots'] if page['/Annots'] else []

def create_AP(value, pdf):
  print("leaving this out, as it is somewhat experimental and not relevant to the issue")

```

**Comment by jbarlow83** [comment]
You can encrypt a file with my public key as described here:
https://github.com/jbarlow83/OCRmyPDF/wiki

**Comment by anarchist912** [comment]
@jbarlow83 thank you a lot. Here it is
[test.pdf.zip](https://github.com/pikepdf/pikepdf/files/6055162/test.pdf.zip)

**Comment by jbarlow83** [comment]
I'm not seeing any issues with reading or writing strings that curly braces in pikepdf.

<img width="533" alt="image" src="https://user-images.githubusercontent.com/1825843/109401683-e5f80980-7904-11eb-83bb-3efecb09681f.png">

**Comment by anarchist912** [comment]
@jbarlow83 Okay, thank you and sorry. Maybe I was not clear enough.
The issue arises only when the `/T` value is added with PDF Editors like _Adobe Acrobat_ or _Nuance Power PDF_. I have included a complete exampe, that reproduces it, with another pdf. I have also included a .ipynb file, so you just need to extract, decrypt and run it: [issue172.zip](https://github.com/pikepdf/pikepdf/files/6060478/issue172.zip)

Here everything before the dot, including the dot is cut off. If you open the PDF with an editor like Adobe, Nuance oder Master PDF you can see that the value is actually there. Something like `{{deliveryAddress.zip}}`. Because it seems to happen with `{` and `.`, we resorted to `#` and `:` for now.

![image](https://user-images.githubusercontent.com/30655359/109477406-4491c480-7a78-11eb-98b9-55517b6fca78.png)

**Comment by jbarlow83** [comment]
Here is what that object looks like when you open the PDF in a text editor:
```
32 0 obj
<</AP<</N 120 0 R>>/BS<</S/S/W 1>>/DA(/Calibri 0 Tf 0 g)/F 4/FT/Tx/Ff 0/MK 60 0 R/P 22 0 R/Q 0/Rect[ 34.0157 539.7169 102.0468 557.575]/Subtype/Widget/T(zip}})/Type/Annot/Parent 7 0 R>>
endobj
```

Note the `/T(zip}})`. That is exactly the data that is stored in the file. It would be an error if pikepdf returned any other value.

However, by inspecting the file, the /Parent object contains the first portion, `{{deliverAddress`:
```
7 0 obj
<</T({{deliveryAddress)/Kids[ 32 0 R 33 0 R]>>
```

So the full name of the field is `str(p.pages[0].Annots[8].Parent.T) + '.' + str(p.pages[0].Annots[8].T)`. Although this does not work for Annotation 12.

I'm not familiar with the relevant portion of the PDF spec so I don't know why this behavior occurs. It may be that the software you use to generate the PDF introduces errors, or it may be that this is correct behavior required by the spec that is just more complicated than expected.

**Comment by anarchist912** [comment]
Okay, that explains the behaviour. SetaLib (PHP) seems to handle this part of the PDF spec. It has a higher-level lib of functions specifically for filling PDF forms. One function gets all the form fields `/T` values. I tested it with the same PDF and it "worked as expected".

Thank you! I am closing it.
