### ISSUE TITLE
Extracting images adds a black border?

### ISSUE THREAD

**Issue by AmitMY** [pikepdf/pikepdf#175]
I have a pdf. In the pdf there is this image:
![image](https://user-images.githubusercontent.com/5757359/109708313-e8c45a00-7ba3-11eb-9c97-4717384fb27d.png)

If I extract the image with `pikepdf`, I get:
![image](https://user-images.githubusercontent.com/5757359/109708338-f083fe80-7ba3-11eb-9d3e-b7ff7c4b77a5.png)

Note, the image is saved as a `jpg`.

Is there a way to save the image without having this black border? I suspect its something to do with transparency...

Link to the PDF: https://www.signwriting.org/archive/docs10/sw0935_SignWriting_Hand_Symbols_ISWA2010_Sutton_Frost_2014.pdf

This happens on every image of a hand.

----

My code:
```python
from pikepdf import Pdf, PdfImage
from IPython.display import Image 
import os

filename = "sw0935_SignWriting_Hand_Symbols_ISWA2010_Sutton_Frost_2014.pdf"
example = Pdf.open(filename)

os.makedirs("images", exist_ok=True)

for i, page in enumerate(example.pages):
    os.makedirs("images/" + str(i), exist_ok=True)
    for j, (name, raw_image) in enumerate(sorted(page.images.items(), key=lambda x: int(x[0].replace("/Im", "")))):
        image = PdfImage(raw_image)
        f_name = "images/" + str(i) + name
        out = image.extract_to(fileprefix=f_name)
```

**Comment by jbarlow83** [comment]
There's probably a `raw_image.SMask`, which will be the alpha channel.

**Comment by AmitMY** [comment]
Thanks, that might be it.
There is a `raw_image.SMask` of type `pikepdf.objects.Object`, but I cannot print it (`NotImplementedError: don't know how to __str__ this object`)

Is there an example I can look at? I couldn't really find one or documentation

**Comment by jbarlow83** [comment]
Only string-like objects in pikepdf have a `__str__` representation. You can use `repr()` to inspect the other types.

Docs at pikepdf.readthedocs.io including some image object and working with objects.

**Comment by AmitMY** [comment]
Thanks for the help.
Solution:
```python
image = PdfImage(raw_image).as_pil_image()

if image.mode == "RGB":
  mask = PdfImage(raw_image.SMask).as_pil_image()
  image.putalpha(mask)
```
