### ISSUE TITLE
[Question] Possibility to prevent copying from pdf

### ISSUE THREAD

**Issue by zurek11** [pikepdf/pikepdf#176]
Hello. I would like to ask, if there is some possibility to prevent copying content from pdf. Thank you.

**Comment by jbarlow83** [comment]
You can encrypt the PDF with an owner password - then only someone with the owner password can access it.

You can also mark a password as "no copying" with the encryption settings; see pikepdf.Pdf.save. In reality, this is an honor system. Nothing prevents a skilled user from circumventing this restriction, but most brand name PDF viewers will enforce it.

General principle: if you share _any_ digital information with someone, they can keep a copy of it.

**Comment by zurek11** [comment]
Just for somebody, who wants to prevent copying from pdf file without encryption.

1. Created html template with content to be showed in the pdf file (one template representing one page in the resulting pdf file).
2. Created png files from corresponding html templates from first step (one png file one template) with method `write_png`.
3. Created resulting html template which contain all generated png images one per page and fitting to page.
4. Finally created resulting pdf from generated template (step 3) with method `write_pdf`.

- **As example my content from html template (step 3) looks like this**:
```html
{% load i18n %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title></title>
</head>

<style>
	@page {
		size: A4;
		margin: 0;
	}

	@media print {
		@page {
			size: landscape
		}
	}

	body {
		margin: 0;
		text-align: center;
	}

	img {
		width: 100%;
	}
</style>

<body>
{% for i in pages %}
	<img src="{% static '_images/' %}page_{{ i }}.png" alt="test">
{% endfor %}
</body>
</html>
```

**Comment by jbarlow83** [comment]
@zurek11 This does not actually prevent copying in any real way - it can be reversed easily. I will hide your comment because I don't want to propagate misinformation.
