### ISSUE TITLE
[Question] Is it possible to convert Flasks 'FileStorage' (file that comes in post request) to pikepdf pdf object?

### ISSUE THREAD

**Issue by chacken93** [pikepdf/pikepdf#177]
Hello,
I am sending pdf via api to my flask application (POST request with all needed headers)
In flask I can catch this request it and access file via `request.files`
```
files_from_request = request.files
for _param_name, file_obj in files_from_request.items():
    file_obj.read()
    file_obj.stream.read()
    (+ all 'tries' code below)
```

I can see that this file exists and was properly saved to [(FileStorage)](https://tedboy.github.io/flask/generated/generated/werkzeug.FileStorage.html#methods) object:
`ImmutableMultiDict([('file', <FileStorage: 'file2.pdf' ('application/pdf')>)])`

And now is the thing that I believe I don't understand:
In `FileStorage` documentation I can see that I can access bytes and stream via:

```
In: 
file_obj.read()

Out:
`b'%PDF-1.4\n%\xd3\xeb\xe9\xe1\n1 0 obj\n<</Creator (Chromium)\n/Producer (Skia/PDF m78)\n/CreationDate (D:20210308081625+00\'00\')\n/ModDate (D:20210308081625+00\'00\')>>\nendobj\n3 0 obj\n<</ca 1\n/BM /Normal>>\nendobj\n8 0 obj\n<</ca .098\n/BM /Normal>>\nendobj\n9 0 obj\n<</Type /XObject\n/Subtype /Form\n/Resources <</ProcSet [/PDF /Text /ImageB /ImageC /ImageI]\n/ExtGState <</G3 3 0 R>>\n/Font <</F6 6 0 R>>>>\n/BBox [0 0 2086 2485]\n/Group <</Type /Group\n/S /Transparency\n/I true>>\n/Filter /FlateDecode\n/Length 178>> stream\nx\x9cu\x8fM\n\xc3 \x10\x85\xf7\x9eb.\x103\xa3\xce\xa8\x10\xbaH\xfa\xb3.x\x83\x96\x16\n]\x94\xde\x1f*&\xd2\xc6\x12\xdc\xf8\xbd\xe7\x9by\xbe\x14i\x16\xa2\xe0c\x80\xceh\x8f\x0eY<|o\xbf>\x89A\x1dH\xd8\x02I\xf0:\xa0\x8fpy\xaa\xfed\xe1\xfeVcR\xfdQ\x80,C\xba)\x02\xcc\xa7#0\xe4@\\\xd6\x9ej\xb0n\x07\xe9\xa1r\x0c!]a\xb0\xb6p^\xb0\x08&\xcc\x02\x9a*\x8c\xcb\x0b\xaa\x11\x9cG\xe0\xc2\x93\x14\x8e\xb8\x9epH[}(2\x04\xb2\xa5\x0f\xf9u\x1f\x9a\x1a\xde7<\xf7e_\x99\x0b\x0bm\xf9\xd2\xe4\x9b\xff\xff\xf9\\\xcb\x9f\xd5\x07 (...)
``` 
and much more (cut it to make it readable)

or via:
`file_obj.stream.read()` - output of this looks like one above

and I have no idea how can I use this stream to create pikepdf Pdf object.

---------------------
I tried with 
`Pdf.open(file_obj.read())` - but it wants to open PDF file from disc

---------------------
Also tried to create new pdf and "pass stream to object"
```
dst = Pdf.new()
dst.make_stream(file_obj.read())
```
but `dst` is still empty

---------------------
`pikepdf.parse_content_stream(file_obj.stream.read())` - got error `stream must a PDF object`

---------------------
And last one - just tried to use private `_open` method from Pdf object:
```
dst = Pdf.new()
dst._open(file_obj.read(), 1)
```

found out that `1` is for stream mode: `<AccessMode.stream: 1>`
but unfortunately still got error, just different:

```
_open(): incompatible function arguments. 
The following argument types are supported:\n    
1. (filename_or_stream: object, 
password: str = '', 
hex_password: bool = False, 
ignore_xref_streams: bool = False, 
suppress_warnings: bool = True, 
attempt_recovery: bool = True, 
inherit_page_attributes: bool = True, 
access_mode: pikepdf._qpdf.AccessMode = <AccessMode.default: 0>) -> 
pikepdf._qpdf.Pdf\n\nInvoked with: b'%PDF-1.4\\n%\\xd3\\xeb\\xe9\\xe1\\n1 0 obj\\n<</Creator (Chromium)\\n/Producer (Skia/PDF m78)\\n/Cr (... loads of b'')
```

Not sure if it is even possible, any ideas what to do? 

I will appreciate any help!

PS. I tried to open this file just via directory and it works fine - I can extract all images (thats what I need this library for), the problem is just when I send it via request :/

PS2. Also tried all above commands with `file_obj.stream.read()` instead of just `file_obj.read()` but output was still the same

**Comment by jbarlow83** [comment]
You should be to do this:

```python
pdf = pikepdf.open(file_obj.stream)
```

pikepdf wants *a readable and seekable object* or a filename. It does not accept a binary dump of the file's contents as an input.

(However, a Flask FileStorage object may not be *seekable*. From what I can tell, they are. But just in case, you might need to do this:

```python
from io import BytesIO
bio = BytesIO(file_obj.stream.read()) # put the memory in a seekable wrapper
pdf = pikepdf.open(bio)
```
)

Please read here for a discussion on the various things named "stream" in PDFs. Unfortunately, there is overlapping terminology in Python and PDF around the word "stream".
https://pikepdf.readthedocs.io/en/latest/topics/streams.html

Please do not use `Pdf._open`. That is an internal API that can change without warning between pikepdf versions.

**Comment by chacken93** [comment]
Sorry, I forgot to answer, was consumed by work.

First of all thank you for answer and your time! 
It helped me a lot!

I tried second option that you suggested:
```
from io import BytesIO
bio = BytesIO(file_obj.stream.read())
pdf = pikepdf.open(bio)
```

It works like a charm ;)
Have a nice day!
