### ISSUE TITLE
2.8.0 library size jumped from 2 to 12 mb

### ISSUE THREAD

**Issue by manycoding** [pikepdf/pikepdf#178]
I noticed that the size of the latest version changed much, so it doesn't fit on our lambda.

https://pypi.org/project/pikepdf/2.8.0.post1/#files
pikepdf-2.8.0.post1-cp37-cp37m-manylinux2010_x86_64.whl (12.7 MB)

https://pypi.org/project/pikepdf/2.7.0/#files
ikepdf-2.7.0-cp37-cp37m-manylinux2010_x86_64.whl (2.3 MB)

The former has much bigger qpdf library:
libqpdf-9e9308d3.so.28.2.0 44.4mb unpacked versus libqpdf-e710ee5f.so.28.2.0 7mb

**Comment by jbarlow83** [comment]
Looks like it GitHub Actions doesn't strip the libqpdf binary. Should be easy to resolve.

**Comment by jbarlow83** [comment]
Fixed in .post2

**Comment by manycoding** [comment]
> If I may ask just out of curiosity: What exactly is your lambda? (No point in putting "lambda" into Google without context, is there?)
> 
> And as I see it, it affects all the manylinux2010 wheels in 2.8.0.post1 (i.e. it affects 4 Python Versions * 2 Arches = 8 Wheels, not just the one you mentioned).

A microservice on AWS Lambda. It has tight disk space constraints.
