### ISSUE TITLE
Interactive PDF content gets lost with n-up using as_form_xobject()

### ISSUE THREAD

**Issue by mara004** [pikepdf/pikepdf#195]
I tried to do n-up compositing using `as_form_xobject()` with a PDF document that contains interactive content, such as pictures which show overlays on hovering, videos, etc.
I noticed that all interactive content was missing in the new file. Is this a limitation of PDF Form XObjects, or a bug / not implemented feature in qpdf?
In case it is not possible in XObjects, is there any other way of doing page imposition that would preserve interactive elements?
(related to https://github.com/cfcurtis/pdfstitcher/issues/44)

**Comment by mara004** [comment]
@jbarlow83 do you have any comments on this?

**Comment by jbarlow83** [comment]
Many interactive features are usually attached to the /Root object of the PDF rather than pages. 

We rely on qpdf for Form XObjects, so it's a limitation of QPDF at the moment, although manual "repair" ought to be possible.
