### ISSUE TITLE
Dead hooked fish on doc installation page

### ISSUE THREAD

**Issue by JocelynDelalande** [pikepdf/pikepdf#197]
Thanks for that great piece of software that I am currently  discovering :)

Just to mention that there is a dead  and hooked fish on your documentation frontpage (I suppose there is no bad intent at all apart from a joke).

https://pikepdf.readthedocs.io/en/latest/installation.html

IMHO this is inappropriate at this place, that is unexpected an can hurt sensibility in an expected manner for one that just wants to learn how to install a software library.

**Comment by mara004** [comment]
Yes, I find that somewhat offensive, too, and would appreciate a removal very much.

**Comment by JocelynDelalande** [comment]
@jbarlow83 thanks for your consideration <3

**Comment by mara004** [comment]
thanks (dislike the commit message though...)
