### ISSUE TITLE
[Question] Is it able to deduplicate the same images in multiple pages?

### ISSUE THREAD

**Issue by zombie110year** [pikepdf/pikepdf#198]
I have a multi-page PDF with same image object in every page. Is it able to keep only one image object, and makes others refer to this one?

For example, with expression similar to 'ls -l'.

Before:
```
page1/i0.png
page2/i0.png
...
pagen/i0.png
```

After:
```
page1/i0.png
page2/i0.png@ -> page1/i0.png
...
pagen/i0.png@ -> page1/i0.png
```

And the PDF which I want to optimize: [cornel-32p.pdf](https://github.com/pikepdf/pikepdf/files/6352980/cornel-32p.pdf)

**Comment by jbarlow83** [comment]
I believe you can just do the following:
```
pdf.pages[1].Resources.XObject.NameOfImageOnPage1 = pdf.pages[0].Resources.XObject.NameOfImageOnPage0
```
They're just pointers.

The images may or may not have the same. What's important is that you don't change the name that a particular page uses for an image, because that is how it calls for the image.

**Comment by zombie110year** [comment]
Thanks, it works!

**Comment by zombie110year** [comment]
Ohhhh, I retried this code. Maybe the error I reported was caused by that I edited PDF with vscode's text editor automatically trimed tailing spaces... It modified binary file, but offset recorded by PDF doesn't change, so that references cannot find object.

From original PDF file, and doesn't use vscode to open PDF, the code works well.

**Comment by zombie110year** [comment]
I wrote a script to deduplicate images in pdfs. Might it will be useful for someone:

```py
from pikepdf import Pdf
from hashlib import sha256
from typing import Dict, List, Tuple

# source pdf
x = Pdf.open("cornel-32p.pdf")

# hex hash => [(page number, object name)]
image_hash: Dict[str, List[Tuple[int, str]]] = {}

# build reference table
for p in range(len(x.pages)):
    for im in x.pages[p].images.keys():
        # must record in image_hash
        obj = x.pages[p].images[im]
        hashsum = sha256(obj.read_bytes()).hexdigest()
        if hashsum in image_hash:
            image_hash[hashsum].append((p, im))
        else:
            image_hash[hashsum] = [(p, im)]

# redirect other image to first image in the same hash
for first, *others in image_hash.values():
    p0, im0 = first
    for p, im in others:
        x.pages[p].Resources.XObject[im] = x.pages[p0].Resources.XObject[im0]

# ! It seems to be unessential to remove_unreferenced_resources?
x.remove_unreferenced_resources()
# output pdf
x.save("cornel-32p_dedup.pdf", linearize=True)
```
