### ISSUE TITLE
the example fails with `del` [resolution needed: add pages.remove(p=page_number)]

### ISSUE THREAD

**Issue by jabbalaci** [pikepdf/pikepdf#20]
The example in the README fails for me:

```
$ python
Python 3.7.1 (default, Oct 22 2018, 10:41:28) 
[GCC 8.2.1 20180831] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pikepdf
>>> pdf = pikepdf.open('input.pdf')
>>> num_pages = len(pdf.pages)
>>> num_pages
8
>>> del pdf.pages[-1]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: __delitem__(): incompatible function arguments. The following argument types are supported:
    1. (self: pikepdf._qpdf.PageList, arg0: int) -> None
    2. (self: pikepdf._qpdf.PageList, arg0: slice) -> None

Invoked with: <pikepdf._qpdf.PageList object at 0x7fd21bb38378>, -1
>>>
```

Update: it doesn't like the negative indexing. With positive indexes it works:

```
>>> del pdf.pages[1]
>>> pdf.save('output.pdf')
```

Edit: one more error:

```
del pdf.pages.p(page_number)
       ^
SyntaxError: can't delete function call
```

**Comment by jbarlow83** [comment]
\#WellThatsEmbarassing

Thanks. Negative indexing will be fixed in the next release.

I don't believe `del pdf.pages.p(page_number)` is fixable. It appears that Python won't evaluate before deciding what to delete... I will need to add a `pages.remove()` function.

**Comment by jabbalaci** [comment]
`pdf.pages.remove(page_number)` sounds good. Don't forget to update the docs too: https://pikepdf.readthedocs.io/en/latest/tutorial/pages.html#using-counting-numbers where I read about `del pdf.pages.p(page_number)`. Thanks for this libary!

**Comment by jbarlow83** [comment]
`pdf.pages.remove()` is now added
