### ISSUE TITLE
[Question] How to get the size of a page as displayed or printed?

### ISSUE THREAD

**Issue by mara004** [pikepdf/pikepdf#200]
I'd like to retrieve page width and height as it would be displayed or printed by a PDF viewer. I'm a bit confused by the various boxes that exist: MediaBox, TrimBox, CropBox, BleedBox, ArtBox, ... - which one do I need to use?
At the moment, I am have the following code (based on an explanation from https://support.activepdf.com/hc/en-us/articles/360002401273-What-are-PDF-Page-Boxes):
```
# `p` is a page of a pikepdf.Pdf document
if hasattr(p, 'CropBox'):
    RelevantBox = p.CropBox
else:
    RelevantBox = p.MediaBox
size = [RelevantBox[2]-RelevantBox[0], RelevantBox[3]-RelevantBox[1]]
```
Is that correct or am I doing something wrong?

**Comment by jbarlow83** [comment]
A PDF viewer would normally use the cropbox, if defined, and fall back to mediabox, as you are currently doing.

But it is application specific. The other box types are very important in print production.
