### ISSUE TITLE
Providence of tests/resources/enron*.pdf

### ISSUE THREAD

**Issue by spwhitton** [pikepdf/pikepdf#21]
Hello,

I can't find where the files matching `tests/resources/enron*.pdf` came from.  The file `debian/copyright` (in this repository; not Debian's actual copyright file) points to enrondata.org but the download link on that site 404s.  Further, that site is about a collection of e-mails, but neither of the `enron*.pdf` files are e-mail messages.

Unless you've more information, it is probably best for me to filter out these files for Debian and disable the tests.  Let me know.

Thanks.

**Comment by jbarlow83** [comment]
You're thorough ;)

I pushed an update that adds the original location for one (it was attachment to an Enron email) and replaced the Latin one (wrong file anyway, not from Enron) with a synthetic version that exhibits the same problem.

**Comment by spwhitton** [comment]
Thanks.  After thinking about it more, I remain unconvinced that the Enron file is freely licensed.  Although enrondata.org claims a creative commons license, enrondata.org is not the copyright holder of the original e-mails, so I don't see how they can release the files under that license.  I dug out the original release of the files from web.archive.org and there is no indication that they were released under a free license.

So I'm going to filter out the remaining Enron file and disable the correponding test.  Thanks for minimising the amount of filtering I have to do by deleting one of the files :)
