### ISSUE TITLE
[Question] merge pages on top of each other

### ISSUE THREAD

**Issue by piegamesde** [pikepdf/pikepdf#210]
I'd like to "print" some pages of the same size on top of each other. I'm not really proficient with PDFs or this library, so some hint or help to get me started would be appreciated.

**Comment by jbarlow83** [comment]
pikepdf can do this but you need a bit of "glue" to tie it all together.

You can use `pikepdf.Page.as_form_xobject` to capture a whole page into a Form XObject, which is PDF's awkward and unusual name for a collection of drawable objects. You can then attach these FormX Object to a new page as resources (`pikepdf.Page.add_resource`), and set up the new page's content stream to draw them, e.g. `/FormXobj1 Do /FormXobj2 Do`. The last painted object will overwrite the first one, so if the second one is opaque (for example, an image that covers the full page), this process may not work.

Please look at the PDF reference manual for details on form xobjects and content streams.
Also see:
https://pikepdf.readthedocs.io/en/latest/topics/content_streams.html

**Comment by piegamesde** [comment]
Wow, working with this library is *astonishingly* productive. I went from having no idea about PDFs to a small prototype that takes a PDF and prints all pages on top of each other in under an hour (you may use this as an example in the documentation):

```python
from pikepdf import Pdf, Page, Name

new_pdf = Pdf.new()
pdf = Pdf.open('in.pdf')

new_page = new_pdf.add_blank_page(page_size=(3024, 4032))#(page_size=(page.trimbox.2, page.trimbox.3))

for index, page in enumerate(pdf.pages):
    object = Page(page).as_form_xobject())
	Page(new_page).add_resource(new_pdf.copy_foreign(object, Name.XObject, name=f"/Page{index}")

stream = "\n".join([f"/Page{index} Do" for index in range(0, len(pdf.pages))])
new_page.Contents = new_pdf.make_stream(stream.encode())
new_pdf.save("out.pdf")
```

Thank you for your help.
