### ISSUE TITLE
Broken type hint for pikepdf.new()

### ISSUE THREAD

**Issue by levrik** [pikepdf/pikepdf#213]
After upgrading to pikepdf 2.13.0 I'm getting the following type error with `mypy` for `pikepdf.new()`.
`Too few arguments`, the displayed signature being `new: (self: Pdf, *args, **kwargs) -> Any`.
With pikepdf 2.12.0 and lower `pikepdf.new` was just defined as `Any`, thus obviously no error.
I don't know what exactly have changed as nothing was mentioned in the changelog. I'm guessing that these typings just weren't used before for whatever reason.

I've opened a PR #214 to update the signature of `pikepdf.new()`.

**Comment by jbarlow83** [comment]
It may be mypy is getting smarter... anyway, will fix
