### ISSUE TITLE
Flip Pdf pages using pikepdf

### ISSUE THREAD

**Issue by igaurab** [pikepdf/pikepdf#215]
Hi, I had used PyPDF2 for the purpose of flipping pdf, by scaling the page by a factor or (-1,1) but it was not supported for pdf version > 1.6

I have been looking for a way to do a similar thing with pikepdf. 

I tried looking for a `scale` method on the `Page` object but didn't find one. I am sure I am missing something, could you please help me with this, if possible

Regards
Gaurab

**Comment by dreua** [comment]
Just for my understanding: By flipping, you mean rotation by 180 degree or mirroring? I know how to rotate but for mirroring I never had a use case.

**Comment by igaurab** [comment]
Hi, @dreua by flipping I mean mirroring.

**Comment by jbarlow83** [comment]
PDF usually puts the bottom left corner of the page at (0, 0) and positive up. Some people prefer to think of graphics with (0, 0) at the top left and positive down, like computer monitors. You can change the coordinate system by adding `1 0 0 -1 0 Y cm` to the beginning of a page's content stream, where Y is the height of the page's MediaBox. That's equivalent to translation, followed by scaling by (1, -1). You can then draw the content stream as if down were positive. Also, scanned transparencies often end up needing mirroring.

It's clean to capture the page as a Form XObject as described here (where we're merging two pages, but drawing a flipped page is like merging/watermarking a page with a blank page, is it not?):
https://github.com/pikepdf/pikepdf/issues/210#issuecomment-864953329

You'd use a `cm` operation to change the drawing coordinate system before the `Do`.

**Comment by igaurab** [comment]
@jbarlow83 **thank you so much** for the help. 

One thing that didn't change was the annotations(highlights etc) is there a way we can manipulate them as well so that the text and annotations could both be in sync?

For others having the same problem here is a sample code:
```
import pikepdf
from pikepdf import Pdf

file = "input.pdf"
pdf = Pdf.open(file)

# Try for a single page
page = pdf.pages[0]

commands = []
for operand,operator in pikepdf.parse_content_stream(page):
    commands.append([operand,operator])

# Generate content stream as a byte string
content_stream = pikepdf.unparse_content_stream(commands)
new_stream = b'1 0 1 -1 0 790 cm\n' + content_stream

page.Contents = pdf.make_stream(new_stream)

pdf.save('output.pdf')
```
This flips the page vertically. If you want to flip it horizontally change the content stream to

`-1 0 0 1 X 1 cm` 

where X is the width of the MediaBox

If you want to flip the current page then you can get the current height and width of the MediaBox of `page`
```
_,_,w,h = Page(page).trimbox
print(w,h)
```

**Comment by jbarlow83** [comment]
There's an API in newer versions of qpdf to help with annotations but I have not done the bindings for it yet. Should be soon-ish; will need a 3.x release because it will have to drop compatibility with older versions.

Unfortunately annotations are not well implemented in the PDF spec - they are associated with the document as a whole rather than pages, so they don't follow pages around properly and need manual adjustments.

**Comment by igaurab** [comment]
@jbarlow83 oh okay, thanks for the info :)
