### ISSUE TITLE
The pdfdoc encoding raises ValueError instead of UnicodeErrors.

### ISSUE THREAD

**Issue by regebro** [pikepdf/pikepdf#218]
Using a character that doesn't exist in `pdfdoc` encoding correctly fails, but with the wrong error.

```
>>> import pikepdf
>>> "klhkhk".encode("pdfdoc")
b'klhkhk'
>>> "klhkhkŚ ".encode("pdfdoc")
Traceback (most recent call last):
  File "/home/lregebro/Shoobx/shoobx.app/ve/lib/python3.9/site-packages/pikepdf/codec.py", line 48, in encode
    return pdfdoc_encode(input, errors)
  File "/home/lregebro/Shoobx/shoobx.app/ve/lib/python3.9/site-packages/pikepdf/codec.py", line 31, in pdfdoc_encode
    raise ValueError("'pdfdoc' codec can't encode some characters")
ValueError: 'pdfdoc' codec can't encode some characters

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: encoding with 'pdfdoc' codec failed (ValueError: 'pdfdoc' codec can't encode some characters)
```

That should be a `UnicodeEncodeError`. 

This means any code trying to encode to pdfdoc and correctly trapping encoding errors will instead fail with a ValueError. This is a extra serious problem, as if you install ReportLab, they also have a `pdfdoc` encoding, and depending on, I guess, import order, it may end up using pikepdf's encoding instead, making it impossble to save some PDF's. 

I'll make a PR shortly.

**Comment by jbarlow83** [comment]
According to the standard library .encode may return ValueError *or* a more specific subclass. What is written is correct according to the spec, but it violates reportlab's expectations, and possibly other expectations.

https://docs.python.org/3/library/codecs.html

Qpdf does not return all of the informatio  we need to raise a proper UnicodeEncodeError, or at least, did not when this code was written. Of course, if you can improve on this it would be welcome.

Also note the codec registry is messy global state at the standard library level.

I'd consider using some introspection here - if the call stack goes through reportlab, redirect to its encoder.

**Comment by regebro** [comment]
Interesting. I think **everyone** expects Unicode errors there, I have never seen anyone catch ValueErrors. But I'll file a bug for that in Reportlab as well. 

I got a fork of pikepdf for development running, and intend to look at the UnicodeError today.

> Also note the codec registry is messy global state at the standard library level.

Yeah. I was going to suggest that reportlab encoding both as "pdfdoc" and as something else, like "pdfdoc_rl" and only use the "prdfdoc_rl" internally.

Maybe pikepdf could do something similar, register it with "pdfdoc" and "pdfdoc_pike" or something, so you can be specific if you like... But pikepdf doesn't seem to actually use the encoding itself, so the clash with Reportlab won't cause problems in pikepdf.

> if the call stack goes through reportlab, redirect to its encoder.

That's not feasible, but we might be able to monkeypatch it.

**Comment by jbarlow83** [comment]
`inspect` could check if the caller is via reportlab, so it is feasible. Messy, hacky, but feasible.

Not registering "pdfdoc" as a codec would be an absolute last resort, since it's an API breaking change for other software that uses pikepdf. pikepdf has thousands of users that may depend on this behavior. I'd much rather find a way to achieve compatibility or at least a semblance of peaceful coexistence with reportlab. 

I don't see any problem with additionally registering a more specific codec name.

**Comment by regebro** [comment]
> I don't see any problem with additionally registering a more specific codec name.

Yes, that's what I proposed.

> inspect could check if the caller is via reportlab, so it is feasible.

Oh, you mean in pikepdf. I hope that won't be necessary.

**Comment by regebro** [comment]
OK, I looked at this, and no, qpdf doesn't return enough information to make a UnicodeEncodeError. We can find that info in other ways, but nothing reasonable.

However, the UnicodeError() class does NOT require that information, and I think it would be better to raise that error. This is also mentioned in the section on error handlers: https://docs.python.org/3/library/codecs.html#error-handlers
This isn't enough to fix the problem with Reportlab, but that means Reportlab can catch UnicodeError instead of UnicodeEncodingError, and that would look nicer.

I've been looking at the Python-internal error handlers, but I'm not convinced they are useable, but I haven't given up yet. :-)

**Comment by jbarlow83** [comment]
Patching qpdf to provide more info on errors is also a possibility. Qpdf's maintainer is usually happy to adopt changes to support pikepdf.

Doesn't help code in the field but helps everything in the future.

**Comment by regebro** [comment]
Yeah, improving qpdf there would be nice. But I haven't used C++ for 25 years, so I'm not going to try. :-D

**Comment by regebro** [comment]
Oh, and I gave up on using the python internal error handlers, and just changed the errors. PR submitted.
