### ISSUE TITLE
Copying multiple pages from other PDFs doesn't work

### ISSUE THREAD

**Issue by YakBizzarro** [pikepdf/pikepdf#22]
If I generate a new pdf and I try to add a page from another pdf multiple times, it fails.
More specifically, it works with 3 pages, if fails (with a Segmentation Fault) with >4. An example:

```
import pikepdf


def concatenate(number):
    print('concatenating same page', number, 'times')
    output_pdf = pikepdf.Pdf.new()
    for i in range(number):
        print(i)
        pdf_page = pikepdf.Pdf.open('/tmp/drawing.pdf')
        output_pdf.pages.extend(pdf_page.pages)
        
    output_pdf.save('/tmp/test.pdf')
    print('done')

concatenate(3)  #works
concatenate(4)  #fails
```

where drawing.pdf is a single-page pdf

**Comment by jbarlow83** [comment]
What OS?

Did you compile pikepdf yourself or use the wheel?

**Comment by YakBizzarro** [comment]
Linux, specifically a Debian testing.
I compiled it by myself, but if fails also with the wheel.
With the wheel, it fails also with n = 3, but works with n <= 2

**Comment by YakBizzarro** [comment]
Great, thank you! For the moment is fine 😊

**Comment by jbarlow83** [comment]
With v1.2.0 you should be able to do this:

```python
import pikepdf


def concatenate(number):
    print('concatenating same page', number, 'times')
    output_pdf = pikepdf.Pdf.new()
    for i in range(number):
        print(i)
        with pikepdf.Pdf.open('tests/resources/graph.pdf') as pdf_page:
            output_pdf.pages.extend(pdf_page.pages)

    output_pdf.save('_.pdf')
    print('done')

concatenate(3)  #works
concatenate(4)  #works
```

That is, it is no longer necessary to hold open.
