### ISSUE TITLE
QOL: teach Object.__contains__ to search for matching objects in arrays as well

### ISSUE THREAD

**Issue by jbarlow83** [pikepdf/pikepdf#232]
Currently __contains__ only handles dictionary and stream.

**Comment by rassie** [comment]
Oh yes, please! Had to replace `obj in arr` with `any(x for x in arr if obj == x)` because of lack of `__contains__`, which is pretty ugly...

**Comment by jbarlow83** [comment]
`obj in arr.to_list()` works with the current version.

**Comment by jbarlow83** [comment]
Fixed for v3
