### ISSUE TITLE
Real page size is not matching page size obtained via MediaBox

### ISSUE THREAD

**Issue by andrei-volkau** [pikepdf/pikepdf#234]
Let me consider the following code
```
from pikepdf import Pdf


pike_pdf_doc = Pdf.open("./example.pdf")
for pike_pdf_page in pike_pdf_doc.pages:
    width = float(pike_pdf_page.MediaBox[2])
    height = float(pike_pdf_page.MediaBox[3])
    print(width, height)
```
The code provides correct values for PDF files. But I was able to face something strange with one file.

[example.pdf](https://github.com/pikepdf/pikepdf/files/6918265/example.pdf)

The code states that the width is 391.0 pixels
The code states that the height is 612.0 pixels

GIMP is saying that the width is 450 pixels and the height is 780 pixels. Those values are real. 
![Screenshot from 2021-08-02 18-46-44](https://user-images.githubusercontent.com/12778567/127893703-503c26f0-4c44-4ed6-91a7-3feebee50d53.png)

**Question:** Is it possible to obtain those real values using pikepdf? 

Thank you in advance for any hints!

**Comment by dreua** [comment]
This really depends on your definition of the "real" values: PDFs have [different "boxes"](https://wiki.scribus.net/canvas/PDF_Boxes_:_mediabox,_cropbox,_bleedbox,_trimbox,_artbox) and Gimp is most likely not using the MediaBox but something else (maybe it's the BleedBox, who knows).

**Comment by andrei-volkau** [comment]
> This really depends on your definition of the "real" values: PDFs have [different "boxes"](https://wiki.scribus.net/canvas/PDF_Boxes_:_mediabox,_cropbox,_bleedbox,_trimbox,_artbox) and Gimp is most likely not using the MediaBox but something else (maybe it's the BleedBox, who knows).

Hi David! @dreua  Thank you for the info! I was able to walk through PDF source. I am able to see the following data structures there

```
/CropBox [26.64 35.28 350.68 596.88]
/MediaBox [0 0 391 612]
```
Something like  [0 0 450 780]  is not presented there at all. That is interesting.

**Comment by dreua** [comment]
Gimp is doing some calculations, I'd say the "Resolution" is not a "real" value but rather some default that one can and should tweak for a good trade off between file size and quality. (But that is another topic.

If you want to dig deeper into this, I'd recommend  having a look at the [PDF specification](https://www.adobe.com/content/dam/acom/en/devnet/pdf/pdfs/PDF32000_2008.pdf), especially "7.7.3.3 Page Objects" and the keyword "UserUnit". I'm not sure whether Gimp is the gold standard here or why you need exactly those values.

**Comment by rassie** [comment]
Resolution in GIMP is set to 100 pixels per inch, as visible in the image. If you set the resolution to 72 pixel/inch, in which case a pixel equals one PDF unit, you'll get 324x562 units, which is exactly the crop box size. Since the crop box is actually set in the PDF, you shouldn't be looking at the media box for printing matters. Both pikepdf and GIMP are right, you just have to get your resolutions right :)

**Comment by andrei-volkau** [comment]
@dreua @rassie many thanks for all the comments. That makes sense. I am closing the issue. 
There exist one off-top question. Do you know hoe to make the CropBox equal to the MediaBox using pikepdf?

```
/CropBox [26.64 35.28 350.68 596.88]
/MediaBox [0 0 391 612]
```

Those are my efforts using PyPDF2.
```
from PyPDF2 import PdfFileWriter, PdfFileReader

output = PdfFileWriter()
input = PdfFileReader(open('example.pdf', 'rb'))

n = input.getNumPages()

for i in range(n):
    page = input.getPage(i)
    page.cropBox.upperLeft = (0, 0)
    page.cropBox.lowerRight = (391, 612)
    output.addPage(page)

outputStream = open('result.pdf', 'wb')
output.write(outputStream)
outputStream.close()
```

I am having the following result. So they are still not equal. 

```
/CropBox [ 0 612 391 0 ]
/MediaBox [ 0 0 391 612 ]
```
