### ISSUE TITLE
Hello world

### ISSUE THREAD

**Issue by jorisschellekens** [pikepdf/pikepdf#235]
Is there a succinct example of creating a PDF document containing the classic "Hello World!" phrase?

**Comment by dreua** [comment]
I'm not sure pikepdf is the best tool for that. I only use it to manipulate existing PDFs. It should be possible, though, but you'll probably need to know some of the PDF specification.

**Comment by jbarlow83** [comment]
There is a test case in test_sanity.py that builds a PDF from scratch, but yes, other PDF generators may be easier to work with.
