### ISSUE TITLE
[Question] Performance of checking page equality

### ISSUE THREAD

**Issue by mara004** [pikepdf/pikepdf#236]
I am using pikepdf to read the outline ("bookmarks") of PDF documents, which involves comparing the resolved page to the document's pages in order to determine the page number an outline item is pointing to (#149, #173).
I noticed that my code is very slow (reading the outline of the PDF 1.7 specification takes about 5 seconds). The `get_toc()` method of PyMuPDF is much faster. After some analysis, I found out that the most time-consuming part of my code is comparing pages:
```python
for i, page in enumerate(pdf.pages):
    if resolved == page:
        page_number = i
        break
```
**Question:** Is there any way of comparing pages faster than the above code, for the purpose of outline reading? How does PyMuPDF achieve its excellent performance?

**Comment by mara004** [comment]
I am wondering whether I could use threading. I guess there may be no significant performance improvement due to the GIL, but I haven't tried yet.

**Comment by jbarlow83** [comment]
`pikepdf.Page.index` be used to find a page number.

Threading usually won't help, as you mention, due to GIL.

**Comment by mara004** [comment]
Thanks, using `pikepdf.Page(resolved).index` seems to have slightly improved performance. I overlooked this ;)

**Comment by mara004** [comment]
FYI, I just rewrote my code with threading out of curiosity (using `concurrent.futures.ThreadPoolExecutor().map()`), and noticed that it even lead to a performance decrease.
