### ISSUE TITLE
Extend compatibility of PdfImage helper model

### ISSUE THREAD

**Issue by mara004** [pikepdf/pikepdf#237]
I wrote a method to extract images from PDF documents, using the [`PdfImage`](https://pikepdf.readthedocs.io/en/latest/api/models.html#pikepdf.PdfImage) helper of pikepdf. I tested that method on all files in my home directory and noticed that `PdfImage` fails a lot.
Many of these failures were caused by images in CMYK or P colourspace (about 60 documents affected). Examples:
```
pikepdf.models.image.UnsupportedImageTypeError: <pikepdf.PdfImage image mode=CMYK size=2480x3508 at 0x7fedae1ffc40>
pikepdf.models.image.UnsupportedImageTypeError: <pikepdf.PdfImage image mode=P size=2187x447 at 0x7feda8bbd2e0>
```

I also came across some different exceptions, though:
```
NotImplementedError: <unprintable NotImplementedError object> (14x)
NotImplementedError: not sure how to get colorspace: [...] (2x)
NotImplementedError: palette with CMYK (2x)
ValueError: unrecognized raw mode (1x)
NotImplementedError: Not sure how to handle PDF image of this type (1x)
pikepdf._qpdf.PdfError: [...] (offset 171782): getStreamData called on unfilterable stream (1x)
-> pikepdf.models.image.UnsupportedImageTypeError: <pikepdf.PdfImage image mode=RGB size=200x129 at 0x7feda8bb6a90>
OSError: cannot open profile from string (1x)
-> pikepdf.models.image.UnsupportedImageTypeError: ICC profile corrupt or not readable
```

Would it be possible to add support for these kinds of images in the PdfImage helper model?
I can share the affected documents and full tracebacks if necessary.

**Comment by jbarlow83** [comment]
Yes, it would be helpful to see the files that cause this problem.
If you like you can GPG encrypt them - see instructions here:
https://github.com/jbarlow83/OCRmyPDF/wiki

**Comment by mara004** [comment]
Thanks, I will upload the documents. Might take some time.

**Comment by mara004** [comment]
One example for each issue. I had to append the `.txt` extensin since GitHub apparently does not permit `.gpg` files.
The `Not sure how to handle PDF image of this type` document is too large for share over GitHub, unfortunately.
[unrecognised_raw_mode.pdf.gpg.txt](https://github.com/pikepdf/pikepdf/files/6950668/unrecognised_raw_mode.pdf.gpg.txt)
[unprintable_not_implemented_err.pdf.gpg.txt](https://github.com/pikepdf/pikepdf/files/6950669/unprintable_not_implemented_err.pdf.gpg.txt)
[palette.pdf.gpg.txt](https://github.com/pikepdf/pikepdf/files/6950670/palette.pdf.gpg.txt)
[palette_with_cmyk.pdf.gpg.txt](https://github.com/pikepdf/pikepdf/files/6950671/palette_with_cmyk.pdf.gpg.txt)
[not_sure_how_to_get_colourspace.pdf.gpg.txt](https://github.com/pikepdf/pikepdf/files/6950673/not_sure_how_to_get_colourspace.pdf.gpg.txt)
[getStreamdata_called_on_unfilterable_stream.pdf.gpg.txt](https://github.com/pikepdf/pikepdf/files/6950674/getStreamdata_called_on_unfilterable_stream.pdf.gpg.txt)
[cmyk.pdf.gpg.txt](https://github.com/pikepdf/pikepdf/files/6950675/cmyk.pdf.gpg.txt)
[cannot_open_profile_from_string.pdf.gpg.txt](https://github.com/pikepdf/pikepdf/files/6950676/cannot_open_profile_from_string.pdf.gpg.txt)

**Comment by mara004** [comment]
[not_sure_how_to_handle_pdfimage_of_this_type.pdf.gpg](https://drive.google.com/u/0/uc?id=1TOTHUUW71X1cm8KEax9yNXAVZ0sFkVOk&export=download) (Google Drive)

**Comment by mara004** [comment]
This is the code I used to extract images
[imageextractor.py.txt](https://github.com/pikepdf/pikepdf/files/6950720/imageextractor.py.txt)

**Comment by jbarlow83** [comment]
I made several improvements and it is actually possible to extract images from some of these files.

Summary: 
- unrecognised_raw_mode.pdf - now extractable
- unprintable_not_implemented_err.pdf - uses DeviceN colorspace, now returns correct error message
- palette.pdf - now extractable (with warnings)
- palette_with_cmyk.pdf.gpg.txt - defines Separation colorspace
- not_sure_how_to_get_colourspace.pdf.gpg.txt - defines Separation colorspace
- getStreamdata_called_on_unfilterable_stream.pdf - now extractable (had an A85 encoded image)
- cmyk.pdf - in progress
- cannot_open_profile_from_string.pdf - as far as I can tell the error message is correct and the ICC Profile is invalid or corrupt; manually deleting the ICC profile might help

Files with Separation or DeviceN colorspaces mean that they have been prepped for printing on high fidelity printers (e.g. printers that can do Pantone spot colors). Generally speaking, it's not possible to extract that information from a PDF to a raster image without losing data, apart from the user making a conscious decision to rewrite the data.

**Comment by mara004** [comment]
Wow, thanks for investigating.
For my use case, I would prefer if there were an option to accept lossy actions (issue a warning and continue) when unavoidable for extracting the image (like Separation / DeviceN colourspaces, or invalid colour profiles). 
I feel a lossily extracted image is still better than no image at all ;)

**Comment by jbarlow83** [comment]
There will be a new exception for attempts to extract high fidelity print images when I release the changes. I'd suggest that you trap the exception and manually rewrite the image's colorspace to be /DeviceGray or something and extract it to see if that's meaningful. In many cases the color assignments are sort of monotonic and that may be sufficient.

We could implement the PostScript instructions in Annex B of the PDF RM which is used to define a mapping to CMYK for these fancy inks, but I'm not in a hurry to do that.

**Comment by mara004** [comment]
From looking at the commits, a new major release of pikepdf (v3) will happen sometime soon?

**Comment by mara004** [comment]
I'm currently testing the pikepdf 3 beta and the improvements are really noticable! My CMYK images now work :)
