### ISSUE TITLE
[Question] OutlineItem viewport position

### ISSUE THREAD

**Issue by mara004** [pikepdf/pikepdf#239]
I use the [OutlineItem](https://pikepdf.readthedocs.io/en/latest/api/models.html#pikepdf.models.OutlineItem) support model to add bookmarks to PDFs. I tried to also define a viewport position using the left/top/zoom parameters but noticed that my arguments took no effect on the output PDF.
I find the documentation is a bit unclear on these parameters (`"Describes the viewport position associated with a destination"`). I assumed that `top` means the y coordinate in PDF units where the viewer should jump to when clicking on the outline item. I also ensured the values are floats, as the documentation indicates. For example, I set `top` to `630.0` (meaning `22.225 cm`) to make the viewport jump to around `5.7 cm` below an A4 page's top border (`27.9 cm`).
What am I doing wrong?

**Comment by jbarlow83** [comment]
Can you provide code and/or a test file?

The viewport is just advisory information for the PDF viewer which can be ignored - I think Acrobat and Reader specifically have settings to ignore. The main thing I can do is check if we generate the appropriate data structures correctly.

**Comment by mara004** [comment]
It's a bit complicated. What I do is I read out the outline items of input documents and associate them to page-representing objects. Each outline item is described by a custom object that stores properties like title, position and zoom, a unique id, and the id of the parent outline item if existent. The page objects can be rearranged/deleted/manipulated freely; pages from other documents can come in. Finally, a new pikepdf.Pdf is created according to this data structure; the outline item objects attached to pages are converted back to a structure of item & kids. This way I can do arbitrary rearranging while preserving the table of contents.
Here's an example (using [document 3](https://github.com/pikepdf/pikepdf/files/5572410/example_3.pdf) from https://github.com/pikepdf/pikepdf/issues/149#issuecomment-731043485):
```python
[
    WriteOutlineHelper(BookmarkInfo('Title Page', 2, 0, top=630.0, item_id='0x7f173f6a96a0')),
    WriteOutlineHelper(BookmarkInfo('Copyright Page', 3, 0, top=708.75, item_id='0x7f173f6a96d0')),
    WriteOutlineHelper(BookmarkInfo('Dedication', 4, 0, top=585.0, item_id='0x7f173f6a97f0')),
    WriteOutlineHelper(BookmarkInfo('CONTENTS', 5, 0, top=678.0, item_id='0x7f173f6a9820')),
    WriteOutlineHelper(BookmarkInfo('JUSTICE', 6, 0, top=678.0, item_id='0x7f173f6a9850'),
        kids=[
            WriteOutlineHelper(BookmarkInfo('1. DOING THE RIGHT THING', 6, 1, top=678.0, item_id='0x7f173f6a98b0', parent_id='0x7f173f6a9850')),
            WriteOutlineHelper(BookmarkInfo('2. THE GREATEST HAPPINESS PRINCIPLE / UTILITARIANISM', 33, 1, top=678.0, item_id='0x7f173f6a98e0', parent_id='0x7f173f6a9850')),
            WriteOutlineHelper(BookmarkInfo('3. DO WE OWN OURSELVES? / LIBERTARIANISM', 60, 1, top=678.0, item_id='0x7f173f6a9910', parent_id='0x7f173f6a9850')),
            WriteOutlineHelper(BookmarkInfo('4. HIRED HELP / MARKETS AND MORALS', 77, 1, top=678.0, item_id='0x7f173f6a9940', parent_id='0x7f173f6a9850')),
            WriteOutlineHelper(BookmarkInfo('5. WHAT MATTERS IS THE MOTIVE / IMMANUEL KANT', 104, 1, top=678.0, item_id='0x7f173f6a9970', parent_id='0x7f173f6a9850')),
            WriteOutlineHelper(BookmarkInfo('6. THE CASE FOR EQUALITY / JOHN RAWLS', 141, 1, top=678.0, item_id='0x7f173f6a99a0', parent_id='0x7f173f6a9850')),
            WriteOutlineHelper(BookmarkInfo('7. ARGUING AFFIRMATIVE ACTION', 167, 1, top=678.0, item_id='0x7f173f6a99d0', parent_id='0x7f173f6a9850')),
            WriteOutlineHelper(BookmarkInfo('8. WHO DESERVES WHAT? / ARISTOTLE', 183, 1, top=678.0, item_id='0x7f173f6a9a00', parent_id='0x7f173f6a9850')),
            WriteOutlineHelper(BookmarkInfo('9. WHAT DO WE OWE ONE ANOTHER? / DILEMMAS OF LOYALTY', 207, 1, top=678.0, item_id='0x7f173f6a9a30', parent_id='0x7f173f6a9850')),
            WriteOutlineHelper(BookmarkInfo('10. JUSTICE AND THE COMMON GOOD', 243, 1, top=678.0, item_id='0x7f173f6a9a60', parent_id='0x7f173f6a9850'))
        ]
    ),
    WriteOutlineHelper(BookmarkInfo('NOTES', 268, 0, top=678.0, item_id='0x7f173f6a9880')),
    WriteOutlineHelper(BookmarkInfo('ACKNOWLEDGMENTS', 302, 0, top=678.0, item_id='0x7f173f6a9a90')),
    WriteOutlineHelper(BookmarkInfo('INDEX', 304, 0, top=678.0, item_id='0x7f173f6a9ac0'))
]
```
I create pikepdf outline items like this:
```python
# `info` is a BookmarkInfo object
item = pikepdf.OutlineItem(
        title=info.title,
        destination=info.page,
        page_location=info.page_location,
        left=info.left,
        top=info.top,
        right=info.right,
        bottom=info.bottom,
        zoom=info.zoom,
    )
```

I think the issue is not related to the PDF viewer since positioning works correctly with the original document.
I will check my code again whether I made a mistake that causes positions not to be applied correctly, but I currently can't find one.

**Comment by mara004** [comment]
Hah, found the issue. One needs to set page_location to PageLocation.XYZ for the position properties to take effect. Then it works just fine!
