### ISSUE TITLE
ImportError: cannot import name 'AttachedFileSpec' 

### ISSUE THREAD

**Issue by barbaramenendez** [pikepdf/pikepdf#242]
I am trying to read the attachment files in a pdf, but I am not able to import AttachedFileSpec. 

I was trying to do what it says in the following link to get the attachments files in a pdf:
https://pikepdf.readthedocs.io/en/latest/topics/attachments.html

`
from pikepdf import Pdf, AttachedFileSpec
from pathlib import Path

pdf = Pdf.open(file_path)
pdf.Attachments
`

**Comment by dreua** [comment]
Which version of pikepdf are you using? (`print(pikepdf.__version__)`) I think this feature is very new, maybe it hasn't made it to a release at all, yet.

It's also not in the "stable" documentation: https://pikepdf.readthedocs.io/en/stable/topics/attachments.html (404)

**Comment by dreua** [comment]
I think you found a bug or an error in the documentation here:

```
>>> import pikepdf
>>> pikepdf.__version__
'3.0.0b1'
>>> from pikepdf import Pdf, AttachedFileSpec
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'AttachedFileSpec' from 'pikepdf' (/tmp/tmp.EeGcVO61hB/lib64/python3.9/site-packages/pikepdf/__init__.py) 
```

**Comment by dreua** [comment]
It works only in the latest (bleeding edge) built from source. I just verified this in a venv via:

```
git clone git@github.com:pikepdf/pikepdf.git
cd pikepdf/
pip install .
```

(The 3.0.0b1 does not include this latest change, it is literally in a commit from yesterday.)

**Comment by barbaramenendez** [comment]
Thank you very much! It has helped me a lot! 

Do you know when this latest change will be included to access it by pypi?

**Comment by dreua** [comment]
> Do you know when this latest change will be included to access it by pypi?

Depends 100% on when the maintainer @jbarlow83 uploads it. Probably as beta in the next few weeks, not sure what the plans on stable are. (You can install betas [from pypi](https://pypi.org/project/pikepdf/#history) by specifying the exact version: e.g. `pip install pikepdf==3.0.0b1`)

**Comment by mara004** [comment]
pikepdf 3.0.0b2 got released yesterday, so you should be able to use AttachedFileSpec now.

**Comment by barbaramenendez** [comment]
Amazing !! Thank you!

**Comment by dreua** [comment]
(@barbaramenendez I guess you are new to GitHub: You can close this issue yourself if you think that it is resolved.)

**Comment by barbaramenendez** [comment]
I did not see your answer, I see it is already closed. Thank you!
