### ISSUE TITLE
Text inside fillable form turn invisible

### ISSUE THREAD

**Issue by skasidej** [pikepdf/pikepdf#247]
I've come across some weird issue where users with Windows cannot see any other language other than English that being render into the PDF form fields. Personally don't think it came from the library itself, but has anyone ever stuck with this problem before?

Reproduce
- in my case, i'm rendering both Thai and English language into fillable PDF form fields in different files

Issues
- PDF with Thai language is showing as invisible text, you can copy them (value shows normally after clicked the field 😒)
- PDF with Thai language is having this problem mainly on Windows OS (i'm using Max OS)

A bit desperate here, but if any of you have this kind of problem please feel free to share your solutions.

**Comment by skasidej** [comment]
@jbarlow83 Not quite sure what process do you mean, but just simply open the file -> fill out form fields -> set all appearance -> save (as stream).

Here is the example file [pp30_th.pdf](https://github.com/pikepdf/pikepdf/files/7071515/pp30_th.pdf)

**Comment by jbarlow83** [comment]
How is this issue related to pikepdf? It seems like you are having a problem with some PDF software, maybe Acrobat.

**Comment by skasidej** [comment]
@jbarlow83 I've already mentioned that it's not from the library itself. Just curious if there is anyone came across this particular problems. Thanks for replying though!

**Comment by jbarlow83** [comment]
This issue page is for issues that have to do with pikepdf. The question you asked is off topic and a waste of volunteers' time.

Please get technical support for your software from your software vendor.
