### ISSUE TITLE
[Question] How to modify values in operands?

### ISSUE THREAD

**Issue by canedha** [pikepdf/pikepdf#253]
After parsing the pdf with:
```py
with pikepdf.Pdf.open(input_pdf) as pdf:
    page = pdf.pages[0]
    for operands, command in parse_content_stream(page):
        commands.append([operands, operator])
```
one of my operands looks like this:

`pikepdf._qpdf._ObjectList([Decimal('9.867683')])`

How can I change the value? e.g. to

`pikepdf._qpdf._ObjectList([Decimal('1.857583')])`

and unparse it back into the pdf stream?

**Comment by jbarlow83** [comment]
You can replace the operands with a standard Python list, e.g. `commands.append(([1.857], operator))`
Note that a tuple of a `(operands, operator)` should be appended (or better, append a `ContentStreamInstruction`)

Big picture: pikepdf returns some internal data types to improve performance, but if you insert plain Python types into the command list it should automatically convert them.

**Comment by jbarlow83** [comment]
Also note, the returned objects are immutable (like a list of tuples). You should create new ones rather than trying to edit the existing ones.

**Comment by canedha** [comment]
> Also note, the returned objects are immutable (like a list of tuples). You should create new ones rather than trying to edit the existing ones.

Sorry for answering so late! With your help, I got it to work :) 
Thank you so much!
