### ISSUE TITLE
ValueError: overflow/underflow converting to 64-bit integer on .check()

### ISSUE THREAD

**Issue by borwickatuw** [pikepdf/pikepdf#254]
In calling `.check()` on around 90 large, varied PDFs, I received 2 `ValueError`s, "overflow/underflow converting <gigantic number> to 64-bit integer".

```
    issues = pdf_obj.check()
  File "[...]/pikepdf/_methods.py", line 601, in check
    page.parse_contents(discarding_parser)
ValueError: overflow/underflow converting -[308 digit number] to 64-bit integer
```

This is using pikepdf v3.0.0 + Python 3.8.11.

I am fine just catching/ignoring this error in the check? But I didn't know to expect a ValueError.

**Comment by jbarlow83** [comment]
Looks like pikepdf doesn't handle that the error properly so it escapes from .check(). I cannot tell whether this is a real problem or noise. A 308 digit number in a content stream doesn't sound normal. What does `qpdf --check` say?

**Comment by borwickatuw** [comment]
ahh gotcha. qpdf gives the same error (just not the ValueError part):

```
PDF Version: 1.7
File is not encrypted
File is not linearized
ERROR: overflow/underflow converting -[same 308 digit number] to 64-bit integer
```

(In case it's helpful for anyone, this is with qpdf 10.3.2.)

So I guess this is a qpdf/PDF thing rather than a pikepdf thing. Looks like qpdf generates this message here: https://github.com/qpdf/qpdf/blob/36c7c208191a0fd34cf48bdfb4af66b4ab0ec594/libqpdf/QUtil.cc#L372 . There's a comment in the header file:

```
    // These string to number methods throw std::runtime_error on
    // underflow/overflow.
```
