### ISSUE TITLE
Setting TrimBox does not work

### ISSUE THREAD

**Issue by mara004** [pikepdf/pikepdf#257]
I need to reset TrimBox to MediaBox and convert to floats in a certain case. I basically did:
```python3
>>> mediabox = [float(x) for x in page.MediaBox]
>>> print(mediabox)
[0.0, 0.0, 612.0, 792.0]
>>> page.TrimBox = mediabox
>>> print(page.TrimBox)
pikepdf.Array([ Decimal('0'), Decimal('0'), Decimal('612'), Decimal('792') ])
```

Setting TrimBox seems to take no effect ... ?

I also tried `page.TrimBox = pikepdf.Array(mediabox)` but it does not work either.

**Comment by jbarlow83** [comment]
pikepdf.Object cannot store a float. If you try to store a float, it gets automatically converted to Decimal, assuming such conversion is possible (e.g. NaN will fail).

TrimBox is usually used in production printing to indicate the size the page will be cut after printing with overbleed. It's up to the PDF viewer whether to display the trimbox or cropbox. I believe in Acrobat this is configurable in the settings, and in print preview it always uses trimbox. CropBox is the one that is usually used to indicate what a digital PDF viewer program should display.

**Comment by mara004** [comment]
> pikepdf.Object cannot store a float. If you try to store a float, it gets automatically converted to Decimal, assuming such conversion is possible (e.g. NaN will fail).

Ah, that makes sense. The reason I wanted to convert to float was for reszing the box using `+=`/`-=` and floats, but this can be done in a different way.

> TrimBox is usually used in production printing to indicate the size the page will be cut after printing with overbleed. It's up to the PDF viewer whether to display the trimbox or cropbox. I believe in Acrobat this is configurable in the settings, and in print preview it always uses trimbox. CropBox is the one that is usually used to indicate what a digital PDF viewer program should display.

With Okular/Poppler, I noticed that TrimBox doesn't take any effect if it's set on a page. However, if the page is converted to a Form XObject, it does.
