### ISSUE TITLE
add_overlay() does not reset the transformation matrix, with hilarious results

### ISSUE THREAD

**Issue by gcr** [pikepdf/pikepdf#259]
We're processing PDF files for a popular computer vision conference. Part of this process involves adding a banner to the top of the first page. However, once in a while, a truly incredible specimen hits our publication pipeline. Here's one that has me scratching my head.

![image](https://user-images.githubusercontent.com/45252/135872036-1867a9ea-de1d-4b48-a3e1-fc6b2206bf43.png)

* [`a.pdf`](https://github.com/pikepdf/pikepdf/files/7278876/a.pdf)
* [`b.pdf`](https://github.com/pikepdf/pikepdf/files/7278875/b.pdf)
* [`out.pdf`](https://github.com/pikepdf/pikepdf/files/7278874/out.pdf)

This PDF, [`a.pdf`](https://github.com/pikepdf/pikepdf/files/7278876/a.pdf), starts by flipping the transformation matrix along the Y axis. Looks like this happens outside the transformation stack, so it's never undone; the `cm` command is outside the `q` and `Q`. I suppose the rest of the page content is encoded bottom-to-top? Not quite sure. It looks okay in an ordinary viewer, somehow:
```python
a = pikepdf.Pdf.open("a.pdf") # see attachment
page = a.pages[0]
stream=pikepdf.parse_content_stream(page)
print(pikepdf.unparse_content_stream(stream[:5]).decode('utf-8'))
print("...")
print(pikepdf.unparse_content_stream(stream[-5:]).decode('utf-8'))
```
```pdf
1 0 0 -1 0 841.889764 cm
q
0 0 0 rg
/a0 gs
BT
...
[ (gests) -322 (a) -323 (no) 15 (v) 15 (el) -322 (approach) -323 (for) -322 (v) 25 (arious) -323 (data) -322 (scarcity) -323 (problems.) ] TJ
0 -1.199988 Td
[ (Suppose) -338 (that) -338 (we) -338 (ha) 20 (v) 15 (e) -338 (a) -338 (scene) -338 (te) 15 (xt) -338 (dataset) -338 (and) -338 (a) -338 (synthetic) ] TJ
ET
Q
```
I'm not sure how the authors could have generated such a PDF file. I suppose they might have used some PDF editor to flip/rotate the page maybe? We're reaching out to them to figure out what could have happened.

When we try to add [`b.pdf`](https://github.com/pikepdf/pikepdf/files/7278875/b.pdf) as an overlay, `b.pdf` is flipped upside-down (see image, or see resulting [`out.pdf`](https://github.com/pikepdf/pikepdf/files/7278874/out.pdf)):
```python
out = pikepdf.Pdf.new()
out.pages.append(page)
b = pikepdf.Pdf.open("b.pdf") # see attachment
out.pages[0].add_overlay(b.pages[0])
out.save("out.pdf") # see attachment
```

* **Is there an easy way to fix this?** I suppose I could insert an operation that resets the transformation matrix, but it would be nice if I didn't have to.
* **Can I detect when this happens automatically?** I have 1600 PDF files and would prefer not to comb through them manually

**Comment by jbarlow83** [comment]
You're correct that the problem is the lack of a `q/Q` pair surrounding the original content stream. The easiest thing to do is just add your layer as an underlay instead, in which case it will go before the rest of the content stream everything should look right.

It would also work to surround the original page's content stream with a `q/Q` so that the original transformation matrix is restored. e.g.

```python
Page.contents_add(b'q', prepend=True)
Page.contents_add(b'Q', prepend=False)
Page.contents_coalesce()  # tidy up
...
Page.add_overlay(...)
```

(I'm 50/50 on whether to make pikepdf do this automatically. Sometimes people want to do weird things on purpose, normally content streams are surrounded by q/Q to support appending, and detecting that we need a q/Q requires parsing the whole stream.)

**Comment by gcr** [comment]
This seems to work, though I worry about nesting too many q/Qs (one PDF has 18 levels of nesting out of 28 required in the specification)!

Thanks for the help! If I were to add a mention of this issue to the docs and/or add an off-by-default parameter to `add_overlay`, would you entertain such a patch?

**Comment by jbarlow83** [comment]
Thinking about this some more, it should be an *on-by-*default parameter with an explanation in the docs that the existing content stream may be modified and multiple content streams may be coalesced.

It would be great if you have a chance to do a PR for this.

In practice most PDF viewers don't enforce the very low nesting limit you mention, at least as far as I've found. They'll let PDFs go much deeper before complaining.

**Comment by borwickatuw** [comment]
FWIW this one got me too. When adding page numbers to pages, some of the time the page numbers were upside down and backwards. I switched to add_underlay() per this issue.
