### ISSUE TITLE
Question - What is pikepdf.save actually doing?

### ISSUE THREAD

**Issue by thothloki** [pikepdf/pikepdf#262]
I am trying to emulate what pikepdf.save() is doing with arguments and qpdf

I need to rewrite a script I did in python wit pikepdf into c# for a project. I have a pdf that has a restriction that does not allow me to combine with other pdf documents. When I use pikepdf.save(pdf-file), that restriction is gone. When I do the same thing with qpdf, the restriction remains.
I tried looking through the source code to see what it is doing, but I think i got lost in the weeds. 
Is there any way you could tell me what pikepdf.save() adds to the qpdf in the way of arguments so I can get a pdf with that restriction removed?

**Comment by jbarlow83** [comment]
Use `Pdf.save(...encryption=True)` to preserve the encryption and permissions of the original file. When this parameter is omitted, permissions are removed. You could also adjust the permissions by providing a different encryption settings dictionary.

See here for an example of using qpdf to remove permissions:
https://ourcodeworld.com/articles/read/937/how-to-remove-the-password-of-a-pdf-using-the-qpdf-cli

I suppose it was a bit of an oversight that omitting `encryption=` from `Pdf.save` removes encryption by default. Maybe I'll fix that in that in the next major release - I don't think removing encryption should be default behavior.

**Comment by thothloki** [comment]
> Use `Pdf.save(...encryption=True)` to preserve the encryption and permissions of the original file. When this parameter is omitted, permissions are removed. You could also adjust the permissions by providing a different encryption settings dictionary.
> 
> See here for an example of using qpdf to remove permissions: https://ourcodeworld.com/articles/read/937/how-to-remove-the-password-of-a-pdf-using-the-qpdf-cli
> 
> I suppose it was a bit of an oversight that omitting `encryption=` from `Pdf.save` removes encryption by default. Maybe I'll fix that in that in the next major release - I don't think removing encryption should be default behavior.

I actually like it removing the encryption by default. I am just curious how pikepdf calls qpdf with the .save() and removes it by default. Like what is the argument that actually removes the encryption without a password?
I have been playing around with just qpdf and trying to sync up the arguments for it with what I "think" pike is calling, but have had no luck

**Comment by jbarlow83** [comment]
The API call is `QPDFWriter::setPreserveEncryption(false)`. It may be that this parameter is not exposed at the command line interface in qpdf.

If it's a file that you can open without a password and remove its encryption, then it is possible when one of the owner or user password are blank.
