### ISSUE TITLE
remove_unreferenced_resources in thread block main thread

### ISSUE THREAD

**Issue by kbengs** [pikepdf/pikepdf#263]
```
#!/usr/bin/env python3

import pikepdf
import threading
import time
from timeit import default_timer as timer


def pikepdf_thread():
    pdf_output = pikepdf.Pdf.new()
    pdf_input = pikepdf.open('/tmp/870 pages.pdf')
    npages = len(pdf_input.pages)

    for p in range(npages):
        current_page = pdf_input.pages[p]
        print(p)
        new_page = pdf_output.copy_foreign(current_page)
        pdf_output.pages.append(new_page)

    print('remove_unreferenced_resources start')
    pdf_output.remove_unreferenced_resources()
    print('remove_unreferenced_resources end')

    print('save start')
    pdf_output.save('/tmp/test_out.pdf')
    print('save end')

    pdf_input.close
    pdf_output.close

start = timer()
thread = threading.Thread(target=pikepdf_thread)
thread.start()
while thread.is_alive():
    time.sleep(1)
    print('main thread elapsed time ', timer() - start)
```
This code print elapsed time once a second, but when the code comes to remove_unreferenced_resources the main thread stop printing. Once the command is done printing continue.

Tested with pikepdf 2.13 and 3.1.1.

Do you have any idea why remove_unreferenced_resources does not behave well with threading?

**Comment by jbarlow83** [comment]
I assume this is a large PDF. `remove_unreferenced_resources` potentially does a lot of work, and it currently holds the GIL while doing all of it, because I don't know if it's safe to release the GIL. 

It would definitely be unsafe to have a second Python thread modifying the `Pdf` in any way while this function is called. It could be safe to have another Python thread is doing nothing related to the `Pdf`, but this is a fairly complex condition to test and difficult for an application to guarantee.

**Comment by kbengs** [comment]
Okay. Yes it's a large PDF. What I am trying to do is to save pdf in a separate thread in pdfarranger so that window does not freeze while saving. It seems to work fine except for the ```remove_unreferenced_resources``` part (which can take several minutes). Everything related to pikepdf is moved to the saving thread, so I guess releasing GIL should be safe in this case, but I don't know.

Saving can be done with multiprocessing also. Maybe I should do it that way.

**Comment by kbengs** [comment]
Saving and `remove_unreferenced_resources` is done with multiprocessing now so this issue is not relevant for us more.
