### ISSUE TITLE
Unskip CPython 3.10 on Windows since lxml wheel is now available

### ISSUE THREAD

**Issue by nadilo72** [pikepdf/pikepdf#267]
On Oct. 30 Cpython 3.10 wheel has been skipped on Windows because lxml wasn't avaible for this particular config.
lxml publish a Windows CPython 3.10 wheel on Nov. 2.
So eccaeb7 can be revert

**Comment by jbarlow83** [comment]
Thanks

**Comment by jbarlow83** [comment]
Will do a quick release
