### ISSUE TITLE
Tiff images are inverted (pdf file with CCITTFaxDecode /BlackIs1 param is set 1 )

### ISSUE THREAD

**Issue by KKM1983** [pikepdf/pikepdf#269]
The tiff images are inverted when decoding the image with CCITTFaxDecode.
In _generate_ccitt_header (models/image.py) the photometry should be set to 0 when black_is_one is true otherwise 1

From Tiff spec: (https://www.awaresystems.be/imaging/tiff/tifftags/photometricinterpretation.html)
PHOTOMETRIC_MINISWHITE = 0;
PHOTOMETRIC_MINISBLACK = 1;

When "/BlackIs1" decode param is set to True, then min value of 0 represents white and so the PhotometricInterpretation  should be zero.

**Comment by piegamesde** [comment]
I can reproduce it, for example with this file: https://imslp.org/wiki/File:PMLP02259-FChopin_Fantaisie-impromptu,_Op.66_BH13.pdf https://s9.imslp.org/files/imglnks/usimg/e/ea/IMSLP139195-PMLP02259-FChopin_Fantaisie-impromptu,_Op.66_BH13.pdf

**Comment by piegamesde** [comment]
This is keeping me up at night. Tried to debug with different files but only got even more confused.

@jbarlow83 please help, those lines are from you and I'd really like to know why Pikepdf is doing the inverse and it still works most of the time.

**Comment by jbarlow83** [comment]
Some programs misuse or ignore the setting.

**Comment by piegamesde** [comment]
You are probably right. I did some testing and noticed that the "correct" behavior for my test PDFs would be to always set `photometry = 0` regardless of `BlackIs1`\*. This can easily be achieved externally without modifying the pikepdf code through `image.DecodeParms.BlackIs1 = False`.

I know that it should not work and I don't understand why it does, but here we go 🤷

\* The obvious implication would be that the `BlackIs1` tag is set erroneously, which I falsified by changing the tag and checking that the PDF got inverted.

**Comment by jbarlow83** [comment]
I found that Evince (OSS PDF viewer) essentially sets photometry = 0 for all CCITT and disregards BlackIs1, so it seems like that is what is expected even though it contradicts the PDF spec :shrug: 
https://gitlab.gnome.org/GNOME/evince/-/blob/main/backend/tiff/tiff2ps.c#L852-865

I'll change it.
