### ISSUE TITLE
Read PDF from bytes from s3

### ISSUE THREAD

**Issue by houssam7737** [pikepdf/pikepdf#270]
Hi, 

Is there a way to create a pdf object from bytes directly? I'm essentially looking for an equivalent to `pikepdf.open(path)` but that reads pdf bytes directly.
I couldn't find anything in the docs.

Thank you!

**Comment by jbarlow83** [comment]
Just do:
```python
from io import BytesIO
pdf = pikepdf.open(BytesIO(my_bytes))
```
