### ISSUE TITLE
Bug when calling copy_foreign multiple time on the same page

### ISSUE THREAD

**Issue by jeromerobert** [pikepdf/pikepdf#271]
PikePDF version: 3.2.0 and 4.0.1
qpdf version: 10.3.2

Calling `copy_foreign` multiple time on the same page does not work properly. At least `MediaBox` and `Rotate` are not copied the second time.

```python
# Using qpdf 10.3.2-2
import pikepdf
import copy
f1=pikepdf.Pdf.new()
f2=pikepdf.Pdf.new()
p1=f1.add_blank_page()
# copy p1 to f2 and change its mediabox
p2=f2.copy_foreign(p1)
p2.MediaBox[0]=1
p2.Rotate=1
# Make an other copy of p1 to f2
p3=f2.copy_foreign(p1)
# both assertion fail
# p3 have the p2 MediaBox instead of the p1 MediaBox
assert p3.MediaBox[0] == p1.MediaBox[0]
assert p3.Rotate == p1.Rotate
```

This looks similar to #80 but the workaround no longer works:

```
Traceback (most recent call last):
  File "bugpikepdf.py", line 9, in <module>
    p2=copy.copy(f2.copy_foreign(p1))
  File "/usr/lib/python3.9/copy.py", line 92, in copy
    rv = reductor(4)
TypeError: cannot pickle 'pikepdf._qpdf.Page' object
```

**Comment by jbarlow83** [comment]
It's better to use
```python
f2.pages.append(p1)
```
to copy pages. `copy_foreign` is for non-pages, although it accepts pages for backward compatibility with the pikepdf.Page change in pikepdf 3+. I decided to explicitly deprecate `copy_foreign` on a pikepdf.Page.

I also fixed the issue related to attempts to use `copy.copy()` on Pages.

Despite this, for its own reasons QPDF (the underlying library) has complex behavior around transferring pages between PDFs. It has a cache that "notices" it has previously copied the page from one PDF to another and acts accordingly.

To work around this, duplicate the page within `f2` using e.g. `f2.pages.append(f2.pages[-1])`. Or you could close `f1` and reopen it. Yes, this is awkward, but I don't believe I can workaround QPDF's internal behavior. I'll report the issue there. Its author is planning other improvements to the pages API.

**Comment by jeromerobert** [comment]
> To work around this, duplicate the page within f2 using e.g. `f2.pages.append(f2.pages[-1])`

Thank you, it works.

**Comment by masanf** [comment]
Hi both,

I believe my issue could be related to this and hope you can help me with it. Having File_A with three pages, I rotate the first one 90 degrees and save it as File_B. If I try to rotate the first page of File B and save it as new one, it does not work. Perhaps I have not been able to make it work.

I try to do it by creating a new file and appending to that file all the pages from the input file and then duplicating the pages (workaround). I might be doing this wrong. 

`    

    from pikepdf import Pdf

    def rotate_pages(item, result, deg, new_file):
            j = len(new_file.pages) 
            new_file.pages.append(new_file.pages[-1])
            del new_file.pages[j:]
            if "-" in item:
                x,y = item.split('-')
                result.extend(range(int(x), int(y) + 1))
                for q in result:
                    new_file.pages[q - 1].Rotate = int(deg)
            else:
                new_file.pages[int(item) - 1].Rotate = int(deg)


    src_file = ./File_A.pdf         """File contains three pages"""
    page_range = "1"                """Ranges type: 1,4-6,..."""
    out_file = ./File_B.pdf
    deg = "90"

    new_file = Pdf.new()
    input_file = Pdf.open(src_file, allow_overwriting_input=True)
    for n, page in enumerate(input_file.pages):
        new_file.pages.append(input_file.pages[n])

    for item in page_range.split(','):
        result = list()
        rotate_pages(item, result, deg, new_file)

        new_file.save(out_file)

`

Many thanks!

**Comment by jbarlow83** [comment]
@masanf Your issue does not seem to be about `copy_foreign`. Please open a new issue and in particular include your pikepdf and libqpdf version.
