### ISSUE TITLE
Can you provide binary wheels for aarch64 Linux?

### ISSUE THREAD

**Issue by willangley** [pikepdf/pikepdf#272]
I'm working in a [Multipass] VM on a macOS Apple Silicon machine, which provides a virtual aarch64 Linux environment:

```
pdf_sprinkles$ uname -a
Linux pdfsprinkles 5.4.0-90-generic #101-Ubuntu SMP Fri Oct 15 20:02:26 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux
```

I tried installing pikepdf with `pip install pikepdf==3.2.0`, and got compilation errors. I re-read the [Installation](https://pikepdf.readthedocs.io/en/latest/installation.html) instructions, and realized this was happening because there wasn't a binary wheel available and I'd need to build from source.

I was able to do this, but it was a little tricky to figure out, and binary wheels are definitely easier to work with 😄. Could you provide binary wheels for aarch64 Linux, possibly using your existing macOS Apple Silicon build machine?

[Multipass]: https://multipass.run

**Comment by jbarlow83** [comment]
I build Apple Silicon manually when I remember to do it. The latest release 4.0.1.post1 has aarch64.

I've tried automating it. Emulation is too slow and cross compilation is too flakey.
