### ISSUE TITLE
Is it possible to attach files from bytes?

### ISSUE THREAD

**Issue by aron89682** [pikepdf/pikepdf#273]
The docs show this example:
filespec = AttachedFileSpec.from_filepath(pdf, Path('../README.md'))

Is it possible to take a file from memory instead?

**Comment by jbarlow83** [comment]
Yes, just use `AttachedFile(pdf, data_in_memory, ....)` constructor.

**Comment by aron89682** [comment]
Would you be able to provide a working example for how to use this?  I keep running into different errors, I'm not using it correctly.

**Comment by jbarlow83** [comment]
There are some examples in the test suite, tests/test_attachments.py, e.g. https://github.com/pikepdf/pikepdf/blob/6f3e25e561dd3347c01d7824c60237a7c204e0d7/tests/test_attachments.py#L83

**Comment by jbarlow83** [comment]
Added - what kind of errors are you running into?
https://pikepdf.readthedocs.io/en/latest/topics/attachments.html

**Comment by aron89682** [comment]
Thanks, with your much appreciated help, I was able to get it working, it was 100% user error.  I must have kept overlooking AttachedFileSpec(pal, b'some data') in the tests.  Anyway, thanks again for the help!
