### ISSUE TITLE
cannot specify OpenAction

### ISSUE THREAD

**Issue by josch** [pikepdf/pikepdf#282]
I want the PDF Catalog to contain an `/OpenAction` that specifies how viewers should magnify the document. For example, the following should fit the given page so that it is fully visible (assuming that 2 0 obj is the first page):

    << /OpenAction [ 2 0 R /Fit ] /Pages 3 0 R /Type /Catalog >>

I'm unable to create such a PDF with pikepdf. Consider the following code:

```python
import pikepdf
doc = pikepdf.new()
doc.add_blank_page()
doc.Root[pikepdf.Name.OpenAction] = pikepdf.Array([doc.pages[0], pikepdf.Name.Fit])
doc.save("out.pdf")
```

This will create the following Catalog:

    << /OpenAction [ << /Contents 2 0 R /MediaBox [ 0 0 612 792 ] /Parent 3 0 R /Resources << >> /Type /Page >> /Fit ] /Pages 3 0 R /Type /Catalog >>

So instead of a reference to the first page, the first page is put directly into the catalog. This results in an error with Adobe Acrobat. So lets make that an indirect object instead:

```python
import pikepdf
doc = pikepdf.new()
doc.add_blank_page()
doc.Root[pikepdf.Name.OpenAction] = pikepdf.Array([doc.make_indirect(doc.pages[0]), pikepdf.Name.Fit])
doc.save("out.pdf")
```

Now the first page is indeed an indirect object but the first page appears *twice* in the resulting PDF:

```
<< /OpenAction [ 2 0 R /Fit ] /Pages 3 0 R /Type /Catalog >>
endobj
2 0 obj
<< /Contents 4 0 R /MediaBox [ 0 0 612 792 ] /Parent 3 0 R /Resources << >> /Type /Page >>
endobj
[...]
endobj
5 0 obj
<< /Contents 4 0 R /MediaBox [ 0 0 612 792 ] /Parent 3 0 R /Resources << >> /Type /Page >>
endobj
```

Another creative result is created when saving with `linearize=True`:

```python
import pikepdf
doc = pikepdf.new()
doc.add_blank_page()
doc.Root[pikepdf.Name.OpenAction] = pikepdf.Array([doc.make_indirect(doc.pages[0]), pikepdf.Name.Fit])
doc.save("out.pdf", linearize=True)
```

The resulting PDF will not have the first page appearing twice, but the indirect object reference in the catalog is no invalid `0 0 R`:

    << /OpenAction [ 0 0 R /Fit ] /Pages 1 0 R /Type /Catalog >>

Am I using pikepdf wrong or is this one or more bugs?

**Comment by jbarlow83** [comment]
As a workaround it should work to use 
make_indirect(doc.pages[0].obj) wherever you want to make a reference. 

But the behaviour you're seeing should not be happening and is likely due to the changes in the v3 release.

**Comment by josch** [comment]
Thanks, this works if I don't use `linearize=True`. With `linearize=True` I still get `0 0 R` even when I use `.obj`. Is that a separate bug?

**Comment by jbarlow83** [comment]
That is probably a QPDF bug. I’ll look into it. 

>

**Comment by jbarlow83** [comment]
I checked everything out more carefully.

If done this way, everything works as you'd expect:

```python
import pikepdf
doc = pikepdf.new()
doc.add_blank_page()
doc.Root[pikepdf.Name.OpenAction] = pikepdf.Array([doc.pages[0].obj, pikepdf.Name.Fit])
doc.save("out.pdf", linearize=True)  # or linearize=False
```

By using `make_indirect` you are requesting a shallow copy of the object to be added to the PDF and a reference returned. So pikepdf behaves correctly here, just not in a way that either of us found intuitive, which is a problem I will have to address.
