### ISSUE TITLE
Changing XObj Stream fails

### ISSUE THREAD

**Issue by PeterXGrau** [pikepdf/pikepdf#284]
From the tutorial I learned that I can change the stream content with:
```py
pdf=pikepdf.open('test.pdf')
page = pdf.pages[0]
for operands, operator in pikepdf.parse_content_stream(page):
    commands.append([operands, operator])
new_content_stream = pikepdf.unparse_content_stream(commands)
page.Contents = pdf.make_stream(new_content_stream)
pdf.save("test_new.pdf")
```

This works perfectly.
However when I try to change the stream of an XObj that is within a page, 

```py
pdf=pikepdf.open('test.pdf')
xobj = pdf.objects[10] #or pdf.pages[0].Resources.XObject['/obj10'] 
for operands, operator in pikepdf.parse_content_stream(xobj):
    commands.append([operands, operator])
new_content_stream = pikepdf.unparse_content_stream(commands)
xobj.Contents = pdf.make_stream(new_content_stream)
pdf.save("test_new.pdf")
```

it somehow fails and the stream is not changed after saving. I assume the mistake to be in the line, that the stream is not correctly written/updated to the XObj:

```py
xobj.Contents = pdf.make_stream(new_content_stream)
```

I tried without `.Contents`, with `.obj10`, `pdf.objects[10]` and other variants but nothing worked. Most likely I miss a something else or have to update another dictionary etc...

**Comment by jbarlow83** [comment]
XObjects don't have Contents - attach the content stream to the XObject itself.

**Comment by PeterXGrau** [comment]
> XObjects don't have Contents - attach the content stream to the XObject itself.

Thats what I thought, but I can't figure out how to do it correctly. 
I tried for example:

```py
xobj = pdf.make_stream(new_content_stream)
```

But when I save and read out the stream, the changes were not saved somehow.
Can you tell me how the correct command would look like?

**Comment by PeterXGrau** [comment]
@jbarlow83 
has it maybe something to do that the XObject is nested within another XObj? From my understanding that shouldn't be a problem?
I tried using:


```py
xObjToChange = pdf.pages[0].Resources.XObject['/Obj1'].Resources.XObject['/Obj10']

...

xObjToChange = pdf.make_stream(new_content_stream)
```

but again it's not saving the changes.

**Comment by jbarlow83** [comment]
I was on mobile earlier so had to be terse. Your original should be changed to something like:

```python
pdf=pikepdf.open('test.pdf')
xobj = pdf.objects[10] #or pdf.pages[0].Resources.XObject['/obj10'] 
for operands, operator in pikepdf.parse_content_stream(xobj):
    commands.append([operands, operator])
new_content_stream = pikepdf.unparse_content_stream(commands)
xobj = pdf.make_stream(new_content_stream)
xobj.Resources = ...
pdf.pages[0].Resources.XObject['/obj10'] = xobj
pdf.save("test_new.pdf")
```

i.e. the object created by `pdf.make_stream` and assigned the name `xobj` is just floating in the PDF with nothing referring to it. If you want other objects to reference it, you need to update those.

Generally Python doesn't write-through variable names in the way you are perhaps expecting it to, e.g.
```python
lst = [1, 2, 3]
obj = lst[1]
obj = 'foo'  # does not change lst[1]
assert lst[1] == 2
```

**Comment by PeterXGrau** [comment]
thx! that makes perfectly sense. I struggled with this kind of behaviour already a couple of times.
what I still dont understand, why it then works in the tutorial? you create a floating around variable "page" by

```py
page = pdf.pages[0]
```
change your stream and assign it to the still floating

```py
page.Contents = pdf.make_stream(new_content_stream)
```

then you can save without assigning it anywhere specifically in the pdf, but when you save it, changes are still there?

Furthermore, what do I need to put into this line? 
> xobj.Resources = ...
or is it just IF the changes would also affect the ressources like images? that would mean if I e.g. only change the stroke style or line thickness, I don't need this line?

btw. Thank you so much for this awesome help!

**Comment by jbarlow83** [comment]
Stale
