### ISSUE TITLE
How to add OCG layer?

### ISSUE THREAD

**Issue by PeterXGrau** [pikepdf/pikepdf#286]
Is there a command to add an OCG layer?

**Comment by jbarlow83** [comment]
No, but you can build one using the available tools.

**Comment by PeterXGrau** [comment]
> No, but you can build one using the available tools.

Thx for the quick response! I'll give it a try 😊

**Comment by PeterXGrau** [comment]
@jbarlow83 I tried to simply create needed dictionaries like /OCProperties, /D, /OCGs and fill in needed information, but it failed.
When checking with a pdf structure viewer, the structure is there but a label icon is missing. See below: 
![structure2](https://user-images.githubusercontent.com/96450885/147293444-1cb20d33-d10a-4ef0-a165-02a7fe1f4ad5.png)
Left: the one I created manually, not working (layers not shown in adobe)
Right: working one

also when checking the pdf.Root.OCProperties under /OCGs the a working layered pdf shows something like:
`"/OCGs": [ <.get_object(5, 0)>, ...`
while my file shows the array and not an object...

Can you tell me where I screw up? Does it have something to do with indirect objects? Can you show me how to create a OCG layer?

**Comment by jbarlow83** [comment]
It looks like the OCGs and OCGProperties need to be created as indirect objects. You can use Pdf.make_indirect() for that.
