### ISSUE TITLE
Parse/Unparse of XObj seems to lose contents/information

### ISSUE THREAD

**Issue by PeterXGrau** [pikepdf/pikepdf#287]
I try to modify an XObj. Steps are:

1. xobj = page.Resources.XObject['/ObjectName']    
2. ParsedXObj= pikepdf.parse_content_stream(xobj)
3. Modifying commands
4. new_content_stream = pikepdf.unparse_content_stream(ParsedXObj)
5. page.Resources.XObject['/ObjectName'] = pdf.make_stream(new_content_stream)

When I compare the XObj before and after, it seems that some elements ob the XObj are missing 

old (partly):
<pikepdf.Stream(owner=<...>, data=<...>, {
    "/BBox": [ Decimal('19.8425'), Decimal('51.0236'), Decimal('575.433'), Decimal('822.047') ],
    "/Filter": "/FlateDecode",
    "/Length": 1258,
    "/Resources": {
      "/ExtGState": {
        "/GS0": {

.... and so on.

new (COMPLETE!):
<pikepdf.Stream(owner=<...>, data=<...>, {
    "/Filter": "/FlateDecode",
    "/Length": 1158
  })>

anyone knows how to preserve the missing elements?

**Comment by jbarlow83** [comment]
When you just want to replace a content stream's data and preserve all of its existing keys, use `Object.write()`.

If you want to construct a new stream object, you need to copy the data over manually (minus /Filter and /Length), becase `pdf.make_stream` operates on all stream objects, not just content streams. Copying the contents of the old object is not necessarily valid or correct.

**Comment by PeterXGrau** [comment]
Thanks for the reply! I figured the copying out by try & error, but the info on make_stream is really helpful nonetheless!
thanks also for the info about object.write!
