### ISSUE TITLE
Layer names not decoded properly?

### ISSUE THREAD

**Issue by mara004** [pikepdf/pikepdf#288]
[layers_map.pdf](https://github.com/pikepdf/pikepdf/files/7780364/layers_map.pdf) (https://www.edcfiresafe.org/wp-content/uploads/2015/12/Using-Layerd-PDFs-with-Sample-Map.pdf)

When printing the layer names of the attached document using pikepdf, there is an awkward `ÿþ` prefix at some strings, which makes me think something might be wrong with the way how pikepdf/qpdf is decoding them (In Okular PDF viewer, there are no such prefixes).

```
Title Block
ÿþLayers
ÿþGraticule
ÿþOther
ÿþLabels
Road - Highway
Road - Major
Road - Minor
ÿþSchool
River Annotation
ÿþFire Station
ÿþSchool Site
ÿþRoad
ÿþTreatment Area
CL-1 Project
ÿþFire District
ÿþColoma Lotus FSC
Vegetation and Topography
```

This is the code I use to get a list of layer names (derived from pdfstitcher):
```python3
class LayerFilter:
    # ...    

    @staticmethod
    def _search_names(ordered_names, name_object, depth=0):
        for o in name_object:
            if '/Name' in o.keys():
                name = str(o.Name)
                if name not in ordered_names:
                    ordered_names.append(name)
            elif depth == 0:
                LayerFilter._search_names(ordered_names, o, depth=depth+1)
    
    @staticmethod
    def get_layer_names(doc):
        # reads through the root to parse out the layers present in the file
        if '/OCProperties' not in doc.Root.keys():
            return []
        ocp = doc.Root.OCProperties
        names = [str(oc.Name) for oc in ocp.OCGs]
        ordered_names = []
        if '/D' in ocp.keys() and '/Order' in ocp.D.keys():
            LayerFilter._search_names(ordered_names, ocp.D.Order)
        for n in names:
            if n not in ordered_names:
                ordered_names.append(n)
        return ordered_names
```

**Comment by jbarlow83** [comment]
@mara004 Did you find a solution?

**Comment by mara004** [comment]
No... I just closed the issue because this is the only affected file that I have, so this is rather low priority for me.

**Comment by jberkenbilt** [comment]
@mara004 The problem is that the PDF file has strings encoded with UTF-16-LE, which is not a valid PDF encoding. UTF-16 is supposed to UTF-16-BE in PDF. I suppose it would be possible for qpdf to detect and handle this. If you'd like to make it a feature request, please open an issue with qpdf. I imagine it would be an easy change.
