### ISSUE TITLE
Editing page labels

### ISSUE THREAD

**Issue by FelixFrog** [pikepdf/pikepdf#290]
Hello! I am trying to find a way to edit page labels in a pdf. I know that pikepdf does not really have a way to edit them, so I tried to to build the /Pagelabels object myself from primitive types, but I can't find a way to create a NumberTree. I can't find a mention in the documentation on how to create a NameTree from scratch nor how to set an item once created.

Is it something that can be done in pikepdf directly?

**Comment by jbarlow83** [comment]
Not currently - libqpdf does not have an API for editing page labels. It does have an API editing NumberTrees, but pikepdf doesn't have bindings for it yet.

**Comment by jbarlow83** [comment]
v5.4 adds the NumberTree API, so you can edit the page label definitions

**Comment by mara004** [comment]
Thanks!
