### ISSUE TITLE
Issues when rotating already rotated pages

### ISSUE THREAD

**Issue by masanf** [pikepdf/pikepdf#291]
Hi,

First of all I would like to apologize if something I say does not make sense. I am a newbie in python.

pikepdf version: 4.2.0 (no version of libqpdf)

I have issues when trying to rotate pages that have been already rotated as the PDF somehow detects the original orientation that specific page had and it does not performthe correct new rotation. Having File_A with three pages, I rotate the first one 90 degrees and save it as File_B. If I try to rotate the first page of File B additional 90 degrees and save it as new one, it does not work. Perhaps I have not been able to make it work.

    from pikepdf import Pdf

    def rotate_pages(page_range, out_file, item, input_file, result):
        
            if "-" in item:
                x,y = item.split('-')
                result.extend(range(int(x), int(y) + 1))
                for q in result:
                    input_file.pages[q - 1].Rotate = 90
            else:
                input_file.pages[(int(item) - 1)].Rotate = 90

    src_file = ./File_A.pdf         """File contains three pages"""
    page_range = "1"                """Ranges type: 1,4-6,..."""
    out_file = ./File_B.pdf
    deg = "90"

    input_file = Pdf.open(src_file)
    for item in page_range.split(','):
         result = list()
         rotate_pages(page_range, out_file, item, input_file, result)

     input_file.save(out_file)

This code has been adapted as it is part of a larger project.

Many thanks for this fantastic library.

**Comment by mara004** [comment]
I'm using the [`rotate()`](https://pikepdf.readthedocs.io/en/latest/api/models.html#pikepdf.Page.rotate) method of the page support model for this. `page.rotate(rotation, relative=True)` should work.

The issue with your code is that you don't take existing rotation into account - you'd have to check whether the page already has a `Rotate` value and add that.

**Comment by masanf** [comment]
@mara004, thanks a lot for your help and the tip. Method `rotate(90, relative=True)` works perfectly. 

I tried to include the condition `relative=True` before but I did it totally wrong as I kept using `pages.Rotate = 90` and could not successfully include relativeness in there.

**Comment by mara004** [comment]
Nice!

It shouldn't be difficult to do this with your previous approach, probably something like this would also work:
```python3
existing_rot = 0

# check whether is rotated already
if '/Rotate' in page:
    existing_rot = page.Rotate

# set page Rotate to existing value plus new value for relative rotation
page.Rotate = existing_rot + 90
```
