### ISSUE TITLE
Is it possible to get a list of all OCG layer of a pdf file?

### ISSUE THREAD

**Issue by berndhahnebach** [pikepdf/pikepdf#296]
It is not a issue but a question.

Is it possible to retrive a list of all OCG layer of a pdf file with pikepdf?

cheers bernd

**Comment by jbarlow83** [comment]
Yes you can check in the PDF Reference Manual where this data structure is stored and manipulate it using pikepdf. As you can with anything that can be done in a PDF. 

We don't have any wrappers to make accessing them easier however.

**Comment by berndhahnebach** [comment]
thanks for your information
