### ISSUE TITLE
Parsing & Rebuilding stream loses InlineImages

### ISSUE THREAD

**Issue by harshdonga** [pikepdf/pikepdf#299]
Hello!

I am working around with pikepdf to juggle with pdf contents and it has been wonderful

But I have encountered, when i try to parse the pdf content and just rebuild the stream, the output does not contain the <pikepdf.PdfInlineImage> images

My code:

```
    try:
        file_content.seek(0)
        pdf = pikepdf.Pdf.open(io.BufferedReader(file_content))
    except:
        return None
    
    try:
        for pdx, page in enumerate(pdf.pages):
            stream_content = pikepdf.parse_content_stream(page)

            for idx, command in enumerate(stream_content):
                operands, operator = command

        rebuilt_content_stream = pikepdf.unparse_content_stream(stream_content)
        page.Contents = pdf.make_stream(rebuilt_content_stream)
        stream_content = pikepdf.parse_content_stream(page)
            
    except Exception as ex:
        print(f"Failed : {ex}")

    
    stream_output = io.BytesIO()
    pdf.save(stream_output)
    return stream_output
```

Attaching:
1. Before pdf page
2. After pdf page
3. The pdf itself

![pikepdf1](https://user-images.githubusercontent.com/41797494/152529607-f5bd3390-e2b3-41e6-bd8d-8b455be6296f.png)
![pikepdf2](https://user-images.githubusercontent.com/41797494/152529615-c87e0f33-6415-4cc6-9b19-af5aa2a10fb2.png)
[iebe101.pdf](https://github.com/pikepdf/pikepdf/files/8002973/iebe101.pdf)

**Comment by harshdonga** [comment]
@jbarlow83 @EdwardBetts  can someone have a look on this please?

I understand you do have a great deal of work on your plate already, but it will really help me out if you can comment on this!

**Comment by harshdonga** [comment]
@jbarlow83 
i think i have provided the info, do you need anything more to look upon this?

sorry to bother so much, but it ll be really helpful if you do

**Comment by jbarlow83** [comment]
Sorry, won't have time to look at anything till April at the earliest.
