### ISSUE TITLE
Some images in PDF cannot be extracted

### ISSUE THREAD

**Issue by HuntFeng** [pikepdf/pikepdf#301]
It is great that pikepdf can extract images from PDF. 

I was trying to extract figures from a research paper. Here is the link if you want to try it
https://drive.google.com/file/d/14p2T_7hjycnB-Zuy1F6LoceiRYFMDqMF/view?usp=sharing

```
from pikepdf import Pdf, PdfImage

pdf = Pdf.open('the pdf in the link above')
for page in pdf.pages[1:]:
    for raw_name, raw_image in page.images.items():
        image = PdfImage(raw_image)
        name = raw_name.replace("/","")
        if (image.width > 400) & (image.height > 400):
            image.extract_to(fileprefix=f"Image/{page.index}-{name}")
```

Here are some of the figures I successfully extracted

![6-Im1](https://user-images.githubusercontent.com/33592421/152718606-7ffd4183-366f-4aff-95d1-f7828d5b302a.jpg)
![8-Im3](https://user-images.githubusercontent.com/33592421/152718607-5843a06f-f93e-4875-91c6-31600d5f2197.png)

But I was not able to get rest of the figures, for example the two figures on pdf.pages[3] (page 3, counting from 0)
![image](https://user-images.githubusercontent.com/33592421/152718780-992b682e-4115-4fa0-82c4-5ef09d730ae0.png)

Can someone help me to figure out this problem? Thank you so much.

**Comment by jbarlow83** [comment]
I suspect that those are vector images not raster. We can only export raster images with pikepdf. For vector images you can't really decouple them from the PDF because a vector image is a list of drawing commands in PDF format.

**Comment by jbarlow83** [comment]
Had a look at the file - they're definitely vector images.

**Comment by HuntFeng** [comment]
> Had a look at the file - they're definitely vector images.

I see, then I need to figure out another way to extract these images. Thank you very much! This is super helpful! I have been looking for answers related to this for several hours already!

**Comment by jbarlow83** [comment]
Using e.g. Acrobat, you could extract the pages and crop the PDF to just the image, and then save to a vector format like SVG. Not sure if Acrobat can save as SVG but MuPDF can.

There is unfortunately no easy way to isolate a vector image. Sometimes the whole thing is grouped in a FormX Object, but in the general case the page contents are not necessarily drawn in order, so you can't tell what commands are part of a particular image.
