### ISSUE TITLE
Building a linux docker image on mac m1 fails with missing qpdf .h files

### ISSUE THREAD

**Issue by plamb-viso** [pikepdf/pikepdf#304]
Creating this so others will find it when google searching.
 
While attempting to get pikepdf using wheel:
`Constants.h` comes up as the first missing file if you're only including qpdf
`QPDFFileSpecObjectHelper.hh` comes up as the first missing file if you include libqpdf-dev

I'm running some integration tests using a docker image that is built on my M1 Mac. I tried the slew of solutions to missing qpdf .h files from other issues and none worked. I inspected the docker output in verbose mode and found it doing this:

```
#5 2.464 The following additional packages will be installed:
#5 2.464   libqpdf21
#5 2.487 The following NEW packages will be installed:
#5 2.487   libqpdf21 qpdf
#5 2.522 0 upgraded, 2 newly installed, 0 to remove and 36 not upgraded.
#5 2.522 Need to get 794 kB of archives.
#5 2.522 After this operation, 2208 kB of additional disk space will be used.
#5 2.522 Get:1 http://deb.debian.org/debian buster/main arm64 libqpdf21 arm64 8.4.0-2 [392 kB]
#5 2.565 Get:2 http://deb.debian.org/debian buster/main arm64 qpdf arm64 8.4.0-2 [402 kB]
```

In essence, it was detecting my M1 and grabbing the arm64 versions of libqpdf21 and qpdf. It must be that these files do not include the missing .h files.

In my docker-compose.yml, i passed `platform: linux/amd64` under the relevant service to force docker to use amd/64 and it worked.

**Comment by plamb-viso** [comment]
Closing since the solution is above

**Comment by flooie** [comment]
Thank you for this, I was struggling with this bug and was building qpdf manually for my m1 machine.  

I just wanted to add that you can add platform to your base image line if you aren't using a compose file or simply want to have it bundled into the dockerfile.  

`FROM --platform=linux/amd64 python:3.10-slim`

**Comment by jbarlow83** [comment]
Lobby Microsoft to provide arm64 build workers for GitHub Actions so open source developers can automate builds like we want to. This is well within their fiscal and technical capacity.

$0.02.
