### ISSUE TITLE
Can't convert ObjectHelper (or subclass) to Object implicitly. Use .obj to get access the underlying object.

### ISSUE THREAD

**Issue by josch** [pikepdf/pikepdf#313]
With pikpedf 5.0.0 img2pdf now fails with the following error:

```
Traceback (most recent call last):
  File "/home/josch/annex/personal/projects/img2pdf/./src/img2pdf.py", line 3975, in main
    convert(
  File "/home/josch/annex/personal/projects/img2pdf/./src/img2pdf.py", line 2341, in convert
    pdf.tostream(kwargs["outputstream"])
  File "/home/josch/annex/personal/projects/img2pdf/./src/img2pdf.py", line 1111, in tostream
    initial_page = self.writer.make_indirect(initial_page)
TypeError: Can't convert ObjectHelper (or subclass) to Object implicitly. Use .obj to get access the underlying object.
```

What is the recommended way that will make img2pdf compatible with both old and new pikepdf versions? Thanks!

**Comment by jbarlow83** [comment]
This should do it:

```
def get_page_obj(thing):
    if isinstance(initial_page, pikepdf.Page):
        return initial_page.obj
    else:
        return initial_page
```

**Comment by josch** [comment]
Thanks! That works. Can you tell me which pikepdf version this changed so that I can record it in the commit message?

**Comment by jbarlow83** [comment]
https://pikepdf.readthedocs.io/en/latest/release_notes.html#v3-0-0

**Comment by josch** [comment]
It cannot have been 3.0.0. The problem did not occur with version 4.2.0 but it did with 5.0.0. I see nothing related to this problem in the release notes between 4.2.0 and 5.0.0.

**Comment by josch** [comment]
I wanted to send another friendly ping to this issue. Could you check which version of pikepdf changed this? It cannot have been 3.0.0 because the problem did not occur with 4.2.0.

Thanks!
