### ISSUE TITLE
[Question] How to use a compression command from qpdf in pikepdf

### ISSUE THREAD

**Issue by nefyodovve** [pikepdf/pikepdf#314]
With qpdf I can do the following command:

```
qpdf input.pdf --recompress-flate --compression-level=9 --object-streams=generate output.pdf
```

I would like to know if I can get the same effect with pikepdf.

**Comment by jbarlow83** [comment]
```python

pikepdf._qpdf.set_flate_compression_level(9)

with pikepdf.Pdf.open('input.pdf') as pdf:
    pdf.save('output.pdf', recompress_flate=True, object_stream_mode=pikepdf.ObjectStreamMode.generate)
```

**Comment by nefyodovve** [comment]
Thank you.

> ```python
> pikepdf._qpdf.set_flate_compression_level(9)
> ```

Is it safe for using? Warning for protected member and no documentation found.

**Comment by jbarlow83** [comment]
I exposed and documented it in `pikepdf.settings.set_flate_compression_level(9)`.
