### ISSUE TITLE
How to reduce images size in a PDF file

### ISSUE THREAD

**Issue by taicaile** [pikepdf/pikepdf#319]
Hello,

I am trying to reduce images size in a PDF file, and I have tried to rewrite the image without any changes as the code shown below:

```python
for img_key in page.images:
  rawimage = page.images[img_key]
  pdfimage = PdfImage(rawimage)
  pillowimage = pdfimage.as_pil_image()
  with io.BytesIO() as output:
      pillowimage.save(output, format="jpeg",compression='jpeg')
      rawimage.write(output.getvalue(), filter=Name("/DCTDecode"))
```

However, the new PDF file size is increased, I don't understand why this happened. Does anyone know the reason?

**Comment by jbarlow83** [comment]
If you do `rawimage.write(b'')` is the output PDF still larger?

Have a look at the `ocrmypdf.optimize` for a module that reduces image sizes in PDF using pikepdf. You can suppress ocrmypdf's OCR if you just want an optimizer.

**Comment by taicaile** [comment]
> If you do `rawimage.write(b'')` is the output PDF still larger?
> 
> Have a look at the `ocrmypdf.optimize` for a module that reduces image sizes in PDF using pikepdf. You can suppress ocrmypdf's OCR if you just want an optimizer.

Hello, I have tried to do `rawimage.write(b'')`, and the pdf size is reduced as expected.

The `ocrmypdf` works, thank you.

**Comment by taicaile** [comment]
> If you do `rawimage.write(b'')` is the output PDF still larger?
> 
> Have a look at the `ocrmypdf.optimize` for a module that reduces image sizes in PDF using pikepdf. You can suppress ocrmypdf's OCR if you just want an optimizer.

Hello, I have tried to do `rawimage.write(b'')`, and the pdf size is reduced as expected.

The `ocrmypdf` works, thank you.
