### ISSUE TITLE
[Feature Request] Page Screenshot

### ISSUE THREAD

**Issue by bratao** [pikepdf/pikepdf#32]
First of all, thank you for this super polished lib.

I want to request a feature. Would be nice to be able to convert a page to image.

**Comment by jbarlow83** [comment]
You can do this in a Jupyter notebook or IPython

```
pdf.pages[0]
```

Clearly this should be better documented....

It also needs `mupdf` installed, currently.

Although there's no API to do page to image. Perhaps it's worth mentioning that this feature will always depend on an external backend.

**Comment by jbarlow83** [comment]
@bratao Do you mind if I quote you as saying the following on a testimonial page?

>  "Thank you for this super polished library." – Github user bratao

**Comment by bratao** [comment]
Of course not, feel free to use it 🙂

**Comment by impredicative** [comment]
I think quoting it is a bad idea while this package continues to rely on pybind11 which has issues.

**Comment by jbarlow83** [comment]
@impredicative This is where I remind you that this is free software for which you have also received free technical support. Backhanded complaining about an issue for which I provided two different workarounds pending a proper third party solution is not a constructive contribution and does not motivate me to do additional work for your benefit.

**Comment by impredicative** [comment]
@jbarlow83 I think pikepdf can be great, and bratao's compliment can be useful and marketable, but pikepdf is not quite there yet. Of course I want it to be great. It's better that you receive an honest appraisement from me than from a paying user who will be unforgiving.

Also, you aren't the only open source developer that exists. You too rely on free software, and I doubt you paid pybind11 anything. I don't need you to do any work for free for my benefit, so long as you do it for pikepdf's benefit. For the record, I am certainly not monetizing pikepdf in any way.

What workaround are you referring to? On Feb 20, you suggested the use of a ProcessPoolExecutor, but I was [already using that as of a day ago on Feb 19](https://github.com/impredicative/urltitle/blame/master/urltitle/util/pikepdf.py). In fact, your noted workaround was incomplete, as I had to figure out on my own that I can never import pikepdf even once in the parent process.

Feel free to block me if you don't like hearing the truth.

**Comment by jbarlow83** [comment]
@impredicative I encourage you to make constructive contributions in the future. Your first paragraph is an example of a constructive contribution.

>What workaround are you referring to? On Feb 20, you suggested the use of a ProcessPoolExecutor, but I was already using that as of a day ago on Feb 19. In fact, your noted workaround was incomplete, as I had to figure out on my own that I can never import pikepdf even once in the parent process.

This is not a constructive contribution. In reminding you this is free software, I am reminding you that there are practical limitations on the kind of support I can provide. You might have to figure out some things on your own. The other workaround was to patch pybind11.

As this is now offtopic I am hiding all of these comments.
