### ISSUE TITLE
read large pdf

### ISSUE THREAD

**Issue by KaHuier** [pikepdf/pikepdf#326]
I now encounter a very large pdf, about 4-5G, I use pikepdf to read very slowly, is there any solution?

 with pikepdf.open(pdf_file) as pdf:
            all_page = list(pdf.pages)

**Comment by jbarlow83** [comment]
There isn't much point to making a list of all pages like that. If you use the .pages accessor pages will be loaded on demand more efficiently. 

If you can demonstrate pikepdf is pathologically slow (that is, time increases worse than linearly with file size) that would be something to look into.
