### ISSUE TITLE
 object_stream_mode=pikepdf.ObjectStreamMode.disable does not work

### ISSUE THREAD

**Issue by pfrederiksen40** [pikepdf/pikepdf#33]
I run this to save file:
pdf.save("DECOMPRESSED mytest.pdf", object_stream_mode=pikepdf.ObjectStreamMode.disable, qdf=True)
but still get object streams like this:
4 0 obj
<<
  /Type /ObjStm
  /Length 4108
  /N 9
  /First 121
>>
stream
5 0
6 235
7 322
8 409
9 776
10 1588
11 1950
12 2828
13 3196
%% Object stream: object 5, index 0; original object ID: 238
<< .........

There doesn't seem to be difference between .preserve and .disable

Thanks

**Comment by jbarlow83** [comment]
The default parameter `fix_metadata_version=True` prevent object streams from being set somehow; if  `fix_metadata_version=False` object streams are generated correctly. I just mention this in case you need an immediate workaround.

Fixed for next release.
