### ISSUE TITLE
Saving with embedded JavaScript

### ISSUE THREAD

**Issue by janvarsa** [pikepdf/pikepdf#332]
If I open the file linked below and then save it, the embedded JavaScript is missing (the file size decreases from 578kb to 406kb). 

`from pikepdf import Pdf`
`pdf = Pdf.open('imm5708e.pdf')`
`pdf.save('new_file.pdf')`

The original pdf file: 
https://www.canada.ca/content/dam/ircc/migration/ircc/english/pdf/kits/forms/imm5708e.pdf

How can I save the file without interfering with the JavaScript functionality?

**Comment by jbarlow83** [comment]
I believe this is a qpdf issue so I reported it there.

**Comment by jbarlow83** [comment]
@janvarsa Please read the comments on qpdf/qpdf#702 and see if you have any feedback. If not, we will close the issue, because everything seems to be explicable as far as we can tell.

**Comment by janvarsa** [comment]
Thanks - added a response to [qpdf#702](https://github.com/qpdf/qpdf/issues/702)
The Validate button loses its ability to autogenerate a page of barcodes after saving with qpdf or pikepdf.
