### ISSUE TITLE
Tests fail for AArch64

### ISSUE THREAD

**Issue by odidev** [pikepdf/pikepdf#333]
Hi Team,

I tried testing pikepdf package on aarch64, it shows the below error:
`ImportError: pikepdf's extension library failed to import`. Also, I explored regarding the error, I have gone through the [pypi](https://pypi.org/project/emcache/#files) of pikepdf, but wheels are not present for pikepdf. 

@[jbarlow83](https://github.com/jbarlow83) Could you please share your feedback regarding this and suggest what could be done to test this over ARM64 server?

**Logs for your reference**: [test_pikepdf_arm86_with_py38(success).txt.txt](https://github.com/pikepdf/pikepdf/files/8538326/test_pikepdf_arm86_with_py38.success.txt.txt)

Thanks in advance.

**Comment by mara004** [comment]
This note from the [installation docs](https://pikepdf.readthedocs.io/en/stable/installation.html#building-from-source) sounds related:
> pikepdf should be built with the same compiler and linker as libqpdf; to be precise both must use the same C++ ABI. On some platforms, setup.py may not pick the correct compiler so one may need to set environment variables CC and CXX to redirect it. If the wrong compiler is selected, import pikepdf._qpdf will throw an ImportError about a missing symbol.

**Comment by jbarlow83** [comment]
aarch64 implied for v5.3.0 using a self-hosted ARM
