### ISSUE TITLE
(Jupyter) Feature Request: Stop it with the link and actually implement an actual IFrame for it

### ISSUE THREAD

**Issue by Xyndra** [pikepdf/pikepdf#334]
I am trying to view a PDF and the only thing I get is a download link, it would be very nice if it would just be shown on the jupyter webpage.

**Comment by Xyndra** [comment]
For everyone else, here is a workaround to show it, however you always need to call the `save_show()` function:
![image](https://user-images.githubusercontent.com/71836523/165356125-fe3eb03f-f986-45e3-8e80-e946895f6c97.png)
<details>
    <summary>Source</summary>
```python
from pikepdf import Pdf
from IPython.display import IFrame
pdf = Pdf.new()
def save_show():
    pdf.save("test.pdf")
    return IFrame("./test.pdf", width=650, height=950)
pdf.pages
pdf.add_blank_page(page_size=(595, 842))
pdf.add_blank_page(page_size=(595, 842))
save_show()
```
</details>

**Comment by jbarlow83** [comment]
Thanks for this - what I implemented with the link was the best option several years ago when I set it up, but it looks IPython now has better options. I'll make this behavior the default.

Note to self: looks like this should be done with `_ipython_display_` instead of `_repr_*`
