### ISSUE TITLE
unable to find trailer dictionary while recovering damaged file

### ISSUE THREAD

**Issue by pocupine** [pikepdf/pikepdf#335]
First, I want to say thank you that Pikepdf helps to convert encrypted PDF files which cannot be done by Pypdf2.  Pypdf2 popped up read error but Pikepdf didn't. I had a weird problem. when I code normally on a flask website:

```
if request.form['submit_button'] == 'rotate':
    filePath = request.files['file4']
    if filePath.filename == '':
        flash('Please choose a file first.',category='warning')
    elif filePath.seek(0,2)/(1024*1024) > 2:    #get the file size in MB
        flash('The file size must be below 2MB.', category='warning')
    else:
        bio=BytesIO(filePath.stream.read())
        my_pdf = pikepdf.open(bio)
        my_pdf.pages[0].Rotate = 90
        my_pdf.save('csu.pdf')

```
the app stopped on an error:pikepdf._qpdf.PdfError: <_io.BytesIO object at 0x000000D00D19E5C0>: unable to find trailer dictionary while recovering damaged file.

But if I rotate it directly without checking, it convert normally.
```
if request.form['submit_button'] == 'rotate':
    filePath = request.files['file4']
    bio=BytesIO(filePath.stream.read())
    my_pdf = pikepdf.open(bio)
    my_pdf.pages[0].Rotate = 90
    my_pdf.save('csu.pdf')

```
Please shine some light on this. Thanks.

**Comment by jbarlow83** [comment]
You have to seek back to the beginning of the file before reading from it again.

**Comment by pocupine** [comment]
Hi,
Thanks for the quick response. I am not familiar with the stream. How can I seek back? Thanks.

**Comment by pocupine** [comment]
I found it. filePath.seek(0, 0)
Thanks for the help. :)
