### ISSUE TITLE
[Feature Request] - document object parsing

### ISSUE THREAD

**Issue by pfrederiksen40** [pikepdf/pikepdf#34]
Hi
Parsing a PDF in QDF mode is relatively easy because it's all text e.g. it's easy to identify that this is a data table cell:

112 0 obj
<< /K 72 0 R /P 60 0 R /S /TD
 /A 147 0 R>>
endobj

and it's straigtforward to change it to a /TH or to find the /A object to add a /Headers attribute.
My question is: is it possible to do this using pikePDF? could you please provide a code example in the documentation?
Thank you very much!

**Comment by jbarlow83** [comment]
In case you're not aware that sort of logical structure does not always appear in all PDFs; it only appears in explicitly tagged PDFs.

In any event, if you already know the object ID

```python
cell = pdf.get_object((112, 0)) 
cell.S = pikepdf.Name.TH
a_object = cell.A
```

Note `qpdf --qdf` changes the object IDs.

You can find the tagged PDF structure information somewhere (recursively searching) in the root object of the PDF. You'd then have to recursively search this object tree for objects that interest you. 

```python
struct_tree = pdf.root.StructTreeRoot
```

See here for an example of parsing the table of contents object tree to fix bookmark entries after combining PDFs:

https://github.com/jbarlow83/OCRmyPDF/blob/210f134b5baea09ec16698ca80acc7982f0a9744/src/ocrmypdf/_weave.py#L231

**Comment by pfrederiksen40** [comment]
Thanks heaps! that works and is much safer than editing the qdf text version.
I managed to parse the PDF and also extract MCID referenced text from the streams.

But I still struggle with assigning values to existing objects - e.g

ob.ID = pikepdf.String("somestring")
becomes:
/ID <feff006100720032>

and same happens when using the ".make_indirect" method. How can I make an existing python dictionary (not string) into a new object? e.g. how make  {"/O":"/Table","/Headers":["a", "b"]} into a new object?

**Comment by jbarlow83** [comment]
It looks like there could be a bug with using `setattr` to create a new value on an object...

You can use item notation too to reference values on existing objects: `obj["/ID"]`.

You can construct a new dictionary by explicitly creating a PDF dictionary

```python
pikepdf.Dictionary(
    O=pikepdf.Name.Table,
    Headers=["a", "b"]
)
```

or if you just use a Python dictionary pikepdf should attempt conversion. For `make_indirect`

```python
obj["/SubObject"] = pdf.make_indirect({"/O": pikepdf.Name("/Table"), "/Headers": ["a", "b"]})
```

You do need to use `Name()` whenever a /Name is a value, since this ensures the name is properly encoded in the PDF. Otherwise the PDF will be populated with the value `/O (/Table)` for example, the which is the literal string "/Table" not a PDF name object.

**Comment by pfrederiksen40** [comment]
hi - I tried the above for creating a new object but it give this:
130 0 obj
&lt;&lt;
  /Headers [
    &lt;feff006100720031&gt;
    &lt;feff006100720034&gt;
    &lt;feff006100630034&gt;
    &lt;feff005a0055&gt;
  ]
  /O /Table
&gt;&gt;
endobj

**Comment by jbarlow83** [comment]
That's just UTF16-BE encoded with a leading byte order mark (`feff`), so `0061` is U+0061 or `a`.

Although I thought libqpdf would automatically switch to ASCII (strictly speaking, PdfDocEncoding) when such a representation existed and fallback to UTF-16... that I will have to look at, but there's nothing wrong what it currently does, it just's a little nicer to see readable text when possible.

If you require a bytes string you can encode as ASCII.

**Comment by pfrederiksen40** [comment]
ah, ok, I'll try that
this is by the way the same as happened with the ID in my previous question - it displays as &lt;etc. in the PDF
but it didn't display in the post because I typed the greater than rather than using a character code

**Comment by pfrederiksen40** [comment]
Hi jbarlow
It's all working now: extracting structure and content from PDF, manipulating it in a different interface and then saving back to PDF.
Thanks heaps for your help and for making this super excellent library!!!!!!!

**Comment by pfrederiksen40** [comment]
I do have another question - For the TJ command, print(str(operands)) gives:

[pikepdf.Array([ "Magistr", Decimal('20.3'), "ates Cour", Decimal('-40.1'), "ts " ])]    OR sometimes

[pikepdf.Array([ "\000,\000S\000F\000E\000V", Decimal('-19.5'), "\00....

How do I convert the "\000..." codes into text? they show as readable text in the QDF file
thank you!

**Comment by pfrederiksen40** [comment]
OK - looks like /ToUnicode provides the translation...

**Comment by jbarlow83** [comment]
If /ToUnicode exists, it provides the mapping, but some caveats apply, like if the PDF doesn't use Unicode. Read the PDF 1.7 reference manual if you want to see how complex this gets.

I recommend pdfminer.six if you want to extract text – it takes a whole Python project that's a few times the size of pikepdf, just to extract text reliably. (pdfminer on the other hand is read-only; it cannot edit or write PDFs.)

**Comment by pfrederiksen40** [comment]
Wow - OK. Luckily I don't need to edit the text, only to roughly extract it. Can a PDF be saved in Unicode format from Acrobat?

**Comment by jbarlow83** [comment]
I think Acrobat can save to a text file.

pdfminer has a command line tool to extract text from PDFs. So does poppler's `pdftotext -enc utf-8`.  I have example files that are technically valid PDFs that break both; but being a PDF developer I tend to see more than my share of pathological files. For most cases either program should be fine and I trust pdftotext a bit more.

**Comment by pfrederiksen40** [comment]
I need the text in the context of the tagging e.g. know that text is inside a TH or a P and then edit the tagging (not the text), so pikepdf is the tool to use!.

You mention that /ToUnicode only exists if the PDF is using Unicode, so I was wondering if a PDF can be forced to use Unicode (e.g. by saving from Acrobat in some specific way). If this forces the creation of the /ToUnicode mapping objects then it would always be possible to get the correct (or close to) text.

**Comment by jbarlow83** [comment]
You can't force /ToUnicode to be created, because it's possible to define an arbitrary symbolic font with no Unicode mapping at all. Because of that you can't force it to be created either.

If there is a /ToUnicode mapping you can count on the text being convertible to Unicode. There's also an in-between case, where a font can specify some that it is in some other encoding which is convertible to Unicode.

**Comment by pfrederiksen40** [comment]
Thanks for the info - most of the PDFs that I'll be working with should have /ToUnicode when needed. For other PDFs I can refer to the original PDF in parallel with the extracted version.

And thanks for the tip about object streams - that did the trick :)

**Comment by pfrederiksen40** [comment]
By the way - is is possible to delete a key in a pikepdf dictionary?

I currently do it by copying all key/value pairs (except the one to delete) to a new dictionary and then overwrite the original dictionary.

**Comment by pfrederiksen40** [comment]
ah - ok, just use "del"

**Comment by jbarlow83** [comment]
I'll close the issue now. If you have further related questions feel free to reopen it.
