### ISSUE TITLE
how to remove watermarks ?? 

### ISSUE THREAD

**Issue by Ling1992** [pikepdf/pikepdf#340]
need an example of remove watermark

**Comment by jbarlow83** [comment]
In the general case this isn't possible. PDF does not contain semantic markup. It is a lot age description format, and contains a description of how a page should look when printed to a printer or screen. The drawing commands look like "draw text here", "draw line here".

(Apart from accessibility markup, which is rare.)

If the watermark has characteristics you can isolate, then you may be able to remove it, but the procedure to remove it would vary.

**Comment by Ling1992** [comment]
Acrobat Dc can do it , but it's not convenient.



> In the general case this isn't possible. PDF does not contain semantic markup. It is a lot age description format, and contains a description of how a page should look when printed to a printer or screen. The drawing commands look like "draw text here", "draw line here".
> 
> (Apart from accessibility markup, which is rare.)
> 
> If the watermark has characteristics you can isolate, then you may be able to remove it, but the procedure to remove it would vary.

Acrobat Dc can do it , but it's not convenient.
