### ISSUE TITLE
AWS Lambda Problem

### ISSUE THREAD

**Issue by lbrent2k** [pikepdf/pikepdf#342]
I am not able to get dependencies installed on an AWS Lambda function.

I get this error:

pikepdf's extension library failed to import

Any guidance on how to get pikepdf installed on Lambda?

**Comment by jbarlow83** [comment]
You're likely missing required libraries. Try:

https://aws.amazon.com/premiumsupport/knowledge-center/lambda-python-package-compatible/

I believe there are third party packages of ocrmypdf for AWS Lambda which would include the necessary packages.

**Comment by jbarlow83** [comment]
Here's the OCRmyPDF for AWS Lambda package, which is out of date but does demonstrate how to package pikepdf for Lambda.
https://github.com/chronograph-pe/lambda-OCRmyPDF
