### ISSUE TITLE
pikepdf doesn't see some bitmap images

### ISSUE THREAD

**Issue by SF73** [pikepdf/pikepdf#344]
Hi, I have a pdf with many images inside but pikepdf does not see any of them

Here the link to the pdf : https://iopscience.iop.org/article/10.1088/1361-6463/aba64c/pdf
Note that this is different from #301 as the pdf contains bitmap images.

mwe
```py
import pikepdf
from pikepdf import Pdf

print(pikepdf.__libqpdf_version__)
print(pikepdf.__version__)

c = 0
with Pdf.open("file.pdf") as pdf:
    for page in pdf.pages:
        images = list(page.images.keys())
        c += len(images)
print(f"{c} images found")

```
Ouput : 
```
10.6.3
5.1.2
0 images found
```

**Comment by mara004** [comment]
When I do `[page.images for page in pdf.pages]` on the referenced PDF, I get a list of 58 images, i. e. I can't reproduce the issue. My pikepdf version is `5.1.3`.

**Comment by jbarlow83** [comment]
The images in question are embedded inside Form XObjects. e.g. page 1 has object Xi0, which contains the image and a font as resources.

qpdf (our dependent library) does not seem to search inside Form XObjects for images. You can explore `Page.resources` to locate form xobjects, then explore them to find any images. If you call `pikepdf.PdfImage()` on an image object in the PDF, e.g. `pdfim = pikepdf.PdfImage(p.pages[0].Resources.XObject['/Xi0'].Resources.XObject['/img0']) you can still access the full image API.

Another method is to iterate though `pdf.objects` and look for objects with `.Type == Name.XObject` and `.Subtype == Name.Image`
