### ISSUE TITLE
runtime error: LZWDecoder: table full

### ISSUE THREAD

**Issue by william0353** [pikepdf/pikepdf#345]
Hi I was trying to merge around 11 pdf to one and got this error.
For some cases it works without any problem

Full notes: 
 File "c:\Users\*\combiner.py", line 65, in merge_pike
    pdf.save(final_name)
  File "C:\Users\*\pikepdf\_methods.py", line 774, in save
    self._save(
RuntimeError: LZWDecoder: table full

**Comment by jbarlow83** [comment]
It won't be possible to investigate this without example files and the version of pikepdf used.
