### ISSUE TITLE
pip/pypi lists 5.1.3 as latest when it builds from source

### ISSUE THREAD

**Issue by aptalca** [pikepdf/pikepdf#351]
This may be an issue with pypi, not sure. But I'm hoping you can point me in the right direction.

5.1.4 was released about 7 hours ago. When I check with pip on a platform where prebuilt wheels are available (such as ubuntu jammy x86_64), it correctly shows 5.1.4 as the latest release and installs using the wheel.

However, if I check the latest or try to install on a platform where there are no prebuilt wheels, and it has to build from source (any arm32/64 distro, or alpine/musl), pip shows 5.1.3 as the latest.

Any ideas what might be causing this?

Here are some basic tests (reproducible with docker):
- Ubuntu jammy x86_64, 5.14 _is_ listed:
  - command: `docker run --rm ghcr.io/linuxserver/baseimage-ubuntu:jammy /bin/bash -c 'apt-get update && apt-get install -y python3-pip && pip3 install -U pip && pip install pikepdf=='`
  - log snippet:
```
ERROR: Ignored the following versions that require a different python version: 1.19.4 Requires-Python >=3.5, <3.9
ERROR: Could not find a version that satisfies the requirement pikepdf== (from versions: 0.1rc1, 0.1rc3, 0.1rc4, 0.1rc5, 0.1.0.post1, 0.1.1, 0.1.2, 0.1.3, 0.1.4, 0.1.5, 0.1.6, 0.1.7, 0.1.8, 0.1.9, 0.1.10rc1, 0.1.10, 0.2.0, 0.2.1, 0.2.2, 0.3.0, 0.3.1, 0.3.2, 0.3.3, 0.3.4, 0.3.5, 0.3.6, 0.3.7, 0.3.7.post1, 0.3.7.post2, 0.9.0, 0.9.1, 0.9.2, 0.10.0, 0.10.1, 0.10.2, 1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.1.0, 1.2.0, 1.3.0, 1.3.1, 1.4.0, 1.5.0.post0, 1.6.0, 1.6.1, 1.6.2, 1.6.3, 1.6.4, 1.6.5, 1.7.0, 1.7.1, 1.8.0, 1.8.1, 1.8.2, 1.8.3, 1.9.0, 1.10.0, 1.10.1, 1.10.2, 1.10.3, 1.10.4, 1.11.0, 1.11.1, 1.11.2, 1.12.0, 1.13.0, 1.14.0, 1.15.0, 1.15.1, 1.16.0, 1.16.1, 1.17.0, 1.17.1, 1.17.2, 1.17.3, 1.18.0, 1.19.0, 1.19.1, 1.19.2, 1.19.3, 2.0.0b1, 2.0.0b2, 2.0.0, 2.1.0, 2.1.1, 2.1.2, 2.2.0, 2.2.1, 2.2.2, 2.2.3, 2.2.4, 2.2.5, 2.3.0, 2.4.0, 2.5.0, 2.5.1, 2.5.2, 2.6.0, 2.7.0, 2.8.0, 2.8.0.post1, 2.8.0.post2, 2.9.0, 2.9.1, 2.9.2, 2.10.0, 2.11.0, 2.11.1, 2.11.2, 2.11.3, 2.11.4, 2.12.0, 2.12.1, 2.12.2, 2.13.0, 2.14.0, 2.14.1, 2.14.2, 2.15.0, 2.15.1, 2.16.0, 2.16.1, 3.0.0b1, 3.0.0b2, 3.0.0b3, 3.0.0, 3.1.0, 3.1.1, 3.2.0, 4.0.0, 4.0.1, 4.0.1.post1, 4.0.2, 4.1.0, 4.2.0, 4.3.0, 4.3.1, 4.4.0, 4.4.1, 4.5.0, 5.0.0, 5.0.1, 5.1.0, 5.1.1, 5.1.2, 5.1.3, 5.1.4)
ERROR: No matching distribution found for pikepdf==
```

- Alpine 3.16 x86_64, 5.1.4 is _not_ listed:
  - command: `docker run --rm alpine:3.16 sh -c 'apk add --no-cache py3-pip && pip3 install -U pip && pip install pikepdf=='`
  - log snippet:
```
ERROR: Ignored the following versions that require a different python version: 1.19.4 Requires-Python >=3.5, <3.9
ERROR: Could not find a version that satisfies the requirement pikepdf== (from versions: 0.1rc1, 0.1rc3, 0.1rc4, 0.1rc5, 0.1.0.post1, 0.1.1, 0.1.2, 0.1.3, 0.1.4, 0.1.5, 0.1.6, 0.1.7, 0.1.8, 0.1.9, 0.1.10rc1, 0.1.10, 0.2.0, 0.2.1, 0.2.2, 0.3.0, 0.3.1, 0.3.2, 0.3.3, 0.3.4, 0.3.5, 0.3.6, 0.3.7, 0.3.7.post1, 0.3.7.post2, 0.9.0, 0.9.1, 0.9.2, 0.10.0, 0.10.1, 0.10.2, 1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.1.0, 1.2.0, 1.3.0, 1.3.1, 1.4.0, 1.5.0.post0, 1.6.0, 1.6.1, 1.6.2, 1.6.3, 1.6.4, 1.6.5, 1.7.0, 1.7.1, 1.8.0, 1.8.1, 1.8.2, 1.8.3, 1.9.0, 1.10.0, 1.10.1, 1.10.2, 1.10.3, 1.10.4, 1.11.0, 1.11.1, 1.11.2, 1.12.0, 1.13.0, 1.14.0, 1.15.0, 1.15.1, 1.16.0, 1.16.1, 1.17.0, 1.17.1, 1.17.2, 1.17.3, 1.18.0, 1.19.0, 1.19.1, 1.19.2, 1.19.3, 2.0.0b1, 2.0.0b2, 2.0.0, 2.1.0, 2.1.1, 2.1.2, 2.2.0, 2.2.1, 2.2.2, 2.2.3, 2.2.4, 2.2.5, 2.3.0, 2.4.0, 2.5.0, 2.5.1, 2.5.2, 2.6.0, 2.7.0, 2.8.0, 2.8.0.post1, 2.8.0.post2, 2.9.0, 2.9.1, 2.9.2, 2.10.0, 2.11.0, 2.11.1, 2.11.2, 2.11.3, 2.11.4, 2.12.0, 2.12.1, 2.12.2, 2.13.0, 2.14.0, 2.14.1, 2.14.2, 2.15.0, 2.15.1, 2.16.0, 2.16.1, 3.0.0b1, 3.0.0b2, 3.0.0b3, 3.0.0, 3.1.0, 3.1.1, 3.2.0, 4.0.0, 4.0.1, 4.0.1.post1, 4.0.2, 4.1.0, 4.2.0, 4.3.0, 4.3.1, 4.4.0, 4.4.1, 4.5.0, 5.0.0, 5.0.1, 5.1.0, 5.1.1, 5.1.2, 5.1.3)
ERROR: No matching distribution found for pikepdf==
```

- Ubuntu jammy aarch64, 5.1.4 is _not_ listed (requires qemu multiarch support if running on x86_64 hw, can be enabled via first running `docker run --rm --privileged multiarch/qemu-user-static --reset -p yes`)
  - command: `docker run --rm ghcr.io/linuxserver/baseimage-ubuntu:arm64v8-jammy /bin/bash -c 'apt-get update && apt-get install -y python3-pip && pip3 install -U pip && pip install pikepdf=='`
  - log snippet:
```
ERROR: Ignored the following versions that require a different python version: 1.19.4 Requires-Python >=3.5, <3.9
ERROR: Could not find a version that satisfies the requirement pikepdf== (from versions: 0.1rc1, 0.1rc3, 0.1rc4, 0.1rc5, 0.1.0.post1, 0.1.1, 0.1.2, 0.1.3, 0.1.4, 0.1.5, 0.1.6, 0.1.7, 0.1.8, 0.1.9, 0.1.10rc1, 0.1.10, 0.2.0, 0.2.1, 0.2.2, 0.3.0, 0.3.1, 0.3.2, 0.3.3, 0.3.4, 0.3.5, 0.3.6, 0.3.7, 0.3.7.post1, 0.3.7.post2, 0.9.0, 0.9.1, 0.9.2, 0.10.0, 0.10.1, 0.10.2, 1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.1.0, 1.2.0, 1.3.0, 1.3.1, 1.4.0, 1.5.0.post0, 1.6.0, 1.6.1, 1.6.2, 1.6.3, 1.6.4, 1.6.5, 1.7.0, 1.7.1, 1.8.0, 1.8.1, 1.8.2, 1.8.3, 1.9.0, 1.10.0, 1.10.1, 1.10.2, 1.10.3, 1.10.4, 1.11.0, 1.11.1, 1.11.2, 1.12.0, 1.13.0, 1.14.0, 1.15.0, 1.15.1, 1.16.0, 1.16.1, 1.17.0, 1.17.1, 1.17.2, 1.17.3, 1.18.0, 1.19.0, 1.19.1, 1.19.2, 1.19.3, 2.0.0b1, 2.0.0b2, 2.0.0, 2.1.0, 2.1.1, 2.1.2, 2.2.0, 2.2.1, 2.2.2, 2.2.3, 2.2.4, 2.2.5, 2.3.0, 2.4.0, 2.5.0, 2.5.1, 2.5.2, 2.6.0, 2.7.0, 2.8.0, 2.8.0.post1, 2.8.0.post2, 2.9.0, 2.9.1, 2.9.2, 2.10.0, 2.11.0, 2.11.1, 2.11.2, 2.11.3, 2.11.4, 2.12.0, 2.12.1, 2.12.2, 2.13.0, 2.14.0, 2.14.1, 2.14.2, 2.15.0, 2.15.1, 2.16.0, 2.16.1, 3.0.0b1, 3.0.0b2, 3.0.0b3, 3.0.0, 3.1.0, 3.1.1, 3.2.0, 4.0.0, 4.0.1, 4.0.1.post1, 4.0.2, 4.1.0, 4.2.0, 4.3.0, 4.3.1, 4.4.0, 4.4.1, 4.5.0, 5.0.0, 5.0.1, 5.1.0, 5.1.1, 5.1.2, 5.1.3)
ERROR: No matching distribution found for pikepdf==
```

PS. I'm using `pip install pikepdf==` to get pip to list all available versions in a somewhat hacky way

Thanks

**Comment by jbarlow83** [comment]
The sdist is on PyPi. 

https://pypi.org/project/pikepdf/#files

As you say that is a hack to check version availability. Seems like a pip issue. 

pip has some option to tell it to not use binary wheels at all. That may help it here.

**Comment by jbarlow83** [comment]
I think you've found a bug in pip and/or pypi. pip should select the sdist if there is no matching binary wheel. We know that the right sdist is uploaded. If it's a picking the wrong version that needs resolution on their end.

You could try feeding the correct file to pip to see what it does: `pip install https://files.pythonhosted.org/packages/c0/70/ae564e26cf53c7980c7b64e647628ce417262a42434b8fc5f25231550e80/pikepdf-5.1.4.tar.gz`

**Comment by aptalca** [comment]
Thanks for the confirmation. I went ahead and opened an issue in their repo: https://github.com/pypa/pip/issues/11174

Unfortunately manually defining the tarball is not going to work for us as we're trying to maintain our wheel builder that pushes wheels to [our wheel repo](https://wheel-index.linuxserver.io/) for use in our docker images so the whole thing is ci based: https://github.com/linuxserver/wheelie

**Comment by aptalca** [comment]
@jbarlow83 they kicked it back to you 😅
https://github.com/pypa/pip/issues/11174#issuecomment-1151579923

**Comment by jbarlow83** [comment]
☔

So pip says means PyPI is reporting its state inconsistently. That is not something I can fix.

In other words, it appears to be this unresolved issue in warehouse:
https://github.com/pypa/warehouse/issues/10390

I pushed a .post1 release, just for you.

**Comment by aptalca** [comment]
SUCCESS: https://github.com/linuxserver/wheelie/commit/ba6be50db39f8127cc513231342c122869adf62e

Thanks so much
