### ISSUE TITLE
ImportError when build executable file with pyinstaller

### ISSUE THREAD

**Issue by wzdlc1996** [pikepdf/pikepdf#353]
System version: windows10 64 bit
pikepdf version: 5.1.5
pyinstaller version: 5.1
Python version: 3.8.3

The error occurred when I want to build an executable file with pyinstaller on windows machine. The minimal test can be implemented by the following way:

```python3
# test.py
import pikepdf

_ = pikepdf.open
print("hello")
```

With `pyinstaller -cF test.py` one obtain a single file `test.exe`. Then run it post the following exception:

```
Traceback (most recent call last):
  File "pikepdf\__init__.py", line 19, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "pikepdf\_version.py", line 13, in <module>
  File "importlib\metadata.py", line 531, in version
  File "importlib\metadata.py", line 504, in distribution
  File "importlib\metadata.py", line 177, in from_name
importlib.metadata.PackageNotFoundError: pikepdf

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "test.py", line 1, in <module>
    import pikepdf
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "pikepdf\__init__.py", line 21, in <module>
ImportError: Failed to determine version
```

The gui app also got this issue with the same traceback. I can reproduce it and offer the screenshot if necessary.

It seems the issue is caused by the fix in #201 but I am not sure. By downgrade the pikepdf to 3.1.0 this issue gets resolved.

**Comment by jbarlow83** [comment]
I recently changed from using pkg_resources (deprecated) to importlib.metadata for obtaining package information. Does PyInstaller support this change or require any changes to work with it? (I wouldn't know.)

If that does not explain the issue, do you mean pikepdf 5.1.0 or 3.1.0 worked? You said 3.1.0 worked, but I wanted to check if it was more recently. Would you be able to bisect to the exact commit?

**Comment by wzdlc1996** [comment]
> Does PyInstaller support this change or require any changes to work with it?

I need to make some more searches on this. I do not find related issues in pyinstaller docs.

> do you mean pikepdf 5.1.0 or 3.1.0 worked?

I checked recent releases and find this issue appears at pikepdf==5.1.4 and pikepdf==5.1.5. pikepdf==5.1.3 works fine.
