### ISSUE TITLE
Bug in version 1.1.0 with Anaconda

### ISSUE THREAD

**Issue by ghaddarAbs** [pikepdf/pikepdf#36]
Hi,

Since the library has been upgraded to 1.1.0 this bug pop-up and cause a python crash with Anaconda enviroment. 
```
pdf = pikepdf.open("/path/to/file.pdf")
pdf.save("/another/path/to/file.pdf")

could not create 'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\sqlalchemy\\engine\\__pycache__\\reflection.cpython-37.pyc': PermissionError(13, 'Access denied')
```
However, the library works perfectly up to version 1.0.5

Thanks

**Comment by jbarlow83** [comment]
It looks like that has to do with how Anaconda manages its .pyc files or a Windows user permission problem. Upgrading to pikepdf may have updated something else which triggered the problem.

Maybe this issue:
https://github.com/conda/conda/issues/4534

**Comment by ghaddarAbs** [comment]
I doubt because the package was installed via `pip install pikepdf` not conda .... I don't know the bug seem also weird for me too ... however, we will stick with the 1.0.5 for now :)
