### ISSUE TITLE
Overlaying pages fails for all but the first page

### ISSUE THREAD

**Issue by TreeMage** [pikepdf/pikepdf#361]
Hey everyone :)

I have a use-case where I want to overlay some pages of a PDF with another PDF page. This is done by using the `Page.add_overlay` function as follows:
```
page_ids = [0, 1, 4]
final_pdf = Pdf.new()
with Pdf.open("main.pdf") as main_pdf:
  for page_id in page_ids:
    with Pdf.open(f"overlay_{page_id}.pdf") as overlay:
      page = overlay.pages[0]
      main_pdf_page = main_pdf.pages[page_id]
      main_pdf_page.add_overlay(page)
      final_pdf.pages.append(main_pdf_page)

final_pdf.save("final.pdf")
```
This worked flawlessly for a while. However, I recently stumbled over a PDF that will only have its overlay applied on the first page id specified in the `page_ids` and not on all following pages.
If I do not add the overlayed pages to a new PDF but save the old one it works as expected:
```
page_ids = [0, 1, 4]
with Pdf.open("main.pdf") as main_pdf:
  for page_id in page_ids:
    with Pdf.open(f"overlay_{page_id}.pdf") as overlay:
      page = overlay.pages[0]
      main_pdf_page = main_pdf.pages[page_id]
      main_pdf_page.add_overlay(page)
main_pdf.save("final.pdf")
```

If I use a version of the same PDF file that has all its text removed, both variants behave the same.
Is this the intended behavior?
(Sadly I can not share the PDF for privacy reasons)

**Comment by jbarlow83** [comment]
I wonder if perhaps this is a manifestation of the inline image parsing issue in #299. Could you try again with pikepdf 5.3.2?

**Comment by jbarlow83** [comment]
If that does not help, please consider GPG-encrypting the PDF against my public key so that only I can access it, so I can examine your file.

**Comment by jbarlow83** [comment]
stale
