### ISSUE TITLE
tranaslating position dimensions into Rectangle for add_overlay

### ISSUE THREAD

**Issue by jkotra** [pikepdf/pikepdf#362]
Hi,

I am trying to merge(overlay) multiple PDF files into a single page.I cant understand how `Rectangle` arg of `add_underlay` works.

I have a bunch of PDF files which contains news clippings. I have the following details about them WRT. a canvas of size (778w, 1200h) - `width, height, top_margin, left_margin, right_margin`

I created a blank page with `add_blank_page`, now how do i translate my margins and sizes to `Rectangle`?

Regards.

**Comment by jbarlow83** [comment]
From PDF 1.7 ref manual:

> Typically, the array takes the form
> [ llx lly urx ury ]
> specifying the lower-left x, lower-left y, upper-right x, and upper-right y coordinates of the rectangle, in that
> order. The other two corners of the rectangle are then assumed to have coordinates (llx, ury) and (urx, lly).

The units are in pts, so 1/72".

For example to draw a one-inch rectangle in the bottom left corner of the page you'd describe it as:

`pikepdf.Rectangle(0, 0, 72, 72)`

(Or equivalently, `Array([0, 0, 72, 72])`)

For a specific application you have to calculate the margins that work for you.
