### ISSUE TITLE
Missing dependency to "deprecation"?

### ISSUE THREAD

**Issue by dreua** [pikepdf/pikepdf#363]
It seems like there is a new dependency to the module "deprecation". I'm not sure about the details of pyproject.toml but it might be missing as a dependency here:

https://github.com/pikepdf/pikepdf/blob/170c5d3d6ad4212f404fba4562366b0a4e93b41b/pyproject.toml#L1-L8

**Comment by jbarlow83** [comment]
Only packages needed for building wheels or sdist have to be listed in pyproject.

Packages that will be imported get listed in setup.cfg for a setuptools project.

**Comment by dreua** [comment]
My flatpak build fails due to "deprecation":

```
Installed /app/lib/python3.9/site-packages/pikepdf-5.1.5-py3.9-linux-aarch64.egg
Processing dependencies for pikepdf==5.1.5
Searching for deprecation
Reading https://pypi.org/simple/deprecation/
Download error on https://pypi.org/simple/deprecation/: [Errno -3] Temporary failure in name resolution -- Some packages may not be found!
Couldn't find index page for 'deprecation' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.org/simple/
Download error on https://pypi.org/simple/: [Errno -3] Temporary failure in name resolution -- Some packages may not be found!
No local packages or working download links found for deprecation
error: Could not find suitable distribution for Requirement.parse('deprecation')
FB: host_command_exited_cb 998477 256
```
([full log](https://buildbot.flathub.org/#/builders/32/builds/98269))

Maybe it needs to be added as a runtime dependency at another place? Or do I need to fix it on my side?

**Comment by dreua** [comment]
I just saw that it's listed as an install requirement, so that must be an error on my side, sorry.

https://github.com/pikepdf/pikepdf/blob/c717d42bd8c02e13e406a27fb1c6b7c04f14c3ba/setup.cfg#L39-L45
