### ISSUE TITLE
Yet another "extract images but some are missing" issue

### ISSUE THREAD

**Issue by piegamesde** [pikepdf/pikepdf#366]
I tried extracting images from [this PDF](https://imslp.org/wiki/File:PMLP1970-Chopin_-_OP25_1_(etc).pdf), but it does not seem to find them.

The interesting thing though is that `pdfimages` (from poppler) extracts them just fine. Also interesting to me is that other files work just fine, even though they have very similar data (same image format; ccitt).

**Comment by piegamesde** [comment]
Here's a more direct link to the PDF, please try that: http://conquest.imslp.info/files/imglnks/usimg/6/60/IMSLP548375-PMLP1970-Chopin_-_OP25_1_(etc).pdf

I don't see how this is related to #299 since I'm merely extracting images and not building any new PDFs. Here's my code:

```python
from pikepdf import Pdf, PdfImage
from io import BytesIO

pdf = Pdf.open(BytesIO(bytes(pdf)))

images = []
for page in pdf.pages:
	for image in list(page.images.values()):
		buf = BytesIO(bytearray())
		format = PdfImage(image).extract_to(stream=buf)
		images += [(format[1:], buf.getvalue())]
```

**Comment by mara004** [comment]
Without having inspected the PDF, I think this might be the same problem as https://github.com/pikepdf/pikepdf/issues/344, considering that your code does not analyse possible XObjects.

**Comment by piegamesde** [comment]
As proposed in https://github.com/pikepdf/pikepdf/issues/344#issuecomment-1134137014, I modified my code to the following:

```python
for object in pdf.objects:
	if getattr(object, "Type", None) == "/XObject" and getattr(object, "Subtype", None) == "/Image":
		buf = BytesIO(bytearray())
		format = PdfImage(object).extract_to(stream=buf)
		images += [(format[1:], buf.getvalue())]
```

This works for the aforementioned PDF, however, I found a new PDF for which it does not work: https://imslp.org/wiki/File:PMLP05008-Saint-Sa%C3%ABns_-_Danse_Macabre,_Op._40_(trans._violin_and_piano).pdf https://s9.imslp.org/files/imglnks/usimg/3/34/IMSLP33277-PMLP05008-Saint-Sa%C3%ABns_-_Danse_Macabre,_Op._40_(trans._violin_and_piano).pdf

 Both with the original image extractor and with my workaround, it only finds 8 of the 20 pages. And I think the following object is the culprit:

```
<pikepdf.Stream(owner=<...>, data=<...>, {
    "/BBox": [ 0, 0, 1, 1 ],
    "/Filter": "/FlateDecode",
    "/Length": 85,
    "/Resources": {
      "/XObject": {
        "/QQAPIm0c609fa8": pikepdf.Stream(owner=<...>, data=<...>, {
            "/BitsPerComponent": 1,
            "/ColorSpace": "/DeviceGray",
            "/DecodeParms": {
              "/Columns": 2896,
              "/K": -1,
              "/Rows": 1973
            },
            "/Filter": "/CCITTFaxDecode",
            "/Height": 1973,
            "/Length": 27796,
            "/Subtype": "/Image",
            "/Width": 2896
          }),
        "/QQAPIm6a063ebe": pikepdf.Stream(owner=<...>, data=<...>, {
            "/BitsPerComponent": 1,
            "/ColorSpace": "/DeviceGray",
            "/DecodeParms": {
              "/Columns": 2896,
              "/K": -1,
              "/Rows": 1
            },
            "/Filter": "/CCITTFaxDecode",
            "/Height": 1,
            "/Length": 4,
            "/Subtype": "/Image",
            "/Width": 2896
          }),
        "/QQAPIm7c870ff2": pikepdf.Stream(owner=<...>, data=<...>, {
            "/BitsPerComponent": 1,
            "/ColorSpace": "/DeviceGray",
            "/DecodeParms": {
              "/Columns": 2896,
              "/K": -1,
              "/Rows": 1973
            },
            "/Filter": "/CCITTFaxDecode",
            "/Height": 1973,
            "/Length": 34281,
            "/Subtype": "/Image",
            "/Width": 2896
          })
      }
    },
    "/Subtype": "/Form"
  })>
```

It is not of type `XObject`, but a `Form` (whatever that is) containing the desired objects on a sub level. Also, it does not have a `Type` for some reason, only a `Subtype`.
