### ISSUE TITLE
Unable to add elements to a Nametree

### ISSUE THREAD

**Issue by columbarius** [pikepdf/pikepdf#369]
I'm trying to generate a pdf where each page is split into an upper and a lower part for better readability on an ebookreader. Generating this pdf is really nice with your package. To get references working I'd like to migrate the table of contents, which references locations by name. All references are stored in the Nametree `pdf.Root[\Name][\Dests]` so my plan is to parse those elements, calculate the new position, create a new entry and add this to the Nametree of the new pdf. At this point i noticed that a `Nametree` object doesn't let me insert elements. Is this a limitation of the python bindings?

**Comment by jbarlow83** [comment]
NameTree does let you insert - see test_nametree.py for this being exercised.

You cannot attach arbitrary python objects, though. It needs to pikepdf.Object or something trivially convertible to it.

You do need forward slashes not backslashes (`\`). Maybe that's a typo in your comment but if you were using them somewhere that might not be valid.
