### ISSUE TITLE
Exception on name tree construction

### ISSUE THREAD

**Issue by mara004** [pikepdf/pikepdf#376]
Attempting to construct a name tree for `pdf.Root.Names.Dests` of the attached document now raises a `ValueError` while this used to work with older versions of pikepdf:
```
Traceback (most recent call last):
[...]
    name_mapping = pikepdf.NameTree(pdf.Root.Names.Dests)
ValueError: NameTree must wrap a Dictionary that is owned by a Pdf
```
Is this due to a change in pikepdf (commit https://github.com/pikepdf/pikepdf/commit/380a644984caac19b225de715aaaba7c74642ec6, perhaps?), or rather in qpdf?

The document is deliberately not valid and part of some pdfium testing corpus. (The name tree implementations of mupdf and pdfium seem to tolerate the document silently, though.)

[pdfium_missing_key.pdf](https://github.com/pikepdf/pikepdf/files/9217798/pdfium_missing_key.pdf) ([source](https://pdfium.googlesource.com/pdfium_tests/+/a86e93e6d67106e32724fd52ee454c51997574ad/fx/other/bookmarkgetcolor.pdf))

**Comment by jbarlow83** [comment]
As you say it's not valid - `Dests` ought to be an indirect object.

While pikepdf didn't notice before, it looks like errors would occur if allowed to proceed - most likely the nametree structure would be readable if it was valid, but edits would silently fail. It would be better to patch this in your code with:

```python
dests = pdf.Root.Names.Dests
if not dests.is_indirect:
    dests = pdf.make_indirect(dests)
name_mapping = pikepdf.NameTree(dests)
```

That would work for older pikepdf too.

I'll make an alternate constructor where the owning Pdf is passed explicitly: `NameTree(dests, pdf, ...)`. That would allow pikepdf to do the boilerplate above on its own.

**Comment by mara004** [comment]
Thanks!
