### ISSUE TITLE
How to get the position or co-ordinates of the words in PDF ?

### ISSUE THREAD

**Issue by Laxmi530** [pikepdf/pikepdf#379]
Hai,
Thank you for providing such a beautiful library.
Trying to extract the bounding box or the position or the co-ordinates of the word in the form of [x, y, x+width, y+height].
Can someone please help me how can I do this.

**Comment by jbarlow83** [comment]
Use pdfminer.six for this. It's a whole PDF library dedicated to text processing - because it's very complicated. There's about 6 types of fonts, say.
