### ISSUE TITLE
DeprecationWarning: defusedxml.lxml

### ISSUE THREAD

**Issue by hsmett** [pikepdf/pikepdf#38]
Hello,

I just read the following warning:

```
DeprecationWarning: defusedxml.lxml is no longer supported and will be removed in a future release.
```

https://github.com/pikepdf/pikepdf/blob/master/src/pikepdf/models/metadata.py#L16

It seems some changes are required :)

Here is the related defusedxml documentation:
https://github.com/tiran/defusedxml#defusedxmllxml

Thank you !

**Comment by jbarlow83** [comment]
Fixed in v1.3.0
