### ISSUE TITLE
Undefined behavior in NameTreeHolder::NameTreeHolder()

### ISSUE THREAD

**Issue by willangley** [pikepdf/pikepdf#380]
[`NameTreeHolder::NameTreeHolder()`](https://github.com/pikepdf/pikepdf/blob/3b93f707d633fc981f5cefe1f5eff806dad32450/src/qpdf/nametree.cpp#L24)

```cc
    NameTreeHolder(QPDFObjectHandle oh, bool auto_repair = true)
        : ntoh(std::make_unique<QPDFNameTreeObjectHelper>(
              oh, *oh.getOwningQPDF(), auto_repair))
    {
        if (!oh.getOwningQPDF()) {
            throw py::value_error(
                "NameTree must wrap a Dictionary that is owned by a Pdf");
        }
    }
```

has undefined behavior when `oh.getOwningQPDF() == nullptr`. The initializer list is executed _before_ the constructor body, causing a null pointer dereference before the null check runs.

test_nametree.py has been failing in Google's continuous integration from v5.4.0 onwards because of this. (It looks like this was present before; I'm not sure why our CI only caught it now.)

**Comment by mara004** [comment]
I think `NameTreeHolder` will be removed soon (see the `feature/qpdf11` branch).
