### ISSUE TITLE
[QUESTION] What license do I need to use this for my project?

### ISSUE THREAD

**Issue by Jcwscience** [pikepdf/pikepdf#386]
I am getting paid to write a program for a business , and part of the program needs to modify and extract pdf files, Can I use this software in that context? And if I need a commercial license how would I apply for that?

Thanks!

**Comment by jbarlow83** [comment]
You can review the open source license (MPL-2) and determine if that is suitable for your needs. If you want a commercial license, we'll need to draft one.

**Comment by Jcwscience** [comment]
Ok never mind that looks fine, I think I understand. Thanks again
