### ISSUE TITLE
qpdf update to 11.0.0 breaks pikepdf.

### ISSUE THREAD

**Issue by benalb** [pikepdf/pikepdf#389]
Just a heads up about the update of [qpdf](https://github.com/qpdf/qpdf/releases/tag/v11.0.0) that breaks pikepdf in [Void Linux](https://github.com/void-linux/void-packages/pull/39230)

**Comment by Schamschula** [comment]
Same under MacPorts.

**Comment by mara004** [comment]
Are you aware of the [`feature/qpdf11`](https://github.com/pikepdf/pikepdf/tree/feature/qpdf11) branch?

**Comment by benalb** [comment]
is there any plan to merge the feature/qpdf11 branch into master with a new release? [Void Linux](https://github.com/void-linux/void-packages/blob/master/CONTRIBUTING.md) only accept stable releases.

**Comment by jbarlow83** [comment]
Yes, and very soon. CI doesn't pass on qpdf 11.0.0 yet.

**Comment by jbarlow83** [comment]
I've created a tracking issue for any qpdf 11/pikepdf 6 issues in #390
