### ISSUE TITLE
Can I remove PDF permission without password ?

### ISSUE THREAD

**Issue by AhmedNazir** [pikepdf/pikepdf#39]
Some post are suggested me to use pikePDF to remove PDF password and permission without knowing password.
Is it real ?

**Comment by jbarlow83** [comment]
PDF has an owner and user password. The file cannot be accessed without the owner password, although you could brute force it.

pikepdf does not enforce the editing restrictions that can be set with a user password, and currently does not implement saving encrypted files, so it saves files no restrictions at all.

```python
p = pikepdf.open('tests/resources/graph-encrypted.pdf', password='user')
p.save('no-password.pdf')
```

**Comment by jbarlow83** [comment]
I'll close the issue now. If you have further related questions feel free to reopen it.
