### ISSUE TITLE
qpdf 11.0 and pikepdf 6.0 - info for maintainers and problem tracking

### ISSUE THREAD

**Issue by jbarlow83** [pikepdf/pikepdf#390]
pikepdf 6 requires qpdf 11 and drops compatibility for all earlier versions. This is due to the complexity and backward incompatibility of changes from qpdf 10 to 11.

The authors of both packages were in regular collaboration about the changes in qpdf 11 and both contributed PRs to each other to make fairly complex changes as manageable as possible for each other and downstream. All users of qpdf and pikepdf from significant improvements to qpdf that benefit both projects.

pikepdf 6 also contains some minor API changes - mainly removal of functions that have been deprecated for some time.

Release status:
- qpdf11 support has been merged in pikepdf's master branch.
- The master branch will not be tagged until CI passes. That should happen soon within hours of this message.

Binary wheel status:
- Windows support is currently blocked by https://github.com/qpdf/qpdf/issues/766. The PR has been merged. We are waiting for qpdf 11.1.0.
- macOS x64 wheels will be available when 6.0.0.post2 is deployed to PyPI.

If you have problems not explained by the current release status, please report them in this issue.

Some users may be able to `pip install "pikepdf < 6"` as a temporary workaround.

**Comment by jberkenbilt** [comment]
I think qpdf/qpdf#770 fixes the Windows problem. Since it adds new exported symbols, the result will be released qpdf 11.1 along with a trivial number of additional changes.

**Comment by Schamschula** [comment]
I got a clean build of 6.0.0 under MacPorts. The only thing blocking the update is that pypi.org still shows 5.6.1, and the MacPorts python port group uses pypi to find source downloads.

**Comment by jbarlow83** [comment]
@Schamschula pikepdf 6.0.0.post1 has been released to pypi so you should be set.

**Comment by Schamschula** [comment]
Indeed: qpdf has been updated https://github.com/macports/macports-ports/commit/bae879e275bad75382dedcc614213ca01a6ef70d 
and so has py-pikepdf https://github.com/macports/macports-ports/commit/32a9b2d769019643c2032f87d60317f8fb665be8

**Comment by jberkenbilt** [comment]
I'm preparing 11.1 now and will have it out within a few hours. Then we can hopefully reset without workarounds. Thanks for all the quick testing and feedback. It's great to see how quickly packagers and downstreams respond to new releases, especially this one with so many big changes.

**Comment by jberkenbilt** [comment]
> I'm preparing 11.1 now and will have it out within a few hours.

For anyone who's watching, I'm going to wait until tomorrow to release 11.1. I ran into a few issues in testing and had to revert a commit. (Actually I found the problem by running pikepdf's test suite.) I have pushed what I believe will be 11.1 but I won't have time to cut the release today, so it will probably be first thing tomorrow US Eastern time. pikepdf's master branch passes its test suite against what I will release as 11.1. Running pikepdf's test suite is actually a great QA check for me. Although qpdf has a very thorough test suite, pikepdf's test suite often uncovers things. There is incredible value to having some tests developed by other people, so I'm grateful for the thoroughness of the test suite and for @jbarlow83 's help in ensuring that I can run it easily from the pikepdf source tree against the qpdf source tree.

**Comment by jberkenbilt** [comment]
I released qpdf 11.1.0 a few minutes ago. For those who are unaware, I announce release to an email list: https://sourceforge.net/projects/qpdf/lists/qpdf-announce. You can also monitor the github releases page or sourceforge. Probably everyone here already knows how to tell when qpdf is released. :-)

**Comment by javen46** [comment]
Hello, I would like to know when this problem will be solved?
issue：Wheel building error for Win64 Python 3.11

**Comment by mara004** [comment]
@javen46 See here: https://github.com/pikepdf/pikepdf/issues/410
