### ISSUE TITLE
pikepdf 6.x: Notable increase in manylinux wheel file size

### ISSUE THREAD

**Issue by mara004** [pikepdf/pikepdf#395]
Apparently, the size of manylinux wheels jumped from ~2 MB to ~19 MB with the update from pikepdf 5.x to 6.x, while windows and macos wheels are unaffected. Inspecting the wheel archives, I see the size of libqpdf jumped from 1.1 MiB (3.4 MiB decompressed) to 17.4 MiB (63 MiB decompressed). Why?
* https://pypi.org/project/pikepdf/5.6.1/#files
* https://pypi.org/project/pikepdf/6.0.1/#files

**Comment by jbarlow83** [comment]
libqpdf includes debug info since the cmake change. I should be able to build without debug info. Do you think there any concerns with leaving it in?

**Comment by mara004** [comment]
Ah, I see. Asking differently, what is the advantage of keeping debug symbols, only for one OS, if this hasn't been done for the past years?

I'm not sure about the concerns. As far as I've read, debugging symbols should not degrade runtime performance because they aren't loaded into memory unless the process is running in a debugger. As long as the changes didn't disable any compiler optimisations, the only drawback I'm aware of is the increase in file size (download time, disk space).

If it's a deliberate change, I'm okay with it, but would appreciate if it could be mentioned in the release notes.

**Comment by mara004** [comment]
Thanks!
