### ISSUE TITLE
How do you ensure that an image is actually replaced? 

### ISSUE THREAD

**Issue by pzemp1** [pikepdf/pikepdf#396]
Hi, currently I have a small task which revolves around me modifying up to 500 PDF files which are all unique. Each pdf file has these logo images that I must replace with another logo. I am having a look at one of your code snippets in the documentations: 
https://buildmedia.readthedocs.org/media/pdf/pikepdf/latest/pikepdf.pdf
Starting from page 53. 
I have done the same exact thing, except literally nothing is being changed unfortunately. My code is on stackoverflow on this link, 
https://stackoverflow.com/questions/73524659/replacing-a-word-with-another-word-and-replacing-an-image-with-another-image-in?noredirect=1#comment129874403_73524659

Currently, I am thinking it's because I store these image objects in a list, but that's all I have got so far. Please let me know what you think, thank you!

**Comment by jbarlow83** [comment]
From your StackOverflow code sample I don't see where you saved the PDF to a new file. pikepdf does not edit in place and does not commit changes unless asked to. You have to call .save() to save to a new file.

pikepdf's API for images is more oriented around extracting. It does not have a function to take care of all details with replacing one image with another. If you replace an image with another, you need to update the width, height, and colorspace of the image object or it will not be displayed properly in the PDF. When done correctly, the image will render in the same location on the PDF page(s) it appears on.

See ocrmypdf's optimize.py module for examples of replacing images with their optimized equivalents.

**Comment by pzemp1** [comment]
So in terms of "saving" the PDF to a new file, I have to essentially copy the contents over to a new and empty pdf and whenever I encounter the image? I was a bit confused since I was entirely relying on the example provided in the documentation when replacing an image, there was no copying over or saving any PDF files done in the examples, which is why I was confused. In regards to the implementations, I sort of understand what's going on in optimize.py, however the example in the documentation given made it look so simple, it gives the impression that pikepdf does in fact edit in place and does commit changes (how can we ask it to?). 

So right now, I am thinking of copying the contents over to a new pdf file but when I do, will I have to know about the coordinates of different things? Ideally I'd want it to essentially be identical but so far playing with PDF files with python has been pretty tough. 

Thanks for your help though.

**Comment by jbarlow83** [comment]
When you call Pdf.open, the PDF is loaded into memory. Whatever transformations you do happen in memory. When you call `.save('any.pdf')`, in-memory PDF is saved to a new PDF on disk. This workflow (including the method names) is the same as Pillow.

**Comment by jbarlow83** [comment]
You don't need to copy anything into a new PDF. The new PDF is the version you are editing in memory. You just need to save it.

PDF is one of the most complex file formats out there. In some ways it is more complex than HTML.

**Comment by pzemp1** [comment]
Thank you, that actually works. What I did was, I changed my Pdf.open(filepath) to Pdf.open(filepath,  allow_overwriting_input=True). And then I just added example.save() in the last line. Thank You so much, I'll let you know how this automation tasks goes like!

**Comment by jbarlow83** [comment]
Good to hear!
