### ISSUE TITLE
Extracted Image is almost blank

### ISSUE THREAD

**Issue by stumpylog** [pikepdf/pikepdf#401]
When extracting images from a PDF for barcode detection, I've found an image which, when extracted is *almost* blank, when I expect to have an image that contains basically the entire page.

[This PDF](https://github.com/paperless-ngx/paperless-ngx/files/9697707/grey_works.pdf) works, with the image on the second page extracted as I expect.

[This PDF](https://github.com/paperless-ngx/paperless-ngx/files/9697708/bw_no_detection.pdf) will extract the second page image as almost empty, with only a few splotchy pixels in the upper left portion of the image:
![image](https://user-images.githubusercontent.com/797416/193614750-212cfd91-3ff3-49e2-9f36-66be57f433db.png)

The "bad" image has a filter of CCITTFaxDecode, which I do find a reference to back in the 1.6.4 release notes, with basically the same issue.  Except in this case pikepdf didn't refuse to extract the image and I don't see anything that appears to reference EncodedByteAlign.

Is there a way to correctly extract this image to a PIL image?  Or should it also be refused for extraction?

edit: Forgot to say, this was tested with 5.6.1 and 6.0.2 on amd64, installed via the normal wheel.

```
>>> good_pdf = Pdf.open("grey_works.pdf")
>>> bad_pdf = Pdf.open("bw_no_detection.pdf")
>>> good_img = PdfImage(good_pdf.pages[1].images["/I1"])
>>> bad_img = PdfImage(bad_pdf.pages[1].images["/I1"])
>>> good_img.as_pil_image().save("test.jpg")
>>> bad_img.as_pil_image().save("test.tiff")
```

**Comment by vidiecan** [comment]
@jbarlow83 we also found problems with decoding rather simple looking image (that I cannot share, unfortunately)

```
3 0 obj 
<<
/Contents 7 0 R
/CropBox [ 0 0 609.88235 800.08163 ]
/MediaBox [ 0 0 609.88235 800.08163 ]
/Parent 2 0 R
/Resources <<
/ProcSet [ /PDF /Text /ImageB /ImageC /ImageI ]
/XObject <<
/im2 8 0 R
>> 
...
7 0 obj 
<<
/QPDF_original_id 25
/Length 99
>>
stream
q
1 0 0 1 0 0.000000000000000 cm
609.882352941176000 0 0 800.081632653061000 0 0 cm
/im2 Do
Q

endstream
endobj
8 0 obj
<< /BitsPerComponent 1 /ColorSpace /DeviceGray /DecodeParms [ << /Columns 1728 /K 0 /Rows 2178 >> ] /Filter [ /CCITTFaxDecode ] /Height 2178 /QPDF_original_id 27 /Subtype /Image /Type /XObject /Width 1728 /Length 84352 >>
stream 
```

The following code is executed https://github.com/pikepdf/pikepdf/blob/master/src/pikepdf/models/image.py#L502
The result can be saved, and it can be opened but is almost empty. 
Other tools (xpdf) can export the image; hence, should not be corrupted.

**Comment by jberkenbilt** [comment]
Both files that are having problems have `/K 0` in the image dictionary. From the PDF spec (formatting mine):

K: integer

A code identifying the encoding scheme used:

* `<0`: Pure two-dimensional encoding (Group 4)
* `=0`: Pure one-dimensional encoding (Group 3, 1-D)
* `>0`: Mixed one- and two-dimensional encoding (Group 3, 2-D), in which a line encoded one-dimensionally may be followed by at most K-1 lines encoded two-dimensionally The filter shall distinguish among negative, zero, and positive values of K to determine how to interpret the encoded data; however, it shall not distinguish between different positive K values.

Default value: 0.

A lot of tools assume G4, but K=0 is G3.

**Comment by mara004** [comment]
pikepdf currently does
```python
        k = self.decode_parms[0].get("/K", 0)
        if k < 0:
            ccitt_group = 4  # Pure two-dimensional encoding (Group 4)
        elif k > 0:
            ccitt_group = 3  # Group 3 2-D
        else:
            ccitt_group = 2  # Group 3 1-D
```

which is correct as per TIFF and PDF specs AFAICS. 2 is the right enum value for CCITT 3 1-D.

**Comment by jbarlow83** [comment]
@vidiecan Please try #438

**Comment by jbarlow83** [comment]
Latest release includes a fix

**Comment by vidiecan** [comment]
@jbarlow83 thank you. could you please elaborate on the final fix and if/how it addresses https://github.com/pikepdf/pikepdf/issues/401#issuecomment-1414160107 ?

**Comment by jbarlow83** [comment]
While you found ccitt_group=3 fixed the problem, that meant the code would do the same for Group3 1D and 2D, which did not seem correct. I modified your PR to do what the TIFF spec says.
https://github.com/pikepdf/pikepdf/commit/40c20c2335add429b79c04f2fce3351de0fc6c50
