### ISSUE TITLE
[FEATURE REQUEST] Load docinfo and not entire file.

### ISSUE THREAD

**Issue by 10maurycy10** [pikepdf/pikepdf#403]
Is there a way to load just the ``docinfo`` metadata and not the actual content?

The reason loading the entire file is a problem is because I have a large collection of PDFs stored on spinning rust drives, and I want to extract the metadata. (Title, Author....)

**Comment by jbarlow83** [comment]
Generally this is not possible in PDF. At minimum the header and footer have to be read to find the offsets of other content and depending on the file and how it was constructed, a significant amount of decompressing and structural interpretation may be needed. 

If it's really important you could write a parser that checks for some of the trivial cases and fall back to pikepdf. I'd think the time would be better spent parallelizing execution of pikepdf - unless you have very large or unusually complex PDFs I'd be surprised if the random access to PDF content was the bottleneck. 

The DocumentInfo metadata block is deprecated in favor of XMP and removed in PDF 2.0, which has been released. To parse metadata one really should check for XMP first.
