### ISSUE TITLE
how to save linearized pdf file to s3 bucket using pikepdf

### ISSUE THREAD

**Issue by RajHarry** [pikepdf/pikepdf#404]
Hi PikePDF Team,
first of all, it's a great library.

I got struck with an issue,
I want to save linearized pdf file to s3 bucket.
I was using below code to achieve the solution. but not succeeded.

>         s3_output_path = "<s3 bucket path>"
>         local_pdf_path = f"./linearized.pdf"
> 
>         with pikepdf.open(local_pdf_path) as pdf:
>             res = pdf.save(s3_output_path, linearize=True)

flow will be Like,
* I want to read pdf file first
* then linearize it
* save it in s3 bucket

if I can atleast get the linearized pdf object, I can able to save it in s3 bucket with put_object method like below
>         s3_client.put_object(Body=pdf_object, Bucket=s3_output_bucket_name, Key='./linearized.pdf')

can someone help with saving the file in s3 bucket...

Thanks in advance,
Raj

**Comment by jbarlow83** [comment]
pikepdf.save() will write to any writable object.   

You could write to a BytesIO object and then write that to S3 using the boto library, or use a library that mounts S3 as a virtual drive like s3fs-fuse. 

It's out of scope for pikepdf to do this directly.

**Comment by RajHarry** [comment]
Thank you for quick response @jbarlow83 

> pikepdf.save() will write to any writable object.

If possible, Can you please share an example to do it...
Like, writing to a writable object with pikepdf.save()

**Comment by jbarlow83** [comment]
```python
from io import BytesIO
import pikepdf

with pikepdf.open(...) as pdf:
    # your changes to the Pdf go here

    # now save it to memory
    bio = BytesIO()
    pdf.save(bio)
    # rewind
    bio.seek(0)
    # send to S3
    s3_client.put_object(Body=bio, ...)  # or maybe bio.read()
```

**Comment by RajHarry** [comment]
> 

Thank you @jbarlow83 For the code snippet.
