### ISSUE TITLE
Wheel building error for Win64 Python 3.11

### ISSUE THREAD

**Issue by yan-hic** [pikepdf/pikepdf#410]
Wheel does not exist for Windows and py 3.11 but building it fails too:
`Cannot open include file: 'qpdf/Constants.h': No such file or directory`

Note: not using `pikepdf` directly but is a dependency of `img2pdf`

**Comment by jbarlow83** [comment]
Thanks for the reminder.
I updated pikepdf for py311 a while ago, but another dependency (lxml) was out of date so the build would not complete. Now that lxml has published py311 wheels it should be shortly.

Generally speaking newly released Pythons are roughly for about a month while packagers make their updates.

**Comment by yan-hic** [comment]
Thanks for the prompt response ! Using it docker hence linux (and it works there) but developing in Win.

**Comment by jbarlow83** [comment]
Unfortunately I misread - lxml still hasn't uploaded win64 py311 wheels, so we're wedged for the moment.

**Comment by yan-hic** [comment]
You're right and the win64 built of lxml fails

**Comment by jusla** [comment]
Now that pikepdf 6.2.6 is available, I was able to install ocrmypdf with pip on Python 3.11.1. Thank you @jbarlow83 !
