### ISSUE TITLE
Replaced image is a lot bigger

### ISSUE THREAD

**Issue by perrotuerto** [pikepdf/pikepdf#412]
Hi, I am testing the image manipulation as it is describe here: https://pikepdf.readthedocs.io/en/latest/topics/images.html#replacing-an-image I am just testing changing the color space.

The issue I am having is that the final PDF size is x5 times bigger than the input one. I tried to use compression level 9 of zlib but I still have the same final size. Any recommendation of how to avoid this file increase?

**Comment by jbarlow83** [comment]
If you replace an one with a different one, it's quite possible that it will be larger. Especially when expanding to a wider colorspace - a grayscale image is potentially 8x as much data.
