### ISSUE TITLE
Outline link issue when using page_location='XYZ'

### ISSUE THREAD

**Issue by sldzys** [pikepdf/pikepdf#416]
When creating an outline, use page_location=‘XYZ' to meet the needs of ''Zoom level: Inherit Zoom". 

The following code can meet the zoom requirement well, but it will automatically increase the destination page by 1, which will prevent me from jumping to the first page anyway.

`from pikepdf import Pdf, OutlineItem

path=r'~'

pdf=Pdf.open(path+"/"+"tt.pdf")

with pdf.open_outline() as outline:
      outline.root.extend([
                          OutlineItem('Section One', 0**,page_location="XYZ"**)
                        ])

pdf.save(path+"/"+"tt1.pdf")
pdf.close()`

The 'Section One' button should have jumped to the first page, but now it has jumped to the second page. If I remove the bold 'page_location="XYZ"' in the above code, the jump end point is correct, but there is no ’Inherit Zoom‘ property

Note:
Python:3.8.5
pikepdf: 6.2.0

**Comment by PeterSlezak** [comment]
Try the following:
```
from pikepdf import Pdf, OutlineItem, PageLocation

path=r'~'

pdf=Pdf.open(path+"/"+"tt.pdf")

with pdf.open_outline() as outline:
    outline.root.extend([
    OutlineItem('Section One', 0, page_location=PageLocation.XYZ, left=0, top=0, zoom=0)
    ])

pdf.save(path+"/"+"tt1.pdf")
pdf.close()
```
Per PDF reference at least one of the left/top/zoom needs to be set to zero to have the "inherit zoom" setup. So alternatively you can leave them out completely as it will be set to zero by default.
