### ISSUE TITLE
[Feature Request] Overlay/Underlay Support via qpdf 8.4

### ISSUE THREAD

**Issue by DrLynch** [pikepdf/pikepdf#42]
I am trying to use pikepdf to generate a series of bibliographic overlays for already-published papers.  I am able to use pikepdf to open the files and handle other tasks but not to do overlay within pikepdf.  Qpdf 8.4 provides built-in support for overay/underlay of pdfs.  

http://qpdf.sourceforge.net/files/qpdf-manual.html#ref.overlay-underlay

But unfortunately I cannot get to it from pikepdf.  

My request is that the qpdf overlay/underlay functionality be added to pikepdf or failing that, that the underlying features be added to the next iteration of the internal interface so that they can be used.  

Thanks.

**Comment by DrLynch** [comment]
As an additional point there is a direct stamp function included in the new qpdf examples "pdf-overlay-page.cc".  However it is not clear to me how to map that example onto the internal qpd library.

**Comment by jbarlow83** [comment]
I haven't caught up with all of the recent API changes in QPDF. The difficulty is somewhat compounded by my decision to make pikepdf as Pythonic as possible, which means that there's some creativity involved in deciding how to best map the API to Python. I very likely need to break backward compatibility (pikepdf v2.0) to take advantage of them cleanly.

On the other hand, pikepdf can edit any data structure in a PDF so you can accomplish an overlay/underlay already. The new QPDF APIs just make this easier. You would add the overlay's content stream to the existing page's content stream (`page.page_contents.add()`, add any objects from the overlay to the page's /Resources dictionary, taking care that you don't overwrite the names of existing objects. OCRmyPDF does something similar in src/ocrmypdf/_weave.py, where an invisible text layer (the OCR text) is added to an existing page, in `_weave_layers_graft`.

**Comment by jonjrodriguez** [comment]
Can you provide more details on this? I wasn't successful trying to replicate what's happening in `_weave_layers_graft`. Thanks!

**Comment by Vieites** [comment]
More details and 'code example' would be very grateful, thank you.

**Comment by jbarlow83** [comment]
Implemented

**Comment by DrLynch** [comment]
Thanks!
