### ISSUE TITLE
incorrect header check

### ISSUE THREAD

**Issue by pjviz** [pikepdf/pikepdf#422]
When combining multiple pdfs into one we occasionally get an error like this:

**pikepdf._qpdf.DataDecodingError: error while getting stream data for 589 0 R: stream inflate: inflate: data: incorrect header check**

The pages.append calls are successful but the final_pdf.save call throws the above error.

Also the source pdfs themselves seem to open fine in a pdf viewer so we are unable to find a particular pattern or issue with the pdfs in question. Has anyone seen this issue before or any idea what might cause it?

```
for input_file in input_files:
        src = Pdf.open(input_file)

        for src_page in src.pages:
            final_pdf.pages.append(src_page)

    final_pdf.save(final_pdf_path)
```

**Comment by jbarlow83** [comment]
Try opening your PDFs individually and running check() on them which should force decoding of all compressed content. This would narrow the issue to at least the offending files.

While viewers may not report any issues, most silently ignore a wide range of issues. 

Sometimes pikepdf lazily copies compressed data (so will not notice if it's corrupted). In other cases decompression is triggered.
