### ISSUE TITLE
Cannot install pikepdf on Python 3.11.1 on 32-bit Windows

### ISSUE THREAD

**Issue by champlin2** [pikepdf/pikepdf#431]
@jbarlow83 I documented the error trying to install pikepdf on Windows Server 2019 using python 3.11.1 in this thread - https://github.com/ocrmypdf/OCRmyPDF/issues/460#issuecomment-1366127238 - but wanted to create an issue here so it wasn't lost.  Have the wheels been released for 3.11 so pikepdf can be updated?

```
python -m pip install pikepdf
Collecting pikepdf
  Using cached pikepdf-6.2.6.tar.gz (2.9 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting Pillow>=9.0
  Using cached Pillow-9.3.0-cp311-cp311-win32.whl (2.2 MB)
Collecting deprecation
  Using cached deprecation-2.1.0-py2.py3-none-any.whl (11 kB)
Requirement already satisfied: lxml>=4.8 in c:\python311-32\lib\site-packages (from pikepdf) (4.9.2)
Requirement already satisfied: packaging in c:\python311-32\lib\site-packages (from pikepdf) (22.0)
Building wheels for collected packages: pikepdf
  Building wheel for pikepdf (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for pikepdf (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [52 lines of output]
      C:\Users\MMEadmin\AppData\Local\Temp\2\pip-build-env-f01r4mhj\overlay\Lib\site-packages\setuptools_scm\git.py:295: UserWarning: git archive did not support describe output
        warnings.warn("git archive did not support describe output")
      C:\Users\MMEadmin\AppData\Local\Temp\2\pip-build-env-f01r4mhj\overlay\Lib\site-packages\setuptools_scm\git.py:312: UserWarning: unexported git archival found
        warnings.warn("unexported git archival found")
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win32-cpython-311
      creating build\lib.win32-cpython-311\pikepdf
      copying src\pikepdf\codec.py -> build\lib.win32-cpython-311\pikepdf
      copying src\pikepdf\jbig2.py -> build\lib.win32-cpython-311\pikepdf
      copying src\pikepdf\objects.py -> build\lib.win32-cpython-311\pikepdf
      copying src\pikepdf\settings.py -> build\lib.win32-cpython-311\pikepdf
      copying src\pikepdf\_augments.py -> build\lib.win32-cpython-311\pikepdf
      copying src\pikepdf\_cpphelpers.py -> build\lib.win32-cpython-311\pikepdf
      copying src\pikepdf\_exceptions.py -> build\lib.win32-cpython-311\pikepdf
      copying src\pikepdf\_methods.py -> build\lib.win32-cpython-311\pikepdf
      copying src\pikepdf\_version.py -> build\lib.win32-cpython-311\pikepdf
      copying src\pikepdf\_xml.py -> build\lib.win32-cpython-311\pikepdf
      copying src\pikepdf\__init__.py -> build\lib.win32-cpython-311\pikepdf
      creating build\lib.win32-cpython-311\pikepdf\models
      copying src\pikepdf\models\encryption.py -> build\lib.win32-cpython-311\pikepdf\models
      copying src\pikepdf\models\image.py -> build\lib.win32-cpython-311\pikepdf\models
      copying src\pikepdf\models\matrix.py -> build\lib.win32-cpython-311\pikepdf\models
      copying src\pikepdf\models\metadata.py -> build\lib.win32-cpython-311\pikepdf\models
      copying src\pikepdf\models\outlines.py -> build\lib.win32-cpython-311\pikepdf\models
      copying src\pikepdf\models\_content_stream.py -> build\lib.win32-cpython-311\pikepdf\models
      copying src\pikepdf\models\_transcoding.py -> build\lib.win32-cpython-311\pikepdf\models
      copying src\pikepdf\models\__init__.py -> build\lib.win32-cpython-311\pikepdf\models
      running egg_info
      writing src\pikepdf.egg-info\PKG-INFO
      writing dependency_links to src\pikepdf.egg-info\dependency_links.txt
      writing requirements to src\pikepdf.egg-info\requires.txt
      writing top-level names to src\pikepdf.egg-info\top_level.txt
      listing git files failed - pretending there aren't any
      reading manifest file 'src\pikepdf.egg-info\SOURCES.txt'
      adding license file 'LICENSE.txt'
      adding license file 'licenses-for-wheels.txt'
      writing manifest file 'src\pikepdf.egg-info\SOURCES.txt'
      copying src\pikepdf\_qpdf.pyi -> build\lib.win32-cpython-311\pikepdf
      copying src\pikepdf\py.typed -> build\lib.win32-cpython-311\pikepdf
      running build_ext
      building 'pikepdf._qpdf' extension
      creating build\temp.win32-cpython-311
      creating build\temp.win32-cpython-311\Release
      creating build\temp.win32-cpython-311\Release\src
      creating build\temp.win32-cpython-311\Release\src\qpdf
      "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.34.31933\bin\HostX86\x86\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -DPOINTERHOLDER_TRANSITION=4 -IC:\Users\MMEadmin\AppData\Local\Temp\2\pip-build-env-f01r4mhj\overlay\Lib\site-packages\pybind11\include -IC:\Python311-32\include -IC:\Python311-32\Include "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.34.31933\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\cppwinrt" /EHsc /Tpsrc/qpdf\annotation.cpp /Fobuild\temp.win32-cpython-311\Release\src/qpdf\annotation.obj /EHsc /bigobj /std:c++17
      annotation.cpp
      src/qpdf\annotation.cpp(4): fatal error C1083: Cannot open include file: 'qpdf/Constants.h': No such file or directory
      error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.34.31933\\bin\\HostX86\\x86\\cl.exe' failed with exit code 2
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pikepdf
Failed to build pikepdf
ERROR: Could not build wheels for pikepdf, which is required to install pyproject.toml-based projects
```

**Comment by jbarlow83** [comment]
The short answer is that you should switch to Python 3.11 64-bit. You seem to be using 32-bit.

32-bit Windows is on the way out so it's often neglected. What happened here was lxml, a large library that pikepdf depends on, did not bother releasing a wheel for win32 when they released everything else. I rebuilt pikepdf using this new release, and to get it to work, disabled win32 wheels. lxml has since released their win32 wheels as an afterthought several days, so it should be possible to retrigger the build.

Since you're trying to run ocrmypdf too, 32-bit Windows is not supported on ocrmypdf. It may work, but fails on randomly large-ish PDFs because 2GB just isn't much memory anymore. You need 64-bit Tesseract, 64-bit Ghostscript, 64-bit Python for best results.

**Comment by champlin2** [comment]
We're only interested in pikepdf (that other thread I came across when searching for the error we were getting).  Unfortunately we have to use the 32-bit version as another part of our solution refrerences COM libraries (through another python package) that are only available for 32-bit.

If it would be possible to build a version of pikepdf that would have a win32 wheel that would be great for us.  Thank you.

**Comment by champlin2** [comment]
@jbarlow83 any luck building a win32 version of pikepdf that will install on python 3.11.x?

**Comment by champlin2** [comment]
Just tried installing 6.2.7 on python 3.11.1 and got:

pip install pikepdf

Collecting pikepdf
  Using cached pikepdf-6.2.7.tar.gz (2.9 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting Pillow>=9.0
  Downloading Pillow-9.4.0-cp311-cp311-win32.whl (2.2 MB)
     ---------------------------------------- 2.2/2.2 MB 13.9 MB/s eta 0:00:00
Collecting deprecation
  Using cached deprecation-2.1.0-py2.py3-none-any.whl (11 kB)
Requirement already satisfied: lxml>=4.8 in c:\users\mmeadmin\appdata\local\programs\python\python311-32\lib\site-packages (from pikepdf) (4.9.2)
Requirement already satisfied: packaging in c:\users\mmeadmin\appdata\local\programs\python\python311-32\lib\site-packages (from pikepdf) (22.0)
Building wheels for collected packages: pikepdf
  Building wheel for pikepdf (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for pikepdf (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [52 lines of output]
      C:\Users\MMEadmin\AppData\Local\Temp\pip-build-env-uoiqc_or\overlay\Lib\site-packages\setuptools_scm\git.py:295: UserWarning: git archive did not support describe output
        warnings.warn("git archive did not support describe output")
      C:\Users\MMEadmin\AppData\Local\Temp\pip-build-env-uoiqc_or\overlay\Lib\site-packages\setuptools_scm\git.py:312: UserWarning: unexported git archival found
        warnings.warn("unexported git archival found")
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win32-cpython-311
      creating build\lib.win32-cpython-311\pikepdf
      copying src\pikepdf\codec.py -> build\lib.win32-cpython-311\pikepdf
      copying src\pikepdf\jbig2.py -> build\lib.win32-cpython-311\pikepdf
      copying src\pikepdf\objects.py -> build\lib.win32-cpython-311\pikepdf
      copying src\pikepdf\settings.py -> build\lib.win32-cpython-311\pikepdf
      copying src\pikepdf\_augments.py -> build\lib.win32-cpython-311\pikepdf
      copying src\pikepdf\_cpphelpers.py -> build\lib.win32-cpython-311\pikepdf
      copying src\pikepdf\_exceptions.py -> build\lib.win32-cpython-311\pikepdf
      copying src\pikepdf\_methods.py -> build\lib.win32-cpython-311\pikepdf
      copying src\pikepdf\_version.py -> build\lib.win32-cpython-311\pikepdf
      copying src\pikepdf\_xml.py -> build\lib.win32-cpython-311\pikepdf
      copying src\pikepdf\__init__.py -> build\lib.win32-cpython-311\pikepdf
      creating build\lib.win32-cpython-311\pikepdf\models
      copying src\pikepdf\models\encryption.py -> build\lib.win32-cpython-311\pikepdf\models
      copying src\pikepdf\models\image.py -> build\lib.win32-cpython-311\pikepdf\models
      copying src\pikepdf\models\matrix.py -> build\lib.win32-cpython-311\pikepdf\models
      copying src\pikepdf\models\metadata.py -> build\lib.win32-cpython-311\pikepdf\models
      copying src\pikepdf\models\outlines.py -> build\lib.win32-cpython-311\pikepdf\models
      copying src\pikepdf\models\_content_stream.py -> build\lib.win32-cpython-311\pikepdf\models
      copying src\pikepdf\models\_transcoding.py -> build\lib.win32-cpython-311\pikepdf\models
      copying src\pikepdf\models\__init__.py -> build\lib.win32-cpython-311\pikepdf\models
      running egg_info
      writing src\pikepdf.egg-info\PKG-INFO
      writing dependency_links to src\pikepdf.egg-info\dependency_links.txt
      writing requirements to src\pikepdf.egg-info\requires.txt
      writing top-level names to src\pikepdf.egg-info\top_level.txt
      listing git files failed - pretending there aren't any
      reading manifest file 'src\pikepdf.egg-info\SOURCES.txt'
      adding license file 'LICENSE.txt'
      adding license file 'licenses-for-wheels.txt'
      writing manifest file 'src\pikepdf.egg-info\SOURCES.txt'
      copying src\pikepdf\_qpdf.pyi -> build\lib.win32-cpython-311\pikepdf
      copying src\pikepdf\py.typed -> build\lib.win32-cpython-311\pikepdf
      running build_ext
      building 'pikepdf._qpdf' extension
      creating build\temp.win32-cpython-311
      creating build\temp.win32-cpython-311\Release
      creating build\temp.win32-cpython-311\Release\src
      creating build\temp.win32-cpython-311\Release\src\qpdf
      "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.34.31933\bin\HostX86\x86\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -DPOINTERHOLDER_TRANSITION=4 -IC:\Users\MMEadmin\AppData\Local\Temp\pip-build-env-uoiqc_or\overlay\Lib\site-packages\pybind11\include -IC:\Users\MMEadmin\AppData\Local\Programs\Python\Python311-32\include -IC:\Users\MMEadmin\AppData\Local\Programs\Python\Python311-32\Include "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.34.31933\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\cppwinrt" /EHsc /Tpsrc/qpdf\annotation.cpp /Fobuild\temp.win32-cpython-311\Release\src/qpdf\annotation.obj /EHsc /bigobj /std:c++17
      annotation.cpp
      src/qpdf\annotation.cpp(4): fatal error C1083: Cannot open include file: 'qpdf/Constants.h': No such file or directory
      error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.34.31933\\bin\\HostX86\\x86\\cl.exe' failed with exit code 2
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pikepdf
Failed to build pikepdf
ERROR: Could not build wheels for pikepdf, which is required to install pyproject.toml-based projects`

**Comment by jbarlow83** [comment]
After pretty much everything going wrong in my attempts to prepare this release (multiple third party dependencies released breaking changes and hypothesis found new random issues), it seems I've exceeded PyPI's quota for pikepdf. We are now waiting for someone at PyPA to approve an increase of 10 GB. (Seems like a lot of trouble for $0.10 worth of disk space if you ask me.)

Anyway, until they approve, all pikepdf releases are blocked.

In the meantime, please note that the documentation does give instructions for building on Windows.

**Comment by champlin2** [comment]
> After pretty much everything going wrong in my attempts to prepare this release (multiple third party dependencies released breaking changes and hypothesis found new random issues), it seems I've exceeded PyPI's quota for pikepdf. We are now waiting for someone at PyPA to approve an increase of 10 GB. (Seems like a lot of trouble for $0.10 worth of disk space if you ask me.)
> 
> Anyway, until they approve, all pikepdf releases are blocked.
> 
> In the meantime, please note that the documentation does give instructions for building on Windows.

Thank you for all your work on this!  I have a workaround of using python 3.9 32bit for now but would like to move to 3.11.1 when we can.  Please post an update when a new version is ready and I'll try to upgrade.

**Comment by jbarlow83** [comment]
Should be fixed

**Comment by champlin2** [comment]
> Should be fixed

Thanks!  Just successfully installed 6.2.8 on Python 3.11.1 Win32
