### ISSUE TITLE
Update comparison table

### ISSUE THREAD

**Issue by FabioPedretti** [pikepdf/pikepdf#432]
The comparison table on [README.md](https://github.com/pikepdf/pikepdf#readme) still shows [PyPDF2](https://pypi.org/project/PyPDF2/), however they says:

> NOTE: The PyPDF2 project is going back to its roots. PyPDF2==3.0.X will be the last version of PyPDF2. Development will continue with [pypdf==3.1.0](https://pypi.org/project/pyPdf/).

So it would be fair to update the table replacing PyPDF2 with pypdf.

**Comment by FabioPedretti** [comment]
No, I am not at all involved in any PDF libraries, I was just passing by after using pdfarranger and noticed it...

**Comment by mara004** [comment]
What inaccuracies exactly? AFAICS, the main difference they outline is that pypdf is pure-python while pikepdf/pymupdf have C extensions. And they've got a point that C extensions do have some disadvantages.

> I opened a PR about that several months ago.

I'm unable to find the PR: https://github.com/py-pdf/pypdf/pulls?q=author%3Ajbarlow83

**Comment by MartinThoma** [comment]
@jbarlow83 I'm the maintainer of pypdf (and PyPDF2). I'm open to any PR that improves the documentation. I want to make a fair comparison :-)
