### ISSUE TITLE
Which version of 6.2.8 is latest?

### ISSUE THREAD

**Issue by dcopso** [pikepdf/pikepdf#435]
6.2.8 was yanked and 6.2.8.post{1,2} have unusual suffixes. Which version is best to use?

Thanks!

**Comment by jbarlow83** [comment]
.postN is a standard suffix. https://peps.python.org/pep-0440/#post-releases

There were build problems that caused some releases of 6.2.8 to be missing binary wheels for certain Python version + platform combinations that were supposed to build.

pip ought to select 6.2.8.post2

**Comment by dcopso** [comment]
Thanks for that (and for your work on this great package!!)! Didn't know about that being a normal suffix.

BTW it looks like [pypi still lists .post1](https://pypi.org/project/pikepdf/) as the latest version.

**Comment by jbarlow83** [comment]
Admittedly the situation was unclear so I released 6.2.9 to clarify.
