### ISSUE TITLE
Can't place a overlay "exactly"

### ISSUE THREAD

**Issue by kbengs** [pikepdf/pikepdf#446]
```
from pikepdf import Pdf, Rectangle

pdf = Pdf.open("./Rectangles2.pdf")
dest = pdf.pages[0]
overlay = pdf.pages[1]
pdf.pages.append(dest)

print('Destination page size', list(dest.MediaBox))
print('Overlay page size', list(overlay.MediaBox))

# Overlay rectangle in top right corner of destination page
x2 = dest.MediaBox[2]
x1 = x2 - (overlay.MediaBox[2] - overlay.MediaBox[0])
y2 = dest.MediaBox[3]
y1 = y2 - (overlay.MediaBox[3] - overlay.MediaBox[1])

x1, y1, x2, y2 = int(x1), int(y1), int(x2), int(y2)
print(x1, y1, x2, y2)

pdf.pages[2].add_overlay(overlay, Rectangle(x1, y1, x2, y2), shrink=False, expand=False)

pdf.save("output.pdf")
```

Output:
```
Destination page size [0, 0, Decimal('280.5'), 312]
Overlay page size [0, 0, Decimal('27.75'), Decimal('34.5')]
252 277 280 312
```

[Rectangles2.pdf](https://github.com/pikepdf/pikepdf/files/10776740/Rectangles2.pdf) has two pages. The code add page1 as overlay on page0 in top right corner. The resulted page is stored in [output.pdf](https://github.com/pikepdf/pikepdf/files/10776770/output.pdf) page2.
It does not seem to be possible to position the overlay exactly in the corner. It will be about 0,25pt off.

I am using integer for the overlay rectangle. It gives better results than Decimal or float.

Setting shrink=True, expand=True does not give any better result.

This is how the result looks like:
![2023-02-19_13-12](https://user-images.githubusercontent.com/60842129/219945398-7911cb56-3a78-47c5-a363-9e132283c5ea.png)

And here the page is opened in Incscape and zoomed on top right corner: 
![2023-02-19_13-03](https://user-images.githubusercontent.com/60842129/219945428-f379008b-6b83-4838-85a1-bf2796e372de.png)

Is this a bug or is it a physical limitation?

**Comment by jbarlow83** [comment]
Destination page size [0, 0, Decimal('280.5'), 312]
Overlay page size [0, 0, Decimal('27.75'), Decimal('34.5')]
252 277 280 312

The overlay's "right" coordinate is 280, and the page width is 280.5, so you're going to see a gap on the right edge. You'll need to do it without rounding.

**Comment by kbengs** [comment]
Thank you for your response. You mean add the rectangle without converting it to integer first?

If add the the overlay rectangle without rounding, it will be to high up and too far to the right:
(This is zoomed so the x offset can be seen. Black is the destination and grey is the overlay)
![2023-02-20_05-52](https://user-images.githubusercontent.com/60842129/220005809-45e89bb2-003b-469e-bd1c-856ebd5a5871.png)

This is the output without rounding:
```
Destination page size [0, 0, Decimal('280.5'), 312]
Overlay page size [0, 0, Decimal('27.75'), Decimal('34.5')]
252.75 277.5 280.5 312
```

**Comment by jbarlow83** [comment]
I think you would need to use the decimal coordinates and set Interpolate = True on the image inside the overlay. I believe the PDF viewer is refusing to resample the image since you don't have this set, and the margin between its position and the end of the page is sub-pixel.

Might be something like `next(pdf.pages[1].images).Interpolate = True` before doing the overlay.

To confirm this is the case, try placing a solid vector rectangle rather than a bitmap image.

**Comment by kbengs** [comment]
No, Decimal coordinates and placing a vector rectangle does not improve the offset.

As far as I can see the offset is always less than 0.5 PDF point.
By manipulating the rectangle coordinates I can have the overlay positioned exactly where it should be. I have tried to figure out how to calculate the needed offset so that it would work for any page size, but yet I am not successful.

I see the same offset in other PDF viewers too (including Acrobat reader), but only Inkscape allows to zoom that much so the offset is so clearly visible.

**Comment by jbarlow83** [comment]
I did the following

```python
import pikepdf
from pikepdf import Pdf, Rectangle

pdf = Pdf.open("./issue446.pdf")
dest = pdf.pages[0]
overlay = pdf.pages[1]
pdf.pages.append(dest)

print('Destination page size', list(dest.MediaBox))
print('Overlay page size', list(overlay.MediaBox))

# Overlay rectangle in top right corner of destination page
x2 = dest.MediaBox[2]
x1 = x2 - (overlay.MediaBox[2] - overlay.MediaBox[0])
y2 = dest.MediaBox[3]
y1 = y2 - (overlay.MediaBox[3] - overlay.MediaBox[1])

print(x1, y1, x2, y2)

pdf.pages[2].add_overlay(overlay, Rectangle(x1, y1, x2, y2), shrink=False, expand=False)

pdf.save("issue446_out.pdf")
```

Just skipping integer conversion.

In Evince, the image is drawn to the edge as expected. 

![image](https://user-images.githubusercontent.com/1825843/220447068-7ce3a362-e1d3-4155-97bc-0610eb8c316b.png)

I'm going to close the issue since it may be a PDF renderer difference -- unless you can point to something that pikepdf is specifically doing wrong in how it generates the PDF.

**Comment by kbengs** [comment]
> I did the following

On my machine I also need to:
```
import locale
locale.setlocale(locale.LC_NUMERIC, 'C')
```

If I use the default locale:
`LC_NUMERIC=fi_FI.utf8`
The return value from `self.calc_form_xobject_placement()` in `_over_underlay()` in `_methods.py` will be:
b'q\n1 0 0 1 253.125 277.75 cm\n/CesrUV90NRdHaj1fAQoEqA Do\nQ\n'
-> Which is not right, the overlay is not exactly at the edge

If I use:
`LC_NUMERIC=C`
The return value is:
b'q\n1 0 0 1 252.75 277.5 cm\n/NDyOrvzp32pSXfSasMgT5g Do\nQ\n'
-> Which is right, the overlay is exactly at the edge

At least `LC_NUMERIC=en_US` also works.

And here is the terminal output again when "skipping integer conversion":
```
Destination page size [0, 0, Decimal('280.5'), 312]
Overlay page size [0, 0, Decimal('27.75'), Decimal('34.5')]
252.75 277.5 280.5 312
```

I am not sure if this is a bug and if so where it is, but I post the information here anyway if someone else encounter this.
