### ISSUE TITLE
[feature request] Saving with file encryption

### ISSUE THREAD

**Issue by corrupt** [pikepdf/pikepdf#45]
First of all l want to say that basing a python library on qpdf is a great idea. Pretty much all PDF libraries in python lack at least one of the features that qpdf has readily available.

One such feature is saving with PDF encryption. I have yet to find a library that supports more than 128bit RC4. My work-around so far is to generate a PDF in reportlab or modify it in pypdf and then call qpdf's binary on a tempfile from python to encrypt it. This approach, however, turns out to be pretty volatile as qpdf's cli interface is prone to change with version bumps.

I was wondering whether implementing this feature is planned for pikepdf. It would be great to finally have a python interface to proper aes encryption for PDFs.

**Comment by jbarlow83** [comment]
Currently if encryption is present it will be preserved, including AES, but there is no way to add encryption or change the parameters.

I always meant to add encryption... just didn't get to it/no one asked yet. I'll do it soon unless I get distracted by shinier objects.

If you need it to work immediately, you could create an encrypted empty PDF in qpdf, and use pikepdf to append to it.

**Comment by rauf-asad** [comment]
I recently thought of the same. I think we should have this feature within pikepdf. Currently I had to use pypdf2 for encrypting files but that was very painful for files that had non-english texts. I think it would be cool if we had the encrypt feature included here.

**Comment by jbarlow83** [comment]
Done for v1.4.0
`pdf.save(encryption=pikepdf.Encryption(owner='example')`

**Comment by corrupt** [comment]
I just wanted to report back on this. That was really quick man, thank you so much!

I re-implemented some of my qpdf-binary wrappers with pikepdf's new functionality and it does **exactly** what I needed. Pikepdf is now the only python PDF library with proper aes support.
