### ISSUE TITLE
The first 30 pages of the cut file are about the same size as the original file.

### ISSUE THREAD

**Issue by juzj** [pikepdf/pikepdf#455]
<img width="765" alt="image" src="https://user-images.githubusercontent.com/36066382/223954569-7d0d3151-3094-4e77-b866-2d63213a2779.png">
with pikepdf.open("sample.pdf") as pdf:
        del pdf.pages[30:]
         # 使用pikepdf切割PDF文件
        pdf.save("sample_30_pages.pdf")

**Comment by jbarlow83** [comment]
There is a lot of data in PDF that may be associated with multiple pages so removing some pages might not reduce file size. 

See the documentation for pikepdf.PDF.save
