### ISSUE TITLE
Splitting pages breaks pdf/a check

### ISSUE THREAD

**Issue by Gthorsten65** [pikepdf/pikepdf#457]
Hi,
just found this module.
My Task is to splitt a pdf file into separate files.
The Problem, if the original File is PDF/A complined ( use on of these checkers in the internet)
the spliited files always fails these test.
I just did it with this few line below.

So open the original.
Create two new PDF'S and add one page from the pdf/a complient to the new one.
After saving the check fails.

So what did I wrong, because on the main page the is a note that this module will not break to Document
"Modifies PDF/A without breaking PDF/A compliance"

`
    pdf = Pdf.open('D:\dev\sourcen\project\cloner\Test_PdfA.pdf')
    dst_even = Pdf.new()
    dst_odd = Pdf.new()

    dst_even.pages.append(pdf.pages[0])
    dst_odd.pages.append(pdf.pages[1])
    dst_even.save("test_pdfA_even.pdf")
    dst_odd.save("test_pdfA_odd.pdf")
`

**Comment by jbarlow83** [comment]
With Pdf.new() you are constructing a new PDF from scratch and copying individual pages into to it. The PDF/A tag belongs to the file as a whole.

To preserve metadata, including PDF/A, you should open the original PDF, and then (in your case) delete the unwanted even pages, and save as odd.pdf; then reopen the original, delete the unwanted odd pages, and save as even.pdf.

**Comment by Gthorsten65** [comment]
Thanks, I will try it.
But what I really want. I have a pdf, pdf a compliant, and Splitt it into 2 new pdfs, for example with even and odd pages. The 2 new ones should also bei pdf a compliant.

16.03.2023 05:17:31 jbarlow83 ***@***.***>:

**Comment by jbarlow83** [comment]
If you begin with an existing PDF/A and transform it, its PDF/A status will be preserved and not lost on saving (assuming you don't transform it a way that violates the PDF/A spec).

**Comment by Gthorsten65** [comment]
Ok, that means I have to copy the original file, twice, one Namen even the other named odd, and then remove on both files the relevant pages?

16.03.2023 07:18:08 jbarlow83 ***@***.***>:

**Comment by jbarlow83** [comment]
Open the original file, make the odd version and save it. Then open the original file again, make the even version, and save it. The key idea is to _transform the original file_ in the way you want, rather than trying to construct a new PDF.

**Comment by Gthorsten65** [comment]
Ok, thanks. Will try it in the evening, after work
