### ISSUE TITLE
Add link to docs

### ISSUE THREAD

**Issue by impredicative** [pikepdf/pikepdf#46]
For each repo, GitHub allows a link to a website for it. For example, looking at https://github.com/python/cpython/ , it shows "The Python programming language https://www.python.org/ ". Similarly, pikepdf shows "A Python library for reading and writing PDF, powered by qpdf". It will help if pikepdf also includes the website link https://pikepdf.readthedocs.io there. It will make this link so much easier to find. Thanks.

**Comment by jbarlow83** [comment]
Thanks for the tip!
