### ISSUE TITLE
How to add XMP /Metadata to a specific page?

### ISSUE THREAD

**Issue by dmidlo** [pikepdf/pikepdf#466]
Heyo!  I believe I'm already on the the right track to figuring this out, but I'm wondering if you can speed up my research process?

I'm looking to store some data on each page of a PDF for a personal data science project; text analytics like word-frequency, etc.  

I'm already storing similar information at the document level, having added an XMP key to store some serialized json.  Obviously here, I'm using `.open_metadata` on the pdf.  I'd like some metadata to persist at the page level because at times I'll be splitting pages off of the document for analysis.

What I'm looking for is a snippet or example of how to create a `Stream` object containing a XMP fragment and add it to a `Page` object's `"/Metadata"` key (and create the `/Metadata` key if it doesn't already exist.)  

XMP Page metadata located at this key is part of the pdf spec afaik...

The dream would be to follow the existing idiom in pikepdf by using a context manager in the same way as `.open_metadata`, something like:

```Python
 with pdf.pages[x].open_page_metadata() as page_metadata:
     page_metadata["pdf:eggs"] = ham
```
but I would settle for a `get_page_metadata(page)` and `set_page_metadata(page)` if it could be achieved.

Thanks for any help on this!!!! Keep up the great work!!!

**Comment by jbarlow83** [comment]
You can insert arbitrary XML into the XMP metadata, which could include XML that specifies it is applicable to a specific page. Although that will not work if pages are added/removed.

To attach page private level data, you can create a PieceInfo dictionary. A conforming PDF writer should preserve PieceInfo it, but no guarantees.

That would work like this. (This does not do error checking; for example this would overwrite any other app's existing PieceInfo.)

```python
stream = Stream(pdf, b'your binary data')
pdf.pages[x].PieceInfo = Dictionary(
  DmildoApp=Dictionary(
    LastModified=<last modified date in PDF's weird date format>, 
    Private=stream
  )
)
```

You can store PDF objects in Private too, e.g. arrays or other dictionaries, if you don't want a binary stream.

**Comment by dmidlo** [comment]
@jbarlow83  Haven't tried it, but it's obvious that this will work perfectly for my use case!

Also it's nice because, I don't actually want or need guarantees of persistence beyond the analysis/training phase.  All the data I'm storing should and is removed because it's bloat to the overall filesize of the pdf!

Just to double check, the `pdf` in `stream = Stream(pdf, b'your binary data')` and `pdf.pages[x].PieceInfo = ...` is a reference to the same pikepdf `Pdf` object?    That's actually the part where I had a hard time reading how it worked from `src/pikepdf/objects.py`....

... lol, and now that I'm reading it again, I see that the arg/param is actually called `owner` and type hinted to `Pdf`,  So I've answered my own question!   (I am curious about how to use the `d` arg, but that's for another time)

```
 Args:
            owner: The Pdf to which this stream shall be attached.
            data: The data bytes for the stream.
            d: An optional mapping object that will be used to construct the stream's
                dictionary.
            kwargs: Keyword arguments that will define the stream dictionary. Do not set
                /Length here as pikepdf will manage this value. Set /Filter
                if the data is already encoded in some format.
```

Thanks again!!!

**Comment by dmidlo** [comment]
... and if I want my app to be conforming to PieceInfo as you've described (which I do), I'll just end up checking for an existing `Dictionary` at `.PieceInfo`, if it exists, either append/update my `DmidloApp` key to it, or if it's immutable (not sure, haven't read that far), but if it is immutable, grab it, and store it as a key in my new PieceInfo (`Dictionary(DmidloApp=..., ExistingPieceInfo=existing_pieceinfo_dictionary)` and in my cleanup phase, undo that operation and restore the the old PieceInfo.

Great! Again... and again.. Thanks!

**Comment by jbarlow83** [comment]
Normally the `d` dictionary wouldn't normally be used here. It's usually used to store information about how the stream is encoded or compressed.

The existing Dictionary is mutable. You create it if it's not there, or insert your unique key to it alongside any other keys that happen to be there, without disturbing them.
