### ISSUE TITLE
Image extraction error

### ISSUE THREAD

**Issue by mnmtz** [pikepdf/pikepdf#480]
When extracting the images in the following PDF, one of the 6 images throws HifiPrintImageNotTranscodableError().

[example_121.pdf](https://github.com/pikepdf/pikepdf/files/11966868/example_121.pdf)

```
# Page 1
image
    Position: (34.0157, 235.2583, 202.6772, 340.1575)
    Filters: ['DCTDecode']
    width: 820
    height: 510
    horizontal_dpi: 350.0504150390625
    vertical_dpi: 350.0504455566406
    bits_per_pixel: 8
    colorspace: DeviceN
image
    Position: (216.8504, 235.2583, 385.5118, 340.1575)
    Filters: ['DCTDecode']
    width: 820
    height: 510
    horizontal_dpi: 350.0504150390625
    vertical_dpi: 350.0504455566406
    bits_per_pixel: 8
    colorspace: DeviceN
image
    Position: (453.5312, 368.9515, 622.2169, 473.8658)
    Filters: ['DCTDecode']
    width: 820
    height: 510
    horizontal_dpi: 349.9999694824219
    vertical_dpi: 350.0000305175781
    bits_per_pixel: 8
    colorspace: DeviceN
image
    Position: (636.3779, 390.1656, 805.0637, 497.0702)
    Filters: ['DCTDecode']
    width: 703
    height: 446
    horizontal_dpi: 300.06097412109375
    vertical_dpi: 300.3800354003906
    bits_per_pixel: 24
    colorspace: DeviceCMYK
image
    Position: (216.8382, 416.6681, 385.524, 521.5823)
    Filters: ['DCTDecode']
    width: 820
    height: 510
    horizontal_dpi: 349.99993896484375
    vertical_dpi: 350.0000305175781
    bits_per_pixel: 8
    colorspace: DeviceN
image
    Position: (635.3164, 178.6998, 806.0428, 285.7782)
    Filters: ['FlateDecode']
    width: 912
    height: 572
    horizontal_dpi: 384.61541748046875
    vertical_dpi: 384.6153869628906
    bits_per_pixel: 8
    colorspace: Indexed
-> Count: 6

-> Total count: 6
```

**Comment by mara004** [comment]
Actually I would expect that 4 images throw the error, because you have 4 times `DeviceN` colorspace here, but probably it breaks on the first occurrence.
(BTW, if I recognize this correctly the dumped inspection is not from pikepdf, but from pypdfium2.)

**Comment by jbarlow83** [comment]
@mnmtz 
example_121.pdf contains images that cannot converted to standard image formats. The exception is correct.

app-design*.pdf contains images with 16 bits per component (48-bit RGB + 16 bit A). Third parties like Pillow don't support saving these images, so pikepdf cannot support them either at this time.

You can manually read the image data by calling .read_bytes() on the stream object, and then passing the raw data to a Python library does support such images, such as OpenCV.

I'll have to close this as "not planned/not possible at this time."
