### ISSUE TITLE
Feature: Add simple Drawings to existing PDF (line, rectangle etc.)

### ISSUE THREAD

**Issue by PeterSlezak** [pikepdf/pikepdf#484]
I've spend some time working with pikepdf to add a simple drawings to a page in existing pdf file. I've created a simple [demo ](https://github.com/PeterSlezak/pikedf_drawings/blob/main/pike_draw.py) if anybody have a similar problem. It would be great if you could add this feature to future pikepdf release or at least add something similar to the examples.

**Comment by jbarlow83** [comment]
Now implement in pikepdf.canvas
