### ISSUE TITLE
Better visibility for release notes / changelog

### ISSUE THREAD

**Issue by dreua** [pikepdf/pikepdf#488]
I always need a moment to find the release notes / changelog when a new version comes out. As an easy fix, could we just have a link in the Readme that reads release notes or changelog linking to [the page in the documentation](https://pikepdf.readthedocs.io/en/latest/releasenotes/index.html)?

As of now, it actually seems to lack an entry for 8.0.0 but that might just take a moment to update.

Many projects on Github use its release feature in addition to a tag, which also allows one to get notified of new releases and quickly view the most important changes of the new release. It would be great to have that, too but I don't want to put an additional maintenance burden on you. As always, thanks for the great work!

Btw: I'm happy to see another of my favorite projects with a main branch :heart:

**Comment by jbarlow83** [comment]
Linking the release notes is a great idea. I will do that.

Most of this comes from Python binary wheels on all archs and platforms being quite a hassle for a one person project. I spent significantly more time on release engineering than the software itself. Hopefully, hopefully these latest changes will eliminate some perennial time sucks and not require too much rework in the future. Still, the build involves 3 services (GitHub Actions, Cirrus CI, and ReadTheDocs). ReadTheDocs in particular can be very fragile. And it's still not rendering bullet points, which has been an open issue with them for 2 years now. Anyway, my frustrations and rants aside...

If you have suggestions to ensure that pushing a tag will create a GitHub Release with the right release notes, while also ensuring that the same release notes show up in the right place in the documentation, or I'm all ears.

**Comment by dreua** [comment]
I do feel you, let's just go with the link :wink:

**Comment by m-holger** [comment]
On a different but slightly related matter, from the homepage it is not obvious what the current released version of pikepdf is. Both PDF Arranger and QPDF show the latest release on the right-hand side under the "Releases" heading, which I find quite useful. (Perhaps not so much for QPDF). I have no idea how it is done, but hopefully it is not onerous.

(Also, under the "About" heading, in "powered by qpdf", QPDF should probably be capitalized, and at the bottom of README.md, "MPL 2.0 is a not a "viral" license." seems to have an extra "a" or perhaps it should be 'non-"viral" ')

**Comment by dreua** [comment]
@m-holger The version shown on Github is done exactly through the Github releases. It should be possible to have a GHA to automatically create a GH Release for each tag you push. (Maybe with regex filter for version tags in case you may ever push any other tags. Or keep it simple and don't filter, you can always delete or edit unwanted releases after the fact.)

Just another thought: We could add a link to `https://github.com/pikepdf/pikepdf/blob/main/docs/releasenotes/version<some regex to get major version>.rst` there also quite easily :thinking: 

Let me know in case you want any help with that.

I'm not a native speaker but saying something is "not a viral license" seems fine to me. In fact I did write the previous sentence without realizing that it is the perfect example of the "something is not a &lt;adjective&gt; something" pattern.

**Comment by jbarlow83** [comment]
Did the link, "not viral license" thing, and "powered by QPDF". Thanks for the suggestions. I'll see what I can do about releases.

**Comment by m-holger** [comment]
>  I'll see what I can do about releases.

Not a big thing. I wouldn't worry if it doesn't have an easy solution.

**Comment by m-holger** [comment]
@dreua , I would agree 'das es nicht wirklich einen Unterschied macht' whether it is 'not a viral license' or 'a not viral license', but I would not go as far as saying 'das es wirklich keinen Unterschied macht' or 'das es wirklich nicht einen Unterschied macht'. There are slight differences in emphasis. (And I'm sure there must be a better translation than 'Unterschied')

**Comment by dreua** [comment]
Alright, I'm happy with the link, shall we close this or do you want to keep it open for further improvements?

'MPL 2.0 is a not "viral" license' just sounds wrong to me, not emphasized. I think and going by the number of google hits for the phrase, we should go with "is a non-viral license".

**Comment by mara004** [comment]
> ReadTheDocs in particular can be very fragile. And it's still not rendering bullet points, which has been an open issue with them for 2 years now. Anyway, my frustrations and rants aside...

I agree and share the frustration (see also #203).
The environment in RTD is somewhat difficult to control, too (e.g. predefined `git checkout --force` causes a detached head state).

I wonder if it would be an option to switch to GH pages, but last time I didn't figure out how to maintain multiple versions with the deploy-pages workflow...
