### ISSUE TITLE
Bad link

### ISSUE THREAD

**Issue by SteDew** [pikepdf/pikepdf#496]
URL for "PDF 1.7" should be 
https://opensource.adobe.com/dc-acrobat-sdk-docs/standards/pdfstandards/pdf/PDF32000_2008.pdf
I think.

https://github.com/pikepdf/pikepdf/blame/13fc81e8ef8228831186402986eb8e779bc2a8af/docs/references/resources.rst#L6

**Comment by jbarlow83** [comment]
I believe you're looking at an old version - the current version has the same URL you gave.
Thanks for contributing anyway - always appreciated :+1:
