### ISSUE TITLE
test_stack_depth fails on Python 3.12

### ISSUE THREAD

**Issue by QuLogic** [pikepdf/pikepdf#502]
I'm not sure if that's the exact cause, but the test does not pass:
```pytb
_______________________________ test_stack_depth _______________________________
[gw0] linux -- Python 3.12.0 /usr/bin/python3

    @skip_if_pypy
    def test_stack_depth():
        a = [42]
        for _ in range(100):
            a = [a]
        rlimit = sys.getrecursionlimit()
        try:
            sys.setrecursionlimit(100)
>           with pytest.raises(RecursionError):
E           Failed: DID NOT RAISE <class 'RecursionError'>

tests/test_object.py:139: Failed
```

**Comment by QuLogic** [comment]
Checked with Python 3.11 on F38, and the test does pass, so it seems like Python version is probably related.

**Comment by jbarlow83** [comment]
As I understand it this failure can be ignored by any Python 3.12 test, cf: https://github.com/python/cpython/issues/105003

I will mark as "xfail" for Python 3.12.

**Comment by jbarlow83** [comment]
v8.2.3 marks this test as xfail on 3.12.
