### ISSUE TITLE
PDF image extraction error: Not sure how to handle PDF image of this type

### ISSUE THREAD

**Issue by davidress-ILW** [pikepdf/pikepdf#512]
Using 8.3.1 of pikepdf in a clean Python 3.10 environment.
I am trying to extract images from a new PDF text book I purchased this year.
Images with a colorspace of '/DeviceRGB' are extracted fine.
Images with a color space of '/CalRGB' throw a NotImplementedError.

For the images in question,
colorspace = /CalRGB
is_device_n = False
is_separation = False
indexed = False

Given the above, the exception noted is triggered.

Thus, will there be support for this image type in the future? 
In the meantime, does anyone know a work around?

**Comment by jbarlow83** [comment]
You can override the CalRGB by forcing it to DeviceRGB. It may lose color fidelity but you'll get the image out. 

I'd have to check how well document CalRGB is to see if extracting properly is feasible.

**Comment by davidress-ILW** [comment]
@jbarlow83 - thank you for the quick response!

Regarding "forcing it to DeviceRGB", I tried the following but it did not work, ie, the colorspace is still not DeviceRGB when calling image.extract_to():

`if image.colorspace == '/CalRGB':
    image._colorspace = '/DeviceRGB'`

Is there another way to force the colorspace to DeviceRGB?

**Comment by jbarlow83** [comment]
You would need to set `image.obj.ColorSpace = Name.DeviceRGB`, to alter the data that the image object wraps around.

**Comment by jbarlow83** [comment]
Closed since stale
