### ISSUE TITLE
Mypy implicit reexport

### ISSUE THREAD

**Issue by jon-torodash** [pikepdf/pikepdf#522]
Using the import `from pikepdf import Pdf`, I get:

`"pikepdf" does not explicitly export attribute "Pdf"; implicit reexport disabled`

The problem goes away when using the substituting with the undesirable pathing through the "hidden" `_qpdf` module, e.g. `from pikepdf._qpdf import Pdf`

I'm not at all familiar with the source code here, but the imports at the bottom of `_qpdf.__init__.py` don't strike me as required.

**Comment by jbarlow83** [comment]
The module named _qpdf was removed many releases ago. Please check what happens with current versions of pikepdf, Python and mypy. 

I'll also need some information about what you're trying to accomplish - sounds like we have a XY problem.

**Comment by jbarlow83** [comment]
Closing as related to an old version & no new info
