### ISSUE TITLE
The password param in method ‘open’

### ISSUE THREAD

**Issue by Twinkle-Wong** [pikepdf/pikepdf#525]
How does the password parameter in the open method work? I encountered difficulties in implementing PDF known key decryption in Java

**Comment by jbarlow83** [comment]
The source code password handling is mainly in QPDF.
https://github.com/qpdf/qpdf/blob/b352791a07a5488e6f1f67220ddce147d20aa26a/libqpdf/QPDF_encryption.cc#L534

It's fairly complex and there are issues in older versions of the PDF spec with the encoding expectations of passwords being unclear.
