### ISSUE TITLE
How to access OCR-data?

### ISSUE THREAD

**Issue by klartext** [pikepdf/pikepdf#532]
I would like to read OCR data from a pdf.
If possible, the text and it's positioning on the page(s).
Is this possible with pikepdf, and if so, how?

**Comment by jbarlow83** [comment]
pdfplumber and pdfminer.six have the off-the-shelf solutions for this. pikepdf is more useful when you want to edit a pdf, which those tools don't do.

There is no general solution to distinguishing OCR text from ordinary text if a document contains both.
