### ISSUE TITLE
Import/Export annotations to FDF/JSON format

### ISSUE THREAD

**Issue by mah-emad** [pikepdf/pikepdf#533]
Support importing/exporting annotations to FDF format or json format.

**Comment by jbarlow83** [comment]
Using pikepdf's tools you can retrieve these objects from a PDF and replace them. The PDF reference manual, which is freely available, describes where these objects are stored in a PDF if present.

pikepdf does not have tools to modify form data in a way that complies with the expectations of those formats. It's unlikely they will be added without corporation sponsorship or a pull request implementing it.
