### ISSUE TITLE
Accessibility Settings Issue

### ISSUE THREAD

**Issue by Anderu123** [pikepdf/pikepdf#535]
![image](https://github.com/pikepdf/pikepdf/assets/35473449/ca21c087-5398-4409-a606-363e1e352b6c)

Hi there, not sure is it only me but I am having this issue, although I have set my Permissions(accessibility=False) still this section is "Allowed". Others are working as expected.

**Comment by jbarlow83** [comment]
Modern PDF readers ignore any attempt to block accessibility access to documents. From the PDF 2.0 specification:

![image](https://github.com/pikepdf/pikepdf/assets/1825843/5f9f748e-27a9-4d9e-8028-749bb126e252)

I will update the documentation to clarify that blocking accessibility is no longer supported by modern PDF readers.
