### ISSUE TITLE
[Feature request] JBIG2Decode

### ISSUE THREAD

**Issue by rossella86** [pikepdf/pikepdf#54]
Hi, 
first of all, thank you for your work!
I'm having some troubles in extracting images from a pdf (scanned by Google), and I suppose the problem arises because of '/Filter': '/JBIG2Decode'
I would be really grateful if you could add this feature, or if you can suggest me how to solve this error. 

Thanks!

The XObject appears like that: 

{'/BitsPerComponent': 1,
 '/ColorSpace': '/DeviceGray',
 '/Filter': '/JBIG2Decode',
 '/Height': 204,
 '/Mask': IndirectObject(4385, 0),
 '/Subtype': '/Image',
 '/Type': '/XObject',
 '/Width': 1034}

And this is the error I get when calling the "as_pil_image()" function:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pikepdf/models/image.py", line 539, in as_pil_image
    im = self._extract_transcoded()
  File "/usr/local/lib/python3.7/site-packages/pikepdf/models/image.py", line 419, in _extract_transcoded
    data = self.read_bytes()
  File "/usr/local/lib/python3.7/site-packages/pikepdf/models/image.py", line 517, in read_bytes
    return self.obj.read_bytes()
pikepdf._qpdf.PdfError: /Users/aversa/PycharmProjects/C08/pdf_folder/128_Martin_1660_anno.pdf (offset 44470964): getStreamData called on unfilterable stream

**Comment by jbarlow83** [comment]
The image is encoded with JBIG2, a sophisticated image for monochrome images. https://jbig2dec.com/

You can use `Image.extract_to()` to extract the JBIG2 image as a JBIG2 file and then the third party program `jbig2dec` to decode it. 

There are two types of JBIG2 images, self contained ones like the above and those with an entry that looks something like: `{'/DecodeParms': {'/JBIG2Globals': ...}}` If there is a JBIG2 entry, this is a data structure shared by multiple images for further improvement compression. You'd have to extract the JBIG2 globals object with `Object.read_bytes()`, save it, and offer it to `jbig2dec` as well.

It would be ideal to have JBIG2 built-in, but I don't know of any decoders that are available under a compatible license. Clearly, the error message should be more helpful than it currently is.

**Comment by jbarlow83** [comment]
pdfminer.six has a JBIG2 decoder now, could borrow

**Comment by jbarlow83** [comment]
Added JBIG2 a few releases ago....
