### ISSUE TITLE
Traverse PDF layers and classes

### ISSUE THREAD

**Issue by ChavdarVojvoda** [pikepdf/pikepdf#543]
I have architecture plans which in which different data is stored in different layers and classes and would like to fetch the data only from a particular class.
As there are a limited amount of examples for the library, I was wondering if there is a way to do this  without manually converting the data in a traversable form i.e. dictionary.

**Comment by jbarlow83** [comment]
PDF is a very complex format. In this case, the PDFs you have are being used to store data custom application specific data. There is a sort of standard way to do layers. I don't know what "classes" would be in PDF internal data structures - there are many ways one could express that. 

If you're familiar with HTML, it's sort of like looking at a block of text and wondering how it got its particular formatting -  maybe there are some CSS rules that select it, maybe Javascript dynamically modified the rules, maybe there's inline CSS, maybe the text is rendered with SVG or Canvas. Maybe it's an iframe. Without getting into the details of how a specific HTML application works, you can't answer that question. And a different application that looks identical to the user may have an entirely different technical implementation.

You could use a tool like iText RUPS to inspect the structure of the PDF, and the PDF reference manual, and see if you can find where the data you want to access is located in the PDF. Then pikepdf gives you an efficient way to retrieve that information.
