### ISSUE TITLE
How to replace the value of an Object mapped to a variable

### ISSUE THREAD

**Issue by drstuggels** [pikepdf/pikepdf#547]
Hello!

If I define a variable like this
```python
names = pdf.Root.StructTreeRoot.IDTree.Kids[0]["/Names"] # names will be pikepdf.Array
```
How do I replace its value?
```python
names = pikepdf.Array([1,2,3]) # doesn't work. It just rebinds the variable.
```
Only thing that works is
```python
pdf.Root.StructTreeRoot.IDTree.Kids[0]["/Names"] = pikepdf.Array([1,2,3])
```
which is fine, but not clean.

Binding the parent object to a variable becomes confusing.
```python
kids = pdf.Root.StructTreeRoot.IDTree.Kids[0]
kids["/Names"] = pikepdf.Array([1,2,3])
```

I love the library otherwise! Thanks

**Comment by jbarlow83** [comment]
That's a name tree - use `pikepdf.NameTree(pdf.Root.StructTreeRoot.IDTree)` to access it through a Python mapping.
