### ISSUE TITLE
Unable to build on macOS with qpdf 9.0.0

### ISSUE THREAD

**Issue by 404NetworkError** [pikepdf/pikepdf#55]
I ran into a unusual problem when attempting to update `qpdf` to version 9.0.0 for [Homebrew](Homebrew/homebrew-core#43736). Since `ocrmypdf` in the Homebrew repo requires `qpdf`, the test case for `ocrmypdf` ran. It produced an [linking error message](https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/47554/version=mojave/testReport/junit/brew-test-bot/mojave/test_ocrmypdf) stating the compiled `qpdf` library for `pikepdf` could not be loaded. (It was attempting to reference version 21 of `libqpdf` instead of version 26.)

In an attempt to resolve the problem, I bumped the revision to `ocrmypdf` and updated it's python dependencies, which included `pikepdf` from v1.6.1 to v1.6.2. Unfortunately, [Homebrew's CI](https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/47567/version=mojave/console) ran into a compiler error in `ocrmypdf` caused by `pikepdf`. I have duplicated the error when attempting to build `pikepdf` locally using `qpdf` 9.0.0 installed from the Homebrew PR listed above.

I'm not sure how to go about attempting to fix the compiling issue with `pikepdf`. Any help would be appreciated.

---

<details>
<summary>My local setup</summary>
<br>
<pre>
$ pipdeptree
defusedxml==0.6.0
lxml==4.4.1
pipdeptree==0.13.2
  - pip [required: >=6.0.0, installed: 19.2.3]
pybind11==2.3.0
setuptools==41.2.0
wheel==0.33.6
$
$ qpdf --version
qpdf version 9.0.0
Run qpdf --copyright to see copyright and license information.
$
$ ls -al /usr/local/opt/qpdf/lib/
total 3604
-r--r--r--  1 user admin 1111728 Sep  1 08:36 libqpdf.26.dylib
-r--r--r--  1 user admin 2568392 Sep  1 08:36 libqpdf.a
lrwxr-xr-x  1 user admin      16 Sep  1 08:36 libqpdf.dylib -> libqpdf.26.dylib
drwxr-xr-x  3 user admin     102 Sep  1 08:36 pkgconfig
</pre>
</details>
<details>
<summary>Error message</summary>
<br>
<pre>
clang ... -c src/qpdf/object.cpp ...
  src/qpdf/object.cpp:810:10: error: no matching member function for call to 'def'
          .def("handle_object", &QPDFObjectHandle::ParserCallbacks::handleObject)
          ~^~~
</pre>
</details>
<details>
<summary>Full build log</summary>
<br>
<pre>
$ git clone https://github.com/pikepdf/pikepdf.git
$ cd pikepdf
$ git checkout v1.6.2
$ pip install .
Processing /Users/user/work/pikepdf
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
    Preparing wheel metadata: started
    Preparing wheel metadata: finished with status 'done'
Requirement already satisfied: lxml>=4.0 in /Users/user/work/ve/lib/python3.7/site-packages (from pikepdf==1.6.2) (4.4.1)
Building wheels for collected packages: pikepdf
  Building wheel for pikepdf (PEP 517): started
  Building wheel for pikepdf (PEP 517): finished with status 'error'
  ERROR: Command errored out with exit status 1:
   command: /Users/user/work/ve/bin/python3.7 /Users/user/work/ve/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py build_wheel /var/folders/kj/4283qf996816pvl74ls38j2r0000gn/T/tmpd4kqxxdu
       cwd: /private/var/folders/kj/4283qf996816pvl74ls38j2r0000gn/T/pip-req-build-d22uvpm8
  Complete output (55 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.12-x86_64-3.7
  creating build/lib.macosx-10.12-x86_64-3.7/pikepdf
  copying src/pikepdf/__init__.py -> build/lib.macosx-10.12-x86_64-3.7/pikepdf
  copying src/pikepdf/_cpphelpers.py -> build/lib.macosx-10.12-x86_64-3.7/pikepdf
  copying src/pikepdf/_methods.py -> build/lib.macosx-10.12-x86_64-3.7/pikepdf
  copying src/pikepdf/_version.py -> build/lib.macosx-10.12-x86_64-3.7/pikepdf
  copying src/pikepdf/codec.py -> build/lib.macosx-10.12-x86_64-3.7/pikepdf
  copying src/pikepdf/objects.py -> build/lib.macosx-10.12-x86_64-3.7/pikepdf
  creating build/lib.macosx-10.12-x86_64-3.7/pikepdf/models
  copying src/pikepdf/models/__init__.py -> build/lib.macosx-10.12-x86_64-3.7/pikepdf/models
  copying src/pikepdf/models/encryption.py -> build/lib.macosx-10.12-x86_64-3.7/pikepdf/models
  copying src/pikepdf/models/image.py -> build/lib.macosx-10.12-x86_64-3.7/pikepdf/models
  copying src/pikepdf/models/matrix.py -> build/lib.macosx-10.12-x86_64-3.7/pikepdf/models
  copying src/pikepdf/models/metadata.py -> build/lib.macosx-10.12-x86_64-3.7/pikepdf/models
  running build_ext
  creating var
  creating var/folders
  creating var/folders/kj
  creating var/folders/kj/4283qf996816pvl74ls38j2r0000gn
  creating var/folders/kj/4283qf996816pvl74ls38j2r0000gn/T
  clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -I/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/include/python3.7m -c /var/folders/kj/4283qf996816pvl74ls38j2r0000gn/T/tmpctz05xfq.cpp -o var/folders/kj/4283qf996816pvl74ls38j2r0000gn/T/tmpctz05xfq.o -std=c++14
  clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -I/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/include/python3.7m -c /var/folders/kj/4283qf996816pvl74ls38j2r0000gn/T/tmpahrs8nxu.cpp -o var/folders/kj/4283qf996816pvl74ls38j2r0000gn/T/tmpahrs8nxu.o -fvisibility=hidden
  building 'pikepdf._qpdf' extension
  creating build/temp.macosx-10.12-x86_64-3.7
  creating build/temp.macosx-10.12-x86_64-3.7/src
  creating build/temp.macosx-10.12-x86_64-3.7/src/qpdf
  clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -I/Users/user/work/ve/bin/../include/site/python3.7 -I/Users/user/work/ve/bin/../include/site/python3.7 -I/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/include/python3.7m -c src/qpdf/annotation.cpp -o build/temp.macosx-10.12-x86_64-3.7/src/qpdf/annotation.o -stdlib=libc++ -mmacosx-version-min=10.7 -DVERSION_INFO="1.6.2" -std=c++14 -fvisibility=hidden
  clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -I/Users/user/work/ve/bin/../include/site/python3.7 -I/Users/user/work/ve/bin/../include/site/python3.7 -I/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/include/python3.7m -c src/qpdf/object.cpp -o build/temp.macosx-10.12-x86_64-3.7/src/qpdf/object.o -stdlib=libc++ -mmacosx-version-min=10.7 -DVERSION_INFO="1.6.2" -std=c++14 -fvisibility=hidden
  src/qpdf/object.cpp:810:10: error: no matching member function for call to 'def'
          .def("handle_object", &QPDFObjectHandle::ParserCallbacks::handleObject)
          ~^~~
  /Users/user/work/ve/bin/../include/site/python3.7/pybind11/pybind11.h:1111:13: note: candidate template ignored: couldn't infer template argument 'Func'
      class_ &def(const char *name_, Func&& f, const Extra&... extra) {
              ^
  /Users/user/work/ve/bin/../include/site/python3.7/pybind11/pybind11.h:1129:13: note: candidate template ignored: could not match 'op_<id, ot, type-parameter-0-2, type-parameter-0-3>' against 'char const[14]'
      class_ &def(const detail::op_<id, ot, L, R> &op, const Extra&... extra) {
              ^
  /Users/user/work/ve/bin/../include/site/python3.7/pybind11/pybind11.h:1141:13: note: candidate template ignored: could not match 'constructor<type-parameter-0-0...>' against 'char const[14]'
      class_ &def(const detail::initimpl::constructor<Args...> &init, const Extra&... extra) {
              ^
  /Users/user/work/ve/bin/../include/site/python3.7/pybind11/pybind11.h:1147:13: note: candidate template ignored: could not match 'alias_constructor<type-parameter-0-0...>' against 'char const[14]'
      class_ &def(const detail::initimpl::alias_constructor<Args...> &init, const Extra&... extra) {
              ^
  /Users/user/work/ve/bin/../include/site/python3.7/pybind11/pybind11.h:1153:13: note: candidate template ignored: could not match 'factory<type-parameter-0-0...>' against 'char const[14]'
      class_ &def(detail::initimpl::factory<Args...> &&init, const Extra&... extra) {
              ^
  /Users/user/work/ve/bin/../include/site/python3.7/pybind11/pybind11.h:1159:13: note: candidate template ignored: could not match 'pickle_factory<type-parameter-0-0...>' against 'char const[14]'
      class_ &def(detail::initimpl::pickle_factory<Args...> &&pf, const Extra &...extra) {
              ^
  1 error generated.
  error: command 'clang' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for pikepdf
  Running setup.py clean for pikepdf
Failed to build pikepdf
ERROR: Could not build wheels for pikepdf which use PEP 517 and cannot be installed directly
</pre>
</details>

**Comment by jbarlow83** [comment]
Qpdf 9 probably has breaking changes. I didn't know it was released yet.
Shouldn't take long to fix.

**Comment by jbarlow83** [comment]
Fixed in v1.6.3. qpdf introduced a new overloaded method for `QPDFObjectHandle::ParserCallbacks::handleObject` which caused pybind11's introspection to fail as that name no longer referred to a unique method.

It should do the job to rebuild ocrmypdf 9.0.1 with pikepdf 1.6.3.

**Comment by 404NetworkError** [comment]
Thanks for the update. I will try a rebuild of `ocrmypdf` & report back.

**Comment by 404NetworkError** [comment]
Everything built perfectly. Again, thank you for the update.
