### ISSUE TITLE
pikepdf, libjpeg, l

### ISSUE THREAD

**Issue by datatalking** [pikepdf/pikepdf#550]
When I go to pip install the package it says it cant... module not found, which is weird since I'm trying '!pip3 install pikepdf' and says 'requirement already satisfied'

When I do that in the jupyter notebook I get the following error

```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
File ~/opt/anaconda3/envs/BookDatabase/lib/python3.8/site-packages/pikepdf/__init__.py:13
     12 try:
---> 13     from . import _core
     14 except ImportError as _e:  # pragma: no cover

ImportError: dlopen(/Users/{user_name}/opt/anaconda3/envs/BookDatabase/lib/python3.8/site-packages/pikepdf/_core.cpython-38-darwin.so, 2): Symbol not found: __ZNKSt3__115basic_stringbufIcNS_11char_traitsIcEENS_9allocatorIcEEE3strEv
  Referenced from: /Users/{user_name}/opt/anaconda3/envs/BookDatabase/lib/python3.8/site-packages/pikepdf/.dylibs/libqpdf.29.6.4.dylib (which was built for Mac OS X 12.0)
  Expected in: /usr/lib/libc++.1.dylib


The above exception was the direct cause of the following exception:

ImportError                               Traceback (most recent call last)
Cell In[17], line 2
      1 get_ipython().system('pip3 install pikepdf')
----> 2 import pikepdf

File ~/opt/anaconda3/envs/BookDatabase/lib/python3.8/site-packages/pikepdf/__init__.py:16
     14 except ImportError as _e:  # pragma: no cover
     15     _msg = "pikepdf's extension library failed to import"
---> 16     raise ImportError(_msg) from _e
     18 from ._core import (
     19     AccessMode,
     20     Annotation,
   (...)
     42     TokenType,
     43 )
     44 from ._exceptions import DependencyError

ImportError: pikepdf's extension library failed to import
```

So then i try to install it via conda and make some progress but then not sure how pikepdf would access the list of pdf files I've got in a folder.

Which made me think does this mean pikepdf works different with anaconda or why conda works but the pip and brew installs don't work on bigsur or catalina?

Then I try 'conda install -c conda-forge pikepdf' and it kindof works but now I'm not sure how to  parse the list of pdf's I have that are dirty might be causing issues with pikepdf?

<img width="606" alt="Screen Shot 2023-12-27 at 10 07 29 AM" src="https://github.com/pikepdf/pikepdf/assets/11813209/2cd71edc-66d2-4284-94d0-276d28cfc21c">

**Comment by jbarlow83** [comment]
conda has its own packaging ecosystem, and I have no idea how any of it works. Its version of pikepdf is quite old (last updated August 2022). Catalina and Big Sur are no longer supported by Apple or Homebrew, which is likely the main reason you're seeing issues.

Consider switching to venv+pip or hatch to manage your environments and dependencies, which get the latest version from PyPI as soon I release it. Alternately, you could open an issue with conda and ask them to update pikepdf's packaging. If you can, I also recommend switching to Python 3.11, since 3.8 is just a few months from end of life.
