### ISSUE TITLE
Segmentation fault when using with PyTorch

### ISSUE THREAD

**Issue by samkit-jain** [pikepdf/pikepdf#56]
I installed `pikepdf` using `pip` and `pytorch-cpu` using `conda`. Importing both the libraries results in a segmentation fault.

```
>>> import torch
>>> import pikepdf
Segmentation fault (core dumped)
```
The order doesn't matter
```
>>> import pikepdf
>>> import torch
Segmentation fault (core dumped)
```

Using Python 3.6.8 on Ubuntu 18.04

Raised an issue on PyTorch GitHub too at https://github.com/pytorch/pytorch/issues/26092

**Comment by jbarlow83** [comment]
It's possible that some recent fixes like commit 5394b7855eb or 855088f5 fixed this.
