### ISSUE TITLE
Re-enable 32-bit wheels on Windows

### ISSUE THREAD

**Issue by sekrause** [pikepdf/pikepdf#563]
In version 8.0 pikepdf dropped support 32-bit wheels on Windows with the following reason:

> Since Pillow (Python imaging library), a major dependency, has dropped support for 32-bit wheels on Windows and Linux, we have done the same.

After much outcry Pillow has since re-enabled 32-bit wheels on Windows in version 10.0.2: https://github.com/python-pillow/Pillow/issues/7443#issuecomment-1834902039

I would be nice if pikepdf also re-enables them.

As for the reason why this is actually needed: While it's true that 32-bit Windows is on the way out ([as commented here](https://github.com/pikepdf/pikepdf/issues/431#issuecomment-1368107448)), 32-bit Python on 64-bit Windows is not. It's often required to run a 32-bit Python even on a modern 64-bit Windows system just to interface with old, pure 32-bit COM libraries or ODBC drivers. See also these comments by a Python core developer:

- https://discuss.python.org/t/consider-downgrading-windows-32-bit-from-tier-1-to-tier-2-or-tier-3-in-python-3-13/33719/9
- https://discuss.python.org/t/consider-downgrading-windows-32-bit-from-tier-1-to-tier-2-or-tier-3-in-python-3-13/33719/21

32-bit Linux wheels are probably not needed anymore.

**Comment by jbarlow83** [comment]
Python and Pillow are reasonably well funded projects - they can afford to support legacy platforms.

 If a sponsor were willing to fund it, that would help build a case for restoring support.

**Comment by jbarlow83** [comment]
This issue won't be addressed unless it is sponsored.
