### ISSUE TITLE
The pdf doc has been linearized,  but the property "fast web view"  still is “no"

### ISSUE THREAD

**Issue by hytTony** [pikepdf/pikepdf#566]
I open a pdf doc, then save it with "linearize=True",  like this:
`import pikepdf

pdf = pikepdf.open("E:\work\MedXview\RE_ 回复：Re_ question\Doc1.pdf")
print(pdf.is_linearized)
pdf.save("E:\work\MedXview\RE_ 回复：Re_ question\Doc1_out.pdf", linearize=True)
print("OK")`

Open the saved Doc1_out.pdf and print(pdf.is_linearized), it is true. But, i open it on browser, the property "fast web view" still is "no".
![Weixin Photo Editor_20240219115857](https://github.com/pikepdf/pikepdf/assets/89056911/fc139461-cb67-4a76-845e-6016cacfa86d)

This is right?  or how to correct it?

**Comment by jbarlow83** [comment]
Yes, Acrobat doesn't show it as having that status. What "fast web view" actually looks for is undocumented. The PDF is linearized when the flag is set which is at least the key optimization of fast web view.
