### ISSUE TITLE
[Feature request] add/modify bookmark

### ISSUE THREAD

**Issue by OnlyFor** [pikepdf/pikepdf#57]
Amazing work !
Why not consider adding and editing bookmarks of pages (like PyPDF2)，
thanks !

**Comment by jbarlow83** [comment]
You already can manipulate the bookmarks data structure manually. Yes, I'd like to add this. Bookmarks have a lot of functionality associated.

**Comment by OnlyFor** [comment]
Finally i got what I wanted by parsing and imitating existing cases.

for i in enumerate(ordered_bookmarks):
    child = pikepdf.Dictionary({
        "/A": pikepdf.Dictionary({
            "/D": pikepdf.Array([
                pdf_writer.root["/Pages"]["/Kids"][i[0]],
                pikepdf.Name("/Fit")
            ]),
            "/S": pikepdf.Name("/GoTo")
        }),
        "/Title": pikepdf.String(i[1]),
    })
    if "/First" not in outlines:
        outlines["/First"] = child
    else:
        outlines["/Last"]["/Next"] = child
    outlines["/Last"] = child
    outlines["/Count"] += 1

**Comment by OnlyFor** [comment]
Finally i got what I wanted by parsing and imitating existing cases.

`
for i in enumerate(ordered_bookmarks):
    child = pikepdf.Dictionary({
        "/A": pikepdf.Dictionary({
            "/D": pikepdf.Array([
                pdf_writer.root["/Pages"]["/Kids"][i[0]],
                pikepdf.Name("/Fit")
            ]),
            "/S": pikepdf.Name("/GoTo")
        }),
        "/Title": pikepdf.String(i[1]),
    })
    if "/First" not in outlines:
        outlines["/First"] = child
    else:
        outlines["/Last"]["/Next"] = child
    outlines["/Last"] = child
    outlines["/Count"] += 1
`

**Comment by cepm-nate** [comment]
@OnlyFor , what is the variable ```ordered_bookmarks``` you are enumerating?

My quest is to find the page numbers that specifically a named bookmark refers to. I'm from the javascript world, so still trying to wrap my mind around python's style.

Do you have any examples that show a list of the bookmarks + their properties (namely just "Title" and "Page")?

**Comment by jbarlow83** [comment]
Have a look at the PDF reference manual (ISO32000 2008) in section H.6 for a description of how the document outline works. In short it is a tree data structure and you have to decide how you want to traverse it. It's difficult to describe without diagrams. The reference manual is linked the pikepdf documentation.

**Comment by cepm-nate** [comment]
Thanks @jbarlow83 . I'll take a look.
