### ISSUE TITLE
Specific Image with CCITT group 4 cannot be detected and treated

### ISSUE THREAD

**Issue by Skaddd** [pikepdf/pikepdf#583]
I'm a having a hard time treating a Scanned PDF that seems to have two images but `my_pdf.images.items()` is detecting only one image. When looking in `/Resources` 2 two objects can be found, my guess would be that `Obj5`has no `ColorSpace` so is not detected as an image ?

The image object found produce a rather blank image, sadly i cannot show you the PDFs.
```
<pikepdf.Dictionary({
  "/ProcSet": [ "/PDF", "/Text", "/ImageB", "/ImageC", "/ImageI" ],
  "/XObject": {
    "/Obj4": pikepdf.Stream(owner=<...>, data=<...>, {
      "/BitsPerComponent": 8,
      "/ColorSpace": "/DeviceRGB",
      "/Filter": [ "/FlateDecode", "/DCTDecode" ],
      "/Height": 1753,
      "/Length": 24619,
      "/Subtype": "/Image",
      "/Type": "/XObject",
      "/Width": 1240
    }),
    "/Obj5": pikepdf.Stream(owner=<...>, data=<...>, {
      "/BitsPerComponent": 1,
      "/DecodeParms": {
        "/Columns": 2104,
        "/K": -1
      },
      "/Filter": "/CCITTFaxDecode",
      "/Height": 3088,
      "/ImageMask": True,
      "/Length": 66792,
      "/Subtype": "/Image",
      "/Type": "/XObject",
      "/Width": 2104
    })
  }
})>
```
`mypdf.check()`outputs an empty list.

The stream content also have instructions for drawing both images (with the `Do`operator)
```
Operands pikepdf._core._ObjectList([]), operator q
Operands pikepdf._core._ObjectList([Decimal('595.20'), 0, 0, Decimal('841.44'), Decimal('0.00'), Decimal('0.00')]), operator cm
Operands pikepdf._core._ObjectList([pikepdf.Name("/Obj4")]), operator Do
Operands pikepdf._core._ObjectList([]), operator Q
Operands pikepdf._core._ObjectList([]), operator q
Operands pikepdf._core._ObjectList([Decimal('0.071')]), operator g
Operands pikepdf._core._ObjectList([Decimal('512.64'), 0, 0, Decimal('740.16'), Decimal('69.12'), Decimal('25.44')]), operator cm
Operands pikepdf._core._ObjectList([pikepdf.Name("/Obj5")]), operator Do
Operands pikepdf._core._ObjectList([]), operator Q
```

I'm wondering if it's a malformed PDF even though the first image is extractable, or just an specific type of scanned PDF not handled yet.

Sorry in advance if i have missed an obvious thing.

**Comment by jbarlow83** [comment]
When there is an image mask (/ImageMask True) there should be no /ColorSpace. That's correct.

/Obj5 is drawn as a stencil mask - how it appears is dependent on the graphics state at the time it is drawn. It's not an ordinary image, so (I presume) qpdf doesn't present it with other .images. You can still extract the object by wrapping it into a PdfImage and extracting it manually.
