### ISSUE TITLE
Missing sdist for 9.0.0

### ISSUE THREAD

**Issue by mgorny** [pikepdf/pikepdf#585]
https://pypi.org/project/pikepdf/9.0.0/#files has only binary wheels, the source distribution is missing.

**Comment by federicobond** [comment]
I'm getting this error when attempting to install pikepdf==9.0.0 with `uv` on Python 3.12, probably related:

```
  × No solution found when resolving dependencies:
  ╰─▶ Because pikepdf==9.0.0 has no wheels are available with a matching
      Python ABI and you require pikepdf==9.0.0, we can conclude that the
      requirements are unsatisfiable.
```

**Comment by jbarlow83** [comment]
Fixed - the upload runner glitched out and didn't upload all wheels or sdists. Unfortunately incomplete updates still get published.

This is a known issue with PyPI that hopefully will be fixed one day in https://peps.python.org/pep-0694/

**Comment by mgorny** [comment]
Thanks!
