### ISSUE TITLE
OSS-Fuzz Integration

### ISSUE THREAD

**Issue by ennamarie19** [pikepdf/pikepdf#587]
My name is McKenna Dallmeyer and I would like to submit pikepdf to OSS-Fuzz.

If you are not familiar with the project, OSS-Fuzz is Google's platform for continuous fuzzing of Open Source Software.

In order to get the most out of this program, it would be greatly beneficial to be able to merge-in my fuzz harness and build scripts into the upstream repository and contribute bug fixes if they come up. Is this something that you would support me putting the effort into?

Thank you!

**Comment by jbarlow83** [comment]
Yes, I believe I can support this.

QPDF, the main library used to implement pikepdf, already does its own fuzz testing (I believe by its author, I don't know if it's done specifically using OSS-Fuzz).

**Comment by ennamarie19** [comment]
Wonderful! Thank you! Could you share an email address with me that I can include in my submission to OSS-Fuzz so that you are notified should any vulnerabilities be uncovered?

**Comment by jbarlow83** [comment]
james@purplerock.ca
