### ISSUE TITLE
Release for Python 3.8

### ISSUE THREAD

**Issue by impredicative** [pikepdf/pikepdf#59]
When possible, please build and release for Python 3.8 too 😊
It's currently preventing me from updating a project to Python 3.8.

**Comment by jbarlow83** [comment]
Done! - v1.6.5
Except on Windows, PyPI wheels are not available yet since the various CI providers have not updated to Py3.8

**Comment by jbarlow83** [comment]
pikepdf 1.6.5 works on py3.8, but no wheels are available as yet.
Blocked by https://github.com/joerick/cibuildwheel/pull/172

**Comment by jbarlow83** [comment]
Available now - 1.7.0 recommended

Requires upgrading to most recent version pip
