### ISSUE TITLE
fraud detection and document comparison

### ISSUE THREAD

**Issue by arad2022** [pikepdf/pikepdf#594]
I want to detect any changes in the pdf file. How can I do that?

In the first step, I have an original pdf file and the modified version, and I want to detect changes by comparing these two files.

It would be great if you can help me in this matter.

**Comment by jbarlow83** [comment]
This will depend on what level of change you want to detect. Depending how detailed you want to go, this could be very complex (as in a multiple person-year project) since there are a lot of ways one could introduce fraud with PDF.

If a document is digitally signed, that will detect if any tampering has occurred. pikepdf doesn't have an API to support checking signatures, but it provides the low level building blocks that could be used for this. In short, using the existing infrastructure for this. That's an improvement over encrypted PDFs - since if you have the password, it's easy to remove the encryption and create a modified encrypted document that looks the same. Using the existing infrastructure in this way is probably best.

**Comment by arad2022** [comment]
> This will depend on what level of change you want to detect. Depending how detailed you want to go, this could be very complex (as in a multiple person-year project) since there are a lot of ways one could introduce fraud with PDF.
> 
> If a document is digitally signed, that will detect if any tampering has occurred. pikepdf doesn't have an API to support checking signatures, but it provides the low level building blocks that could be used for this. In short, using the existing infrastructure for this. That's an improvement over encrypted PDFs - since if you have the password, it's easy to remove the encryption and create a modified encrypted document that looks the same. Using the existing infrastructure in this way is probably best.

Thanks for your response. It was hard for me to use pikepdf to compare two pdf files. Is there any method in this library to do that. I have two pdf file in this stage and one of them is original without encryption and another one is modified version. I need to compare them page by page and detect any change and find the exact location.  Can you help me in this matter?

**Comment by arad2022** [comment]
I saw all the objects in a page with below code but I couldn't understand anything from that and compare with other file


page1 = example.pages[0]
obj_page1 = page1.obj
print(obj_page1)

**Comment by jbarlow83** [comment]
What's your use case? Do you have something like a legal document and you want to see if someone tampered with the contract, and where?

**Comment by arad2022** [comment]
> What's your use case? Do you have something like a legal document and you want to see if someone tampered with the contract, and where?

Yes. I have Invoice Receipts and I want to detect any changes on them. In first step I have original and modified version but in the real world I don't have access to the original one. 
1. For my first use case how can I compare two pdf files and detect any tampered?
2. I have one pdf file and I want to detect any changes on that and then find out what is the change on the pdf to detect any fraud.

**Comment by jbarlow83** [comment]
Why can't you just do a binary comparison on the files? Is there some set of changes that you want to permit?

**Comment by arad2022** [comment]
What do you mean?
How can I detect the changes and location of them on the pdf files?
I don't want to check two pdf files are same or not only.

**Comment by jbarlow83** [comment]
Please download and review the PDF Reference Manual version 1.7. I think if you take some time to read it, you will develop an idea of how PDF works and what is actually involved in a structural comparison of the files. I think that will help you formulate a more specific problem, one I'd be able to answer. 

The first pass would be to render images of each page and compare the images for changes. But someone skilled with PDF could construct a PDF that would appear differently on different computers (by abusing font substitution), differently on screen versus printing (by adding special printer-only marks), or even differently by zoom level. A robust fraud detection solution for PDF is a very difficult task - would cost millions to implement and well beyond the capabilities of any open source software.

**Comment by arad2022** [comment]
> Please download and review the PDF Reference Manual version 1.7. I think if you take some time to read it, you will develop an idea of how PDF works and what is actually involved in a structural comparison of the files. I think that will help you formulate a more specific problem, one I'd be able to answer.
> 
> The first pass would be to render images of each page and compare the images for changes. But someone skilled with PDF could construct a PDF that would appear differently on different computers (by abusing font substitution), differently on screen versus printing (by adding special printer-only marks), or even differently by zoom level. A robust fraud detection solution for PDF is a very difficult task - would cost millions to implement and well beyond the capabilities of any open source software.

Please check this [tool ](https://www.qtrac.eu/diffpdf.html)for pdf comparison and also we have **compare file tool** in the Adobe Acrobat Pro DC which can compare pdf files and show differences. I need something like that. I want to use some open source libraries like pikepdf to do that. If you have any solution related to that let me know. Is it possible to do that by using this library?

**Comment by jbarlow83** [comment]
pikepdf has most of the components needed to build such a tool, but you'd still need several person-years of work (read: budget $1 million to get started) to develop an application like that. Please review the reference manual so you can see how much work is required and how many features would be required.

**Comment by arad2022** [comment]
> pikepdf has most of the components needed to build such a tool, but you'd still need several person-years of work (read: budget $1 million to get started) to develop an application like that. Please review the reference manual so you can see how much work is required and how many features would be required.

Thanks for your help
