### ISSUE TITLE
Typo in README

### ISSUE THREAD

**Issue by dantetemplar** [pikepdf/pikepdf#596]
There is typo ("graft" instead of "draft") in readme file

![изображение](https://github.com/user-attachments/assets/9eb81460-b1ec-42df-a0a5-7cdac554e83e)

**Comment by dantetemplar** [comment]
PR made

**Comment by jbarlow83** [comment]
Graft is correct here

**Comment by dantetemplar** [comment]
> Graft is correct here

Interesting ^^

Sorry for bothering then
