### ISSUE TITLE
Some Decimal numbers converting to (invalid) scientific notation

### ISSUE THREAD

**Issue by cfcurtis** [pikepdf/pikepdf#598]
I've encountered the occasional broken PDF when I parse/unparse a content stream, and I've finally narrowed it down to *some* numbers being converted to scientific notation. I'm using pikepdf v9.1.0 - please let me know if this is an upstream issue, but I think it might be related to the use of Python's `Decimal`.

Minimal reproducable example:

```python
import pikepdf
from decimal import Decimal

doc = pikepdf.Pdf.new()
doc.add_blank_page()

# Define a ridiculous transformation matrix
cm = (
    [
        Decimal(1.0000008),
        Decimal(-0.0000006),
        Decimal(0.0000006),
        Decimal(1.0000008),
        Decimal(-0.0000015),
        Decimal(-0.0000014),
    ],
    pikepdf.Operator("cm"),
)

# Draw a random rectangle just to have something to look at
rect = ([200, 400, 200, 200], pikepdf.Operator("re"))
commands = [cm, rect, ([], pikepdf.Operator("S"))]

# convert commands to bytes and write to document
bcontents = pikepdf.unparse_content_stream(commands)
doc.pages[0].Contents = doc.make_stream(bcontents)

doc.save("weirddoc.pdf", compress_streams=False)
```

Inspecting the byte string gives the following illegal values, and Adobe chokes on the resulting PDF:

```
b'1.00000080000000 -6.00000000000000E-7 6.00000000000000E-7 1.00000080000000 -0.00000150000000000000 -0.00000140000000000000 cm\n200 400 200 200 re\nS'
```

You might ask "why would you define such a silly transformation matrix?", to which I would reply "no idea, but this is a direct copy from one that I found in the wild".

The reason I think it's related to `Decimal` to string conversion is if I instead define the byte string directly, everything behaves as expected, i.e. setting `bcontents` to:

```python
bcontents = b'1.0000008 -0.0000006 0.0000006 1.0000008 -0.0000015 -0.0000014 cm\n200 400 200 200 re\nS'
```

**Comment by jbarlow83** [comment]
You can use pikepdf.Matrix to hold your matrix, and pikepdf.Matrix.encode() to ensure that matrices are handled/rendered properly.

However, it is still an issue that very small but nonzero numbers were being expressed in scientific notation. This should be fixed in v9.1.1.
