### ISSUE TITLE
Failing to open qpdf library on FreeBSD

### ISSUE THREAD

**Issue by opairdrop** [pikepdf/pikepdf#6]
```python3.6
Python 3.6.5 (default, Jun 23 2018, 01:15:38) 
[GCC 4.2.1 Compatible FreeBSD Clang 4.0.0 (tags/RELEASE_400/final 297347)] on freebsd11
Type "help", "copyright", "credits" or "license" for more information.
>>> from pikepdf import Pdf
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/pikepdf/__init__.py", line 12, in <module>
    from . import _qpdf
ImportError: /usr/local/lib/python3.6/site-packages/pikepdf/_qpdf.so: Undefined symbol "_ZN16QPDFObjectHandle12getDictAsMapEv"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/pikepdf/__init__.py", line 14, in <module>
    raise ImportError("pikepdf's extension library failed to import")
ImportError: pikepdf's extension library failed to import```

....

```qpdf --version
qpdf version 8.1.0
Run qpdf --copyright to see copyright and license information.```

**Comment by jbarlow83** [comment]
I have never tried it on a *BSD.

What is the output of

```
pip install --verbose pikepdf
```

or in the source directory

```
python setup.py build_ext --inplace
```

If you could point me to an appropriate virtualbox image similar to your
configuration and version I could try it out.

**Comment by jbarlow83** [comment]
Sure, I can look. May I ask what you're trying to accomplish - porting ocrmypdf?

**Comment by RNCTX** [comment]
Have you got an email or some other private service I can send an SSH key or password to?  Sorry I just got around to setting up a jail today.

**Comment by jbarlow83** [comment]
https://pgp.mit.edu/pks/lookup?op=get&search=0x4434EB74C4A35F7F

**Comment by RNCTX** [comment]
Further testing with Qpdf 8.2.x and higher:

There are more issues with Qpdf and the gcc that ships with FreeBSD (4.7 iirc) that are unresolved.  It core dumps when trying to split a multi-page document and crashes when trying to build a multi-page document as well.

So with all of that in mind, even if a whole OCRmyPDF toolchain were built with gcc on FreeBSD, it wouldn't be worth much without a working Qpdf binary to use.

Therefore, I think the only thing to do as I mentioned the other day is to wait until the port maintainer updates the FreeBSD ports repo to a newer version.  Until then, Qpdf 8.0 and OCRmyPDF 6.2.3 are the latest stable versions usable on FreeBSD.

**Comment by WillemJansen** [comment]
Encoutered similar issue on Raspbian. Solution
- Compile qpdf from source & install
```
./configure CFLAGS=-std=c11 CPPFLAGS=-std=c++14
make
sudo make install
```

- Compile & install python 3.7 from source (./configure command as above), as not available for raspbian

- Clone pikepdf repository & buid, ensure you link in the /usr/local/lib directory!
```
cd pikepdf
CFLAGS=-std=c11 CPPFLAGS=-std=c++14 sudo pip3.7 -vvv install --global-option=build_ext --global-option="-I/usr/local/include/" --global-option="-L/usr/local/lib"  .
```

- only then clone ocrmypdf from git and install
```
cd OCRmypd
CFLAGS=-std=c11 CPPFLAGS=-std=c++14 sudo pip3.7 -vvv install --global-option=build_ext --global-option="-I/usr/local/include/" --global-option="-L/usr/local/lib"  .
```
on raspbian, this enabled g++ to resolve the previously undefined symbol. 

Hope it helps!

**Comment by jbarlow83** [comment]
Wow, sounds like you went to a lot of trouble to get that working.

Did you by chance run into an issue that sounds like:
https://github.com/qpdf/qpdf/issues/281
In particular I'd be interesting in knowing if the problematic symbol was related to QPDFExc.

Also, I assume you went through this because you wanted the latest version, but just in case you weren't aware, Raspbian testing has ocrmypdf 8.0.1: https://repology.org/metapackage/ocrmypdf/versions. Raspbian stable has a much older version.

**Comment by RNCTX** [comment]
FreeBSD has bumped to Qpdf 8.2.1 and seems to have addressed these compiler issues, going by the version notes, which may be of help.

https://svnweb.freebsd.org/ports?view=revision&revision=487272
