### ISSUE TITLE
Python library pikepdf not allowing duplicate pages to be inserted in a pdf

### ISSUE THREAD

**Issue by a-kaly** [pikepdf/pikepdf#60]
With a given single page input pdf, I tried to create a pdf with two copies of the first page making it a new two page pdf document. I received the following error:
**PdfError: empty PDF (page 1 (numbered from zero): object 3 0): duplicate page reference found; this would cause loss of data**

Can anyone help with this issue? Thanks!

**Comment by jbarlow83** [comment]
Can you provide the code please?

**Comment by jbarlow83** [comment]
Like this:

```python
pdf.pages.append(pdf.pages[0])  # duplicate page 1 into page 1 and 2
pdf.save(outfile)
```

or even

```python
    def _repeat_page(pdf, page, count):
        print(f'Duplicating page {page} - {count} times')

        for dup in range(count):
            pdf.pages.append(pdf.pages[page])

        print(f'Added page {page} to output document')
        return pdf
```

You don't need to worry about keeping `pdf_in` and `pdf_out` separate. `pikepdf.Pdf` is an in-memory object you can edit as much as you like; it will not change the source file. Only when you use `.save()` will changes be persisted.

**Comment by a-kaly** [comment]
Thank you for your reply.
I am keeping pdf_in and pdf_out separately since pdf_in is a 20 page document and pdf_out is new one I am writing to. I want to be able to attach the duplicate pages in order, say for example - first copy the first page of pdf_in to pdf_out then second page duplicate it and add 2 copies to pdf_out (and continue with other pages) rather than appending to pdf_in which would append at the end of 20 pages. 
When I am trying to append to pdf_out (which is basically pikepdf.Pdf.new()) using pdf_out.pages.append(pdf_in.pages[page]), I get the above error hence, I am creating a new pdf again inside the method with that page and appending it. 

How do I work it out in this scenario?

**Comment by a-kaly** [comment]
def write_pdf(in_file, conf):
    result = []

    logger.info('Reading document')
    with io.BytesIO(in_file) as stream_in:
        pdf_in = PDF.open(stream_in)

        logger.info('Initiating process for all destinations')
        for config in conf.config:
            pdf_out = PDF.new()

            processed_pages = []
            logger.info(f'Getting list of pages for a destination {config.pages}')
            for page_number in config.pages:
                if page_number in processed_pages:
                    continue

                logger.info(f'Getting page {page_number}')
                page = pdf_in.pages[page_number]

                logger.info('Checking for page duplicates')
                num_dups = config.pages.count(page_number)

                if num_dups > 1:
                    pdf_out = _repeat_page(pdf_in, page_number, num_dups, pdf_out)
                    processed_pages.append(page_number)
                else:
                    logger.info(f'Adding page {page_number} to output document')
                    pdf_out.pages.append(page)

            logger.info('Building output document')
            with io.BytesIO() as stream_out:
                pdf_out.save(stream_out)
                stream_out.seek(0)
                logger.info('Inititating upload of processed document')
                result_out = put_destination(config, stream_out)
                result.append(result_out)

        logger.info('Processed successfully for all destinations')
        return result

**Comment by jbarlow83** [comment]
In the current version you can use this line

```python
pdf_out.pages.append(pdf_out.copy_foreign(pdf_in.pages[0]))
```

That should work in the current release.

Explanation if you're interested - this is as much for me as for you when I decide to address this, because you may not necessarily care about the internal data model and things happening inside the C++ library:

`copy_foreign` copies the page and all associated data from `pdf_in` to `pdf_out`, but leaves it "floating in space" within the document. Then the `.append` connects it to the rest of the document.

Without `copy_foreign`, we do an implicit copy foreign, but it seems that qpdf notices that the object already exists in the current target Pdf so it returns that, which violates a constraint that pages within a PDF can't be multiply-referenced (each page must have its own object number; duplicate pages must be shallow copies of each other).

In a future release I will look into doing this happen automatically in the general. I'm a little unsure whether to do that, because adding a duplicate page could also be a bug.

**Comment by a-kaly** [comment]
Thank you very much for the above explanation, that worked perfectly.

**Comment by dreua** [comment]
Is there any penalty in using explicit copy_foreign all the time? In my use case we don't know which pages are duplicates and which aren't, but we should be able to find out if it's worth anything.

**Comment by mara004** [comment]
@dreua I think the docs outline the penalty of copy_foreign is that it might be more costly, since it copies recursively: https://pikepdf.readthedocs.io/en/latest/api/main.html?highlight=copy_foreign#pikepdf.Pdf.copy_foreign

**Comment by dreua** [comment]
@mara004 thanks! We are, however, still good with the performance and I think I should rather do proper profiling before I start optimizing based on assumptions.

**Comment by jbarlow83** [comment]
I'd say it's actually better to copy the foreign page once, and then duplicate it within its new home Pdf. This is newer advice than my previous remarks.

@dreua You only need that explicit `copy_foreign` when you might (or will) copy the *same page from a foreign PDF* into the same `Pdf` multiple times.

For copying a page from a foreign PDF is *always* a deep copy of necessity. There's no other way it could work.

As for why a special foreign function is needed, that's a design decision in libqpdf. While the design decision seems right to me for C++, I think Python's usage patterns are different, so I decided to try making copy foreign unnecessary (by having pikepdf figure out automatically if it's necessary in its binding layer). In the process I ran into a new issue a libqpdf:
https://github.com/qpdf/qpdf/issue/512

So for now copy_foreign remains necessary in some cases.

**Comment by dreua** [comment]
> For copying a page from a foreign PDF is _always_ a deep copy of necessity. There's no other way it could work.

So is there a significant performance penalty when I use copy_foreign in those cases? I wouldn't think so since a deep copy is needed anyway and that is was copy_foreign does, right?
Anyway, the export performance is very good imo, that is not really a concern over at PDF Arranger. (OT: We get a lot of requests for better support of annotations, outlines and stuff like this, so that is much more interesting at the moment.)

**Comment by jbarlow83** [comment]
No, there's no real penalty for copy_foreign, because in some cases pikepdf will do an implicit copy_foreign if you don't make it explicit. Even then, we're using something like 0.1% of the CPU time required to draw a single page PDF on screen to save a whole PDF to a file.

**Comment by dreua** [comment]
> I'd say it's actually better to copy the foreign page once, and then duplicate it within its new home Pdf. This is newer advice than my previous remarks.

Alright, I didn't understand this previously, sorry. I guess this would optimize things a bit, but it's not worth the effort for PDF Arranger imo. Duplicating large amount of pages is a niche use case anyway and I don't see a substantial increase in exported file size either, so the depth of this deep copy seems to be limited. Bottom line: It's really not a concern for us at the moment, but thanks for taking the time to explain things!
