### ISSUE TITLE
CCITTFaxDecode with EndOfLine=True fails as unsupported, but seems to be working

### ISSUE THREAD

**Issue by ekordas** [pikepdf/pikepdf#601]
Our scanner produces pdf Files with CCITTFaxDecode and /EndOfLine = True. Exporting an image is as pil Image is cought as UnsupportedImageTypeError Exception. But it seems just removing this mandatory Parameter it works. I successfully exported a pil Image this way. (See attached Pull Request)

Acording to the Adobe Pdf Reference this EndOfLine bit Pattern can appear allways, even if  /EndOfLine = False.

See Pdf Page 50 (marked as Page 36)
https://opensource.adobe.com/dc-acrobat-sdk-docs/pdfstandards/pdfreference1.0.pdf

Example PDF: 
[Test Scan CCITTFaxDecode  EndOfLine_True.pdf](https://github.com/user-attachments/files/16637148/Test.Scan.CCITTFaxDecode.EndOfLine_True.pdf)

**Comment by jbarlow83** [comment]
Can I add your example PDF to the project for future? I believe the reason I did it this way, is that I couldn't find any example files with EndOfLine=True for testing to verify correct behavior.

I will need you to confirm that you own copyright for the example PDF and release it under CC-BY-SA 4.0.

**Comment by ekordas** [comment]
You can add it as CC0 1.0 I can also print/scan some other Picture if that is better suitable for testing purposes.
