### ISSUE TITLE
ImportError: DLL load failed while importing _qpdf: The specified procedure could not be found.

### ISSUE THREAD

**Issue by tcf38012** [pikepdf/pikepdf#61]
Python 3.8.0 (tags/v3.8.0:fa919fd, Oct 14 2019, 19:37:50) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import pikepdf
Traceback (most recent call last):
  File "C:\Python38_64\lib\site-packages\pikepdf-1.6.5-py3.8-win-amd64.egg\pikepdf\__init__.py", line 10, in <module>
    from . import _qpdf
ImportError: DLL load failed while importing _qpdf: The specified procedure could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python38_64\lib\site-packages\pikepdf-1.6.5-py3.8-win-amd64.egg\pikepdf\__init__.py", line 12, in <module>
    raise ImportError("pikepdf's extension library failed to import")
ImportError: pikepdf's extension library failed to import

Python 3.8 Windows 10 1903 64 bit

**Comment by tcf38012** [comment]
![Annotation 2019-10-24 134130](https://user-images.githubusercontent.com/17708959/67515312-01456b80-f664-11e9-9c55-6ecb1df9d7c8.jpg)

**Comment by jbarlow83** [comment]
If you download https://github.com/qpdf/qpdf/releases/download/release-qpdf-9.0.0/qpdf-9.0.0-bin-msvc64.zip, extract the file named `qpdfXX.dll`, that should be the missing file. I think you'd drop it in `C:\Python38_64\lib\site-packages\pikepdf-1.6.5-py3.8-win-amd64.egg`.

The actual problem here is that the continuous integration service (Appveyor, Azure) don't have Windows Python 3.8 working properly yet, so you have to compile from source. If you can, use Python 3.7 for a little longer.

**Comment by tcf38012** [comment]
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\link.exe /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:C:\Python38_64\libs /LIBPATH:C:\Python38_64\PCbuild\amd64 "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\LIB\amd64" "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\LIB\amd64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.18362.0\ucrt\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.18362.0\um\x64" qpdf.lib /EXPORT:PyInit__qpdf build\temp.win-amd64-3.8\Release\src/qpdf\annotation.obj build\temp.win-amd64-3.8\Release\src/qpdf\object.obj build\temp.win-amd64-3.8\Release\src/qpdf\object_convert.obj build\temp.win-amd64-3.8\Release\src/qpdf\object_repr.obj build\temp.win-amd64-3.8\Release\src/qpdf\page.obj build\temp.win-amd64-3.8\Release\src/qpdf\pikepdf.obj build\temp.win-amd64-3.8\Release\src/qpdf\pipeline.obj build\temp.win-amd64-3.8\Release\src/qpdf\qpdf.obj build\temp.win-amd64-3.8\Release\src/qpdf\qpdf_pagelist.obj build\temp.win-amd64-3.8\Release\src/qpdf\shims.obj build\temp.win-amd64-3.8\Release\src/qpdf\utils.obj /OUT:build\lib.win-amd64-3.8\pikepdf\_qpdf.cp38-win_amd64.pyd /IMPLIB:build\temp.win-amd64-3.8\Release\src/qpdf\_qpdf.cp38-win_amd64.lib
LINK : fatal error LNK1181: cannot open input file 'qpdf.lib'
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\link.exe' failed with exit status 1181


That's the error it gave me, so I put qlib.lib from that same zip and copied it to pikepdf-1.6.5

**Comment by tcf38012** [comment]
Got it, forgot to run vcvarsall.bat
