### ISSUE TITLE
 error while getting stream data for 346 0 R: content stream (content stream object 97 0): errors while decoding content stream

### ISSUE THREAD

**Issue by nambanguyennn** [pikepdf/pikepdf#613]
input_pdf = Pdf.open(input_file)
width = input_pdf.pages[0].mediabox[2]
height = input_pdf.pages[0].mediabox[3]
watermark_pdf = make_watermark_image(watermark_text, email, int(width), int(height), level)

watermark = Pdf.open(watermark_pdf)
input_pdf = Pdf.open(input_file)
watermark_page = watermark.pages[0]
for page in input_pdf.pages:
	page.add_overlay(watermark_page, Rectangle(0, 0, 2383, 3370))
input_pdf.save(merged_path)

**Comment by hoangmt** [comment]
maybe this is input specific, i.e., input file has problem. Can you attach the input file?

**Comment by nonubot123** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by jbarlow83** [comment]
Not enough information to investigate
