### ISSUE TITLE
Permission issue

### ISSUE THREAD

**Issue by sjg2203** [pikepdf/pikepdf#615]
As referenced in issue #535, modern PDF readers ignore any attempt to block accessibility access.
Is there an alternative way to block the copy feature? Every other permission is blocked in my PDF but this one remains

**Comment by jbarlow83** [comment]
I'm pretty sure the feature you are referring to is named `Permissions.extract` in pikepdf, but it's hard to say how third party is translating the permissions.

**Comment by sjg2203** [comment]
Thanks, but I set it to `pikepdf.Permissions(extract=False)`, is there anything else that would work?

> I'm pretty sure the feature you are referring to is named `Permissions.extract` in pikepdf, but it's hard to say how third party is translating the permissions.

**Comment by jbarlow83** [comment]
You would need to check the PDF reference manual (linked in documentation) to get information on the bit fields that contribute to permissions, and then manipulate them one by one to figure how your PDF viewer interprets them.

**Comment by sjg2203** [comment]
Weird thing is that it's blocked on Chromium browsers but not in Firefox, same for Adobe Acrobat, it's blocked but with another PDF reader, it's allowed...
