### ISSUE TITLE
Slow and high memory with Chinese language & pikepdf >= 7.0.0 in Mingw64

### ISSUE THREAD

**Issue by kbengs** [pikepdf/pikepdf#616]
The issue can be reproduced with this code in MSYS2 / Mingw64:
```
# code run in "MSYS2 MSYS" terminal in Windows

import pikepdf  # fix 1: use pikepdf < 7.0

import locale
locale.setlocale(locale.LC_COLLATE, 'chinese')  # fix 2: set to other than chinese, greek, hebrew, japanese, korean

print("pikepdf-" + pikepdf.__version__)
print("libqpdf-" + pikepdf.__libqpdf_version__)

pdf_input = pikepdf.open('blank.pdf')  # Issue is with any pdf
pdf_output = pikepdf.Pdf.new()
i = 0
for page in pdf_input.pages:
    pdf_output.pages.append(page)
    print('page', i, 'added')
    #if i == len(pdf_input.pages) - 1:   # fix 3: help the loop to break
    #    break
    i += 1
print('loop done')
pdf_output.save("testfile.pdf")
print('all done')

# fix 4: increase memory. Then it will save but will be super slow and use a lot of memory (a few Gb).
```

And output is:
```
$ /mingw64/bin/python3.exe mexample2.py
pikepdf-9.2.1
libqpdf-11.9.1
page 0 added
Traceback (most recent call last):
  File "C:/msys64/home/kbeng/mexample/mexample2.py", line 14, in <module>
    for page in pdf_input.pages:
MemoryError: std::bad_alloc


```

The bug was first reported here https://github.com/pdfarranger/pdfarranger/issues/1110

As the issue is with pikepdf >= 7.0.0 can the issue be here?

**Comment by jbarlow83** [comment]
Try running it under a profiler such as
https://github.com/benfred/py-spy

Use the `--native` argument.

That may help isolate the function responsible for allocating lots of memory, since presumably it's the one that is also taking most of the time.

**Comment by kbengs** [comment]
py-spy looks interresting but in this environment it results in "Error: Failed to find python version from target process". Also tried to install vmprof-python but that wasn't successful. cprofile works but does not give any useful output.

We can work around the issue by setting locale.LC_COLLATE to 'C'. The issue might be somewhere in the msys environment. If I find out more I let you know. But for now you may close the issue if you like.
