### ISSUE TITLE
How to keep a pdf form editable

### ISSUE THREAD

**Issue by noahleatham** [pikepdf/pikepdf#618]
I'm using pikepdf to fill a form but the output form isn't editable, when I open it on acrobat reader I'm getting an error message: "This document enabled extended features in Adobe Reader, The document has been changes since it was created and use of extended features is no longer available."

Is it possible to keep the extended features enabled?

Currently doing:
with pikepdf.Pdf.open(file) as pdfData: 
pdfData.save(file)

Disables the extended features.

**Comment by jbarlow83** [comment]
Possibly different settings for open/save might preserve it.

There are several ways to do forms in PDF so I can't tell what's going on. Would need to see the input file.

**Comment by noahleatham** [comment]
> Possibly different settings for open/save might preserve it.
> 
> There are several ways to do forms in PDF so I can't tell what's going on. Would need to see the input file.

This form: https://www.onr.navy.mil/media/document/opnav-523914-system-authorization-access-request-navy-saar-n-form is similar to what I'm working with. When opening the pdf and then saving it using the above code the Extended Features are disabled with the same message as noted above.

**Comment by noahleatham** [comment]
To add to this, by trying to set permissions using encryption while saving, even if the permissions are all set to allow. The document restrictions still persist:
![image](https://github.com/user-attachments/assets/2e2121ba-56a5-404b-b274-d7f61007bf21)

with pikepdf.Pdf.open(file) as pdfData:
    pdfData.save(write, encryption = pikepdf.Encryption())

**Comment by nonubot123** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by jbarlow83** [comment]
If you set `encryption=True`, the original encryption is copied (the PDF will be recreated with the same encryption key, even if the password is not known). 

However: This looks like an Adobe LiveCycle PDF, which is a mostly undocumented and now discontinued extension of PDF. It seems Adobe only sold LiveCycle to governments and perhaps some large organizations. The LiveCycle payload is partly encrypted, and it can contain tamper protection to check if the containing PDF was modified. If modified, it disables this extended functionality. To the best of my knowledge there is no way any open source tool can handle LiveCycle, and this is by Adobe's design. (But one could consider other automation tools, such as AutoHotkey.)

A simple test for LiveCycle is checking if the `pdf.docinfo.Producer` contains the text "LiveCycle". A more robust test could be derived as well.
