### ISSUE TITLE
Source build of v9.4.2 on older intel macs fails

### ISSUE THREAD

**Issue by chrisdunley** [pikepdf/pikepdf#624]
I'm running macOS 12.7.6 on an Intel machine and have python 3.11 and 3.12 installed.  Upgrading pikepdf via pip3 install -U fails as the qpdf headers cannot be found despite them being available in the usual `/usr/local/include` directory.

I see that the setup.py file includes shims for includes and libdirs for 'bsd' and for 'darwin' with Apple silicon.  Shims for older Intel machines (which are more likely to be building from source) have no entry and so the build fails.  I assume that this is a recent change as v9.4.0 installed fine.

The simplest fix (which is what I did to solve the problem) would be to add a third limb to the if statement from line 54 of `setup.py` as follows:
```
    elif 'darwin' in sys.platform and machine() == 'arm64':
        shim_includes = ['/usr/local/include']
        shim_libdirs = ['/usr/local/lib']
```
I'd submit a pull request to update the file but, tbh, that's beyond me.

**Comment by chrisdunley** [comment]
Ah - I see that macOS12 is now unsupported, though of course it all still works.  I think that point above still stands for intel machines running macOS13 though...

**Comment by jbarlow83** [comment]
macOS 13 is still supported and binary wheels are built for it. 

For macOS 12, Homebrew dropped support for this version, meaning all pikepdf dependencies have to be built from scratch. I can't support it without Homebrew. You'll probably run into issues with other software you use too. 

Your best bet is to use an older binary wheel version of pikepdf from the era when macOS 12 was supported.
