### ISSUE TITLE
GTS_PDFXVersion Meta

### ISSUE THREAD

**Issue by jessejamesrich** [pikepdf/pikepdf#630]
Really hate to ask what is probably a really dumb question, but for the life of me I cannot figure out how to simply set the GTS_PDFXVersion in the meta data. Any help would be hugely appreciated. I understand this does not force compliance.

**Comment by jbarlow83** [comment]
There's quite a lot you need to do mark a file as PDF/X. Hard to say what criteria are tested by an application looking for it. 

Here is what Ghostscript does. 

https://ghostscript.readthedocs.io/en/gs10.0.0/VectorDevices.html#creating-a-pdf-x-3-document

**Comment by jessejamesrich** [comment]
Thank you for this very, very quick reply. I came to remove this as I realized what I was doing wrong pretty much immediately, but I really appreciate your response and the obvious care you put into this project. Thank you!
