### ISSUE TITLE
 How to install the package on Centos 7?

### ISSUE THREAD

**Issue by miguelgarces123** [pikepdf/pikepdf#64]
I can't find a way to install the package in Centos 7, is it possible to do it?

**Comment by miguelgarces123** [comment]
The following error comes up when installing pikepdf in centos 7, I already have all the dependencies installed but I have not been able to solve this problem, can you help me?

![Captura de Pantalla 2019-11-12 a la(s) 3 55 08 p  m](https://user-images.githubusercontent.com/41314268/68710178-0ad83a00-0565-11ea-9342-d4061cde5f71.png)
![Captura de Pantalla 2019-11-12 a la(s) 3 55 21 p  m](https://user-images.githubusercontent.com/41314268/68710180-0ad83a00-0565-11ea-9d79-96f64e6bf91d.png)

**Comment by jbarlow83** [comment]
First make sure you are using pip 19.3 or newer. Old versions of pip cannot find the latest Python wheels.

The immediate cause of this error is that you are missing the headers for libqpdf. Centos 7 should provide headers in a packaged named something like libqpdf-devel but this will be too old.

**Comment by jbarlow83** [comment]
I'll close the issue now. If you have further related questions feel free to reopen it.
