### ISSUE TITLE
AttributeError: 'pikepdf._qpdf.Pdf' object has no attribute 'close'

### ISSUE THREAD

**Issue by klartext** [pikepdf/pikepdf#65]
IMHO strange error.
A tool that already has worked (and not was changed in between) now throws such an error.
Problem occurs with pikepdf 1.6.5, which was updated in end of october - looks like the problem was introduced by 1.6.5 version.

**Comment by jbarlow83** [comment]
Can you provide a test file and sample that demonstrates the issue?

**Comment by klartext** [comment]
<pre>
#!/usr/bin/python                                                               
                                                
import sys                                                                      
from pikepdf import Pdf                                                         
                                                                                                                                                            
num_of_pages = 0                                                                
                                                                                
for file in sys.argv[1:]:                                                       
    pdf = Pdf.open( file )                                                      
    pages = len(pdf.pages)                                                      
    num_of_pages = num_of_pages + pages                                         
    #pdf.close()                                                                
    print("%4d pages in file %s" % (pages, file) )                              
                                                                                                                                                         
print("Sum of pages:", num_of_pages) 
</pre>

**Comment by klartext** [comment]
Testfile: ftp://ftp.ams.org/pub/tex/doc/amsmath/amsldoc.pdf
But with all others I tried, it is the same.
Uncommenting the pdf.close() and the problem occurs.
Problem is new with 1.6.5.

**Comment by klartext** [comment]
With pikepdf 1.7.0 the problem vanished.

**Comment by jbarlow83** [comment]
Nothing changed that's relevant afaict.

Note that the file `pikepdf._methods` is involved in "installing" `.close()` onto the pikepdf.Pdf class because the implementation of `.close()` is written in Python. If you somehow suppress `pikepdf._methods` from being executed, various things will break. Similarly, if you directly import from `pikepdf._qpdf`.

**Comment by klartext** [comment]
I just used the code as quoted above.
Don't know how to "suppress pikepdf._methods from being executed" or how to "directly import from pikepdf._qpdf" willingly.
Do I do something like that in the quoted code? AFAIK the code follows the docs. Should it look different?

If nothing has changed that affects the close()-issue, I wonder where the problem comes from. Looks like a problem that is existing but only occuring randomly then... let's wait and see if this issue needs to be opened again one day...
