### ISSUE TITLE
Pythonic way of iterating over all PDF objects?

### ISSUE THREAD

**Issue by rbrito** [pikepdf/pikepdf#67]
Hi, @jbarlow83.

I have some PDFs that I would like to make smaller by removing some metadata that is not used for displaying purposes (e.g., thumbnails, `/Metadata`, `/PieceInfo` and so on).

Currently, I am uncompressing the files with `qpdf` in QDF format, editing the text directly with a text editor and, then, fixing the file with qpdf and/or pdfsizeopt.

I would like to do something similar to:

```python
for obj in my_pdf:
   if '/Metadata' in obj:
       del(obj['/Metadata'])
```
Can something like this be done? Currently, the closest that I discovered how to do is something like:

```python
for i in range(1, max_obj_number+1):
    if '/Metadata' in my_pdf.get_object(i, 0)
        del(obj['/Metadata'])
```

Unfortunately, I don't know (short of inspecting the output of `my_pdf.show_xref_table()`) how to discover the number of objects that my PDF has (a flaky way seems to be to take a look at `/Size` in the trailer, but the trailer may not be consistent).

It would be awesome to be able to iterate over the objects in the pythonic way.

Thanks for any help,

Rogério Brito.

**Comment by jbarlow83** [comment]
Well, that was fairly easy to do, so I added it. v1.7.1 - `my_pdf.objects`

**Comment by jbarlow83** [comment]
Note it's not what you propose `for obj in my_pdf` - I think some people might expect that to mean iterate pages, so instead you have to specify whether you want `.pages` or `.objects`.

**Comment by rbrito** [comment]
Super duper thanks, @jbarlow83!
