### ISSUE TITLE
Documentation wish: Example of using PdfMatrix

### ISSUE THREAD

**Issue by cepm-nate** [pikepdf/pikepdf#69]
I have no doubt the documentation for "class PdfMatrix" at https://github.com/pikepdf/pikepdf/blob/master/src/pikepdf/models/matrix.py is understandable by someone who's done maths involving matrics. For the rest of us, it would be very helpful to see a short example that (a) reads a file, (b) offsets a page, then (c) saves the file. 

I think this would go a long way towards helping newcomers get up to speed.

In my case, I'm simply trying to add an offset to a page. In PyPDF3, this works:
```
page.addTransformation((1, 0, 0, 1, ptOffset, 0))
```
But I'm not sure how to do the same thing in pikepdf. Do I create a stream, then run this page through it? Do I create a stream with .translated() on it, then somehow run the page through it? or do I take the page object and somehow apply the matrix.translated()? Again, I'm sure this is clear to seasoned users, but for newcomers it is a bit of a hurdle without clear and simple examples.

In pikepdf, using this ```page.translated((1, 0, 0, 1, ptOffset, 0))``` results in ```AttributeError: translated```.

If I try ```page.PdfMatrix.translated()``` it results in ```AttributeError: /PdfMatrix```. I've also tried using page.Content (as that is a stream), but have yet to arrive a working result.

Any help in this area would be appreciated. :-)

**Comment by jbarlow83** [comment]
Added in v1.9.0 docs
