### ISSUE TITLE
"pikepdf's extension library failed to import"

### ISSUE THREAD

**Issue by berkistayn** [pikepdf/pikepdf#70]
Hi,

On windows 10, version 1.8.1 throws this ImportError. I tried to install and import on several computers, the issue persists. As a solution, I am using version 1.7.0,

I did a check on dependencies, for version 1.8.1 VCRUNTIME140_1.dll is missing.

**Comment by edge-python** [comment]
Win10_64,  py 1.8.1. , pikepdf last working: 1.7.0

pikepdf:1.7.1, 1.8.0, 1.8.1:
```
Traceback (most recent call last):
  File "...\Python38\lib\site-packages\pikepdf\__init__.py", line 10, in <module>
    **from . import _qpdf**
ImportError: **DLL load failed while importing _qpdf**: not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "...\test_pikepdf.py", line 3, in <module>
    import pikepdf
  File "...\Python38\lib\site-packages\pikepdf\__init__.py", line 12, in <module>
    raise ImportError("pikepdf's extension library failed to import")
ImportError: **pikepdf's extension library failed to import**
```

**Comment by edge-python** [comment]
with 1.8.2 no change compared to 1.8.1:

Win10_64, py 3.8.1. , pikepdf last working: 1.7.0

pikepdf: 1.7.1, 1.8.0, 1.8.1, 1.8.2:

`ImportError: DLL load failed while importing _qpdf: not found`

**Comment by jbarlow83** [comment]
Try installing the Visual C++ runtime for 2015 from here

https://support.microsoft.com/en-au/help/2977003/the-latest-supported-visual-c-downloads

**Comment by jbarlow83** [comment]
@edge-python Did that work? I'd like to update the docs if it did

**Comment by edge-python** [comment]
1.)
with 1.8.3 no change compared to 1.8.1:
Win10_64, py 3.8.1. , pikepdf last working: 1.7.0
pikepdf: 1.7.1, 1.8.0, 1.8.1, 1.8.2, 1.8.3:
`ImportError: DLL load failed while importing _qpdf: not found`

2.)
@ jbarlow83 Thanks for your advice
but i had always installed:
Microsoft Visual C++ 2015 Redistributable (x86) – 14.0.23026
Microsoft Visual C++ 2017 Redistributable (x64) – 14.11.25325

why does 1.7.0 work in the same environment but not 1.8.x?

**Comment by jbarlow83** [comment]
Let's check that you have the 64-bit versions of everything: Python 3.8 64-bit, and that pikepdf is installing from the 64-bit wheel, and that you have the 64-bit C++ runtime. The C++ 2015 x86 runtime won't help. I don't know if the C++ 2017 x64 runtime provides the missing file.

You could try http://www.dependencywalker.com/ on the .dll

**Comment by jusla** [comment]
I also had Microsoft Visual C++ 2015 Redistributable (x64) 14.20 installed, and I got the same error message as @berkistayn and @edge-python when running ocrmypdf. Once I installed Microsoft Visual C++ 2015-2019 Redistributable (x64) 14.24.28127 from jbarlow83's link in [the comment above](https://github.com/pikepdf/pikepdf/issues/70#issuecomment-570376653), the error message did not appear anymore when running ocrmypdf. Thanks @jbarlow83 !

**Comment by jbarlow83** [comment]
I added a more detailed error message that directs use to install the file @jusla  mentioned.
