### ISSUE TITLE
Failure of test_degenerate_html[] with python 3.7 too

### ISSUE THREAD

**Issue by spwhitton** [pikepdf/pikepdf#72]
I'm seeing this test fail with python 3.7 too:

    autopkgtest [10:04:52]: test test-suite: [-----------------------
    ============================= test session starts ==============================
    platform linux -- Python 3.7.6, pytest-4.6.9, py-1.8.0, pluggy-0.13.0
    hypothesis profile 'default' -> database=DirectoryBasedExampleDatabase('/tmp/autopkgtest.h0yMPE/build.m91/src/.hypothesis/examples')
    rootdir: /tmp/autopkgtest.h0yMPE/build.m91/src, inifile: setup.cfg, testpaths: tests
    plugins: hypothesis-4.36.2, xdist-1.31.0, forked-1.0.2, timeout-1.3.3, helpers-namespace-2019.1.8
    collected 259 items
    
    tests/test_codec.py ..                                                   [  0%]
    tests/test_dictionary.py ..                                              [  1%]
    tests/test_encrypt.py .................................                  [ 14%]
    tests/test_filters.py .......                                            [ 16%]
    tests/test_formxobject.py .                                              [ 17%]
    tests/test_image_access.py .................x.s......                    [ 27%]
    tests/test_io.py ......                                                  [ 29%]
    tests/test_ipython.py ....                                               [ 31%]
    tests/test_metadata.py ..........................sss........F...s.       [ 47%]
    tests/test_object.py ................................................... [ 67%]
    ...                                                                      [ 68%]
    tests/test_page.py ..                                                    [ 69%]
    tests/test_pages.py .........................                            [ 79%]
    tests/test_parsers.py ..s.                                               [ 80%]
    tests/test_pdf.py ................................                       [ 93%]
    tests/test_pdfa.py ss                                                    [ 93%]
    tests/test_private_pdfs.py s                                             [ 94%]
    tests/test_refcount.py .....                                             [ 96%]
    tests/test_sanity.py ..........                                          [100%]
    
    =================================== FAILURES ===================================
    ____________________________ test_degenerate_xml[] _____________________________
    
    self = <pikepdf.models.metadata.PdfMetadata object at 0x7fdcb69f04d0>
    data = b''
    
        def _load_from(self, data):
            try:
    >           self._xmp = parse(BytesIO(data))
    
    /usr/lib/python3/dist-packages/pikepdf/models/metadata.py:304: 
    _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
    
    >   ???
    
    src/lxml/etree.pyx:3469: 
    _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
    
    >   ???
    
    src/lxml/parser.pxi:1856: 
    _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
    
    >   ???
    
    src/lxml/parser.pxi:1876: 
    _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
    
    >   ???
    
    src/lxml/parser.pxi:1764: 
    _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
    
    >   ???
    
    src/lxml/parser.pxi:1127: 
    _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
    
    >   ???
    
    src/lxml/parser.pxi:601: 
    _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
    
    >   ???
    
    src/lxml/parser.pxi:711: 
    _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
    
    >   ???
    E     File "<string>", line 0
    E   lxml.etree.XMLSyntaxError: <no detail available>
    
    src/lxml/parser.pxi:651: XMLSyntaxError
    
    During handling of the above exception, another exception occurred:
    
    self = <pikepdf.models.metadata.PdfMetadata object at 0x7fdcb69f04d0>
    data = b''
    
        def _load_from(self, data):
            try:
                self._xmp = parse(BytesIO(data))
            except XMLSyntaxError:
                data = re_xml_illegal_bytes.sub(b'', data)
                try:
    >               self._xmp = parse(BytesIO(data))
    
    /usr/lib/python3/dist-packages/pikepdf/models/metadata.py:308: 
    _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
    
    >   ???
    
    src/lxml/etree.pyx:3469: 
    _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
    
    >   ???
    
    src/lxml/parser.pxi:1856: 
    _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
    
    >   ???
    
    src/lxml/parser.pxi:1876: 
    _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
    
    >   ???
    
    src/lxml/parser.pxi:1764: 
    _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
    
    >   ???
    
    src/lxml/parser.pxi:1127: 
    _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
    
    >   ???
    
    src/lxml/parser.pxi:601: 
    _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
    
    >   ???
    
    src/lxml/parser.pxi:711: 
    _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
    
    >   ???
    E     File "<string>", line 0
    E   lxml.etree.XMLSyntaxError: <no detail available>
    
    src/lxml/parser.pxi:651: XMLSyntaxError
    
    The above exception was the direct cause of the following exception:
    
    trivial = <pikepdf.Pdf description='/tmp/autopkgtest.h0yMPE/build.m91/src/tests/resources/pal-1bit-trivial.pdf'>
    xml = b''
    
        @pytest.mark.parametrize(
            'xml',
            [
                b"",
                b"      \n   ",
                b"""<?xpacket begin="\xef\xbb\xbf" id="W5M0MpCehiHzreSzNTczkc9d"?>
                <?xpacket end=""?>
                """.strip(),
                b"""<?xpacket begin="" id=""?>
                <x:xmpmeta xmlns:x="adobe:ns:meta/" x:xmptk="">
                </x:xmpmeta>
                <?xpacket end=""?>
                """.strip(),
            ],
        )
        def test_degenerate_xml(trivial, xml):
            if xml == b'' and platform.system() == 'Darwin':
                pytest.skip(msg="fails on macOS/Python 3.5 and 3.8; unknown cause")
            trivial.Root.Metadata = trivial.make_stream(xml)
    >       with trivial.open_metadata() as xmp:
    
    tests/test_metadata.py:383: 
    _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
    /usr/lib/python3/dist-packages/pikepdf/models/metadata.py:198: in wrapper
        self._load()
    /usr/lib/python3/dist-packages/pikepdf/models/metadata.py:300: in _load
        self._load_from(data)
    _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
    
    self = <pikepdf.models.metadata.PdfMetadata object at 0x7fdcb69f04d0>
    data = b''
    
        def _load_from(self, data):
            try:
                self._xmp = parse(BytesIO(data))
            except XMLSyntaxError:
                data = re_xml_illegal_bytes.sub(b'', data)
                try:
                    self._xmp = parse(BytesIO(data))
                except XMLSyntaxError as e:
                    if str(e).startswith("Start tag expected, '<' not found") or str(
                        e
                    ).startswith("Document is empty"):
                        # This is usually triggered by processing instructions
                        # in another otherwise empty document, or empty documents,
                        # which we consider safe to coerce to a well-formed
                        # XMP. For harder cases like truncated XMP, we want to
                        # raise the exception so that someone is alerted.
                        self._xmp = parse(BytesIO(XMP_EMPTY))
                    else:
    >                   raise PdfError() from e
    E                   pikepdf._qpdf.PdfError
    
    /usr/lib/python3/dist-packages/pikepdf/models/metadata.py:320: PdfError
    ========== 1 failed, 248 passed, 9 skipped, 1 xfailed in 5.23 seconds ==========
    autopkgtest [10:04:58]: test test-suite: -----------------------]
    autopkgtest [10:04:58]: test test-suite:  - - - - - - - - - - results - - - - - - - - - -
    test-suite           FAIL non-zero exit status 1
    autopkgtest [10:04:58]: @@@@@@@@@@@@@@@@@@@@ summary
    test-suite           FAIL non-zero exit status 1

**Comment by jbarlow83** [comment]
Should be better in v1.9.0
