### ISSUE TITLE
want to use python search for a string a directory of encrypted pdfs and return the pdfs that have the string

### ISSUE THREAD

**Issue by mallorydixon** [pikepdf/pikepdf#78]
import os
import PyPDF2 #case sensitive
import textract
import glob
import docx2txt
import io

os.chdir('/Users/mdixon/Documents/contracts') #need to make generic user path
print (os.getcwd())

searchstring = ('banana') #need to make a wildcard search
print (searchstring)

for filename in os.listdir('/Users/mdixon/Documents/contracts'):
	if filename.endswith('.pdf'):
		pdfCounter = len(glob.glob1('/Users/mdixon/Documents/contracts','*.pdf'))
		with open(os.path.join('/Users/mdixon/Documents/contracts', filename)) as f:
			pdfFileObj = open(filename, 'rb')
			pdfReader = PyPDF2.PdfFileReader(pdfFileObj)
			num_pages = pdfReader.numPages
			print(num_pages)
			count = 0
			text = ""
			while count < num_pages:
				pageObj = pdfReader.getPage(count)
				print(pageObj)
				count += 1
				text += pageObj.extractText()
				print(text)
				if text != searchstring:
					text=text
				elif text == searchstring:
					print('searchstring found in ', filename)
				else:
					print('searchstring not found in ', filename)

this is the code i have now,  but it does not work. I have tried to install pikepdf but it will not install on my mac. it returns this error: Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/Library/Python/3.7/site-packages/pikepdf'
Consider using the `--user` option or check the permissions.

if anyone has any suggestions as to why it will not work it will be greatly appreciated. There are 800 encrypted pdf's I am trying to search through for a phrase. None of them have passwords they are only encrypted.

**Comment by jbarlow83** [comment]
As the error message suggests you do not have permission to install and may
try `pip install --user pikepdf` instead.

If you are attempting to search for text use pdfminer.six. PyPDF2 attempts
to extract text and returns incorrect garbage data all but trivial cases.
Pikepdf does not currently have text extraction.

**Comment by mallorydixon** [comment]
I’ve tried pdfminer.six too but it returns the same error.

**Comment by mallorydixon** [comment]
I also need to do pip3 in order for it to work. I don’t have much experience with python so I’m not sure if that makes a difference.
