### ISSUE TITLE
Cannot rotate / crop individual instances of duplicated pages

### ISSUE THREAD

**Issue by dreua** [pikepdf/pikepdf#80]
In [pdfarranger](https://github.com/jeromerobert/pdfarranger/issues/141) users should be able to duplicate pages and rotate / crop individual instances of these pages, but in the pdf created by pikepdf all the instances of the page have the same rotation / cropping applied. 

Our best guess is that copy_foreign is creating a shallow copy.

I focus on rotation here since cropping (i.e. setting Mediabox) is probably the same.

The qpdf command works like it should: 
[a] :arrow_right: [ɐ][a][ɐ][a]
`qpdf in.pdf --pages . 1,1,1,1 -- --rotate=180:1,3 out.pdf`

With pikepdf all pages end up the same:
[a] :arrow_right: [ɐ][ɐ][ɐ][ɐ]
```python
import sys
import pikepdf

if len(sys.argv) < 2:
    print("Need one pdf as argument")
    exit(1)

pdf_output = pikepdf.Pdf.new()
pdf_input = pikepdf.open(sys.argv[1])

for i in range(4):
    pdf_output.pages.append(pdf_output.copy_foreign(pdf_input.pages[0]))

for i in [0,2]:
    pdf_output.pages[i].Rotate = 180

pdf_output.save("duplicate_pdf_test.pdf")
```

**Comment by jbarlow83** [comment]
Thanks - fixed for next version.

Here is a workaround for earlier versions.

```python
from copy import copy
new_page = copy(pdf_output.copy_foreign(pdf_input.pages[0]))
```

The issue was that libqpdf found it already copied the foreign object to `pdf_output`, so it returns a reference to the previously copied object.

**Comment by dreua** [comment]
That's great, thank you so much!

**Comment by jbarlow83** [comment]
Fixed v1.10.2

**Comment by xilopaint** [comment]
Hey @dreua @dreua, could you guys post a small code snippet showing how to crop a page? I'm struggling to do it.

**Comment by xilopaint** [comment]
Hey @dreua @jbarlow83, could you guys post a small code snippet showing how to crop a page? I'm struggling to do it. My intention is cropping a two-column page in half creating two independent pages.

**Comment by dreua** [comment]
@xilopaint here you go. Everyone feel free to use this for whatever you need. Would this be a good addition to the pikepdf documentation? 

```python
import sys
import pikepdf

if len(sys.argv) < 2:
    print("Need one pdf as argument")
    exit(1)

pdf_input = pikepdf.open(sys.argv[1])
pdf_output = pikepdf.Pdf.new()


for page in pdf_input.pages:
    for i in range(2):
        pdf_output.pages.append(pdf_output.copy_foreign(page))

is_left_page = True
for page in pdf_output.pages:
    x_start, y_start, x_end, y_end = page.MediaBox
    # page.MediaBox does not always start with [0, 0, ...] therefore we need
    # the following calculation to find the middle of the page
    middle = x_start + (x_end - x_start) / 2
    if is_left_page:
        x_end = middle
    else:
        x_start = middle
    page.MediaBox = [x_start, y_start, x_end, y_end]
    is_left_page = not is_left_page

pdf_output.save("crop_pdf.pdf")

```

**Comment by xilopaint** [comment]
Thanks @dreua, but your code doesn't work properly in a landscape layout.

**Comment by dreua** [comment]
True, it doesn't work if the page is already rotated in the pdf but it works on a page that is true landscape. (I just tested it with a scan.)

Pdfarranger has the following code to deal with this: 
https://github.com/jeromerobert/pdfarranger/blob/c3f2f30182daa52b58437f248fe2ff4c2228dd9d/pdfarranger/exporter.py#L25-L44

I'm curious: Is this for some open source or proprietary software?

**Comment by jbarlow83** [comment]
For rotation there are several cases:

1. Page MediaBox width < height, but rotated from the "outside" with `page.Rotate % 90 == 90` - rotation is applied after the fact

1. Page MediaBox width > height, `page.Rotate % 90 == 0` - orientation of page contents is baked into the content stream

1. Both of the above

You have to track separately if you are doing a landscape or portrait crop.

**Comment by xilopaint** [comment]
> True, it doesn't work if the page is already rotated in the pdf but it works on a page that is true landscape. (I just tested it with a scan.)

Hey, you're right! I just did the same test.

> Pdfarranger has the following code to deal with this:
> https://github.com/jeromerobert/pdfarranger/blob/c3f2f30182daa52b58437f248fe2ff4c2228dd9d/pdfarranger/exporter.py#L25-L44

Unfortunately it's a bit hard to understand.

> I'm curious: Is this for some open source or proprietary software?

I'm the maintainer of [Alfred PDF Tools](https://github.com/xilopaint/alfred-pdf-tools)  and am in the process of rewriting the codebase using pikepdf instead of PyPDF.

> For rotation there are several cases:
> 
> 1. Page MediaBox width < height, but rotated from the "outside" with `page.Rotate % 90 == 90` - rotation is applied after the fact
> 2. Page MediaBox width > height, `page.Rotate % 90 == 0` - orientation of page contents is baked into the content stream
> 3. Both of the above
> 
> You have to track separately if you are doing a landscape or portrait crop.

Thanks, I'll look into those cases.
