### ISSUE TITLE
isinstance(obj, pikepdf.Operator) doesn't work

### ISSUE THREAD

**Issue by pdknsk** [pikepdf/pikepdf#86]
For some reason this fails on objects returned from `pikepdf.parse_content_stream`.

```Python
...
  if isinstance(obj, pikepdf.Operator):
TypeError: isinstance() arg 2 must be a type or tuple of types
```
I've been using this as a workaround.
```Python
if isinstance(obj, pikepdf.Object) and obj._type_code == pikepdf.ObjectType.operator:
```

**Comment by pdknsk** [comment]
It works for other objects like `pikepdf.Name` so it's not clear to me why `Operator` is different.

**Comment by jbarlow83** [comment]
That's a bug. Will fix.
