### ISSUE TITLE
Open command rejects valid password

### ISSUE THREAD

**Issue by orotau** [pikepdf/pikepdf#87]
I have a pdf file that has a 7 digit password that I know.
I am using this code

```
try:
    Pdf.open("file.pdf", password="1234567")
except:
    type, value, traceback = sys.exc_info()
    print("type", type)
    print("value", value)
    print("traceback", traceback)
else:
    print("open")
```

I am getting an "invalid password" error.
I am wondering if it is to do with this error https://github.com/qpdf/qpdf/issues/212
I am using pikepdf 1.10.3

Thanks for creating the project

**Comment by jbarlow83** [comment]
It's probably not the linked issue, but it may be an issue of similar nature.

It will be easier if I can look at the actual file. If you are concerned about sharing the file publicly, you can encrypt it with my public key as described here:
https://github.com/jbarlow83/OCRmyPDF/wiki 
This is the same GPG used to sign releases.

If you don't want to share the file with me, try to create a non-sensitive file with the same program that created the original.

It would be interested to see if `qpdf --check` lists an errors.

Another option would be to try the `pdfcrack` program on it. This will manually derive the hex password and provide some parameters about how the file is encrypted.

**Comment by orotau** [comment]
When I try
```
gpg --keyserver pgp.mit.edu --recv-keys 4434eb74c4a35f7f
```
I get
```
gpg: keyserver receive failed: No data
```

**Comment by orotau** [comment]
Here is the file
Here is the result of the check command

PDF Version: 1.4
R = 2
P = -4
User password = 1074412
Supplied password is owner password
Supplied password is user password
extract for accessibility: allowed
extract for any purpose: allowed
print low resolution: allowed
print high resolution: allowed
modify document assembly: allowed
modify forms: allowed
modify annotations: allowed
modify other: allowed
modify anything: allowed
File is not linearized
No syntax or stream encoding errors found; the file may still contain
errors that qpdf cannot detect

I managed to use the decrypt command from 'qpdf' to successfully decrypt the file

[ps.pdf.zip](https://github.com/pikepdf/pikepdf/files/4410408/ps.pdf.zip)

**Comment by jbarlow83** [comment]
Works for me....

```
In [13]: try: 
    ...:     Pdf.open("ps.pdf", password="1074412") 
    ...: except: 
    ...:     type, value, traceback = sys.exc_info() 
    ...:     print("type", type) 
    ...:     print("value", value) 
    ...:     print("traceback", traceback) 
    ...: else: 
    ...:     print("open") 
    ...:                                                                                                                                                                                                                                                                                                         
open
```

What platform are you using?

Do you know if you are using pikepdf built from a wheel, or a version distributed by your OS (e.g. the python3-pikepdf package in Debian)? 

What is the value of ` pikepdf.__libqpdf_version__`?

**Comment by orotau** [comment]
Ubuntu 18.04
Python 3.6.9 in a virtual environment
I installed using "pip install pikepdf"
pikepdf version 1.10.3
pikepdf.__libqpdf_version__ = 9.02

**Comment by jbarlow83** [comment]
The issue seems related to the underlying version of libqpdf.

I released a new version, which updates the libqpdf version. Please update and try that.

**Comment by jbarlow83** [comment]
Any luck?

**Comment by orotau** [comment]
I had problems installing the new version. I will add details shortly.

**Comment by orotau** [comment]
First effort

```pip install git+git://github.com/pikepdf/pikepdf.git@e43ab86e05315214534db000f9cfc3b8a23cc88f```

I got 
```ERROR: Could not build wheels for pikepdf which use PEP 517 and cannot be installed directly```

I tried
```pip install --no-binary git+git://github.com/pikepdf/pikepdf.git@e43ab86e05315214534db000f9cfc3b8a23cc88f git+git://github.com/pikepdf/pikepdf.git@e43ab86e05315214534db000f9cfc3b8a23cc88f```

but got the same error as above

I tried
```pip install --no-use-pep517 git+git://github.com/pikepdf/pikepdf.git@e43ab86e05315214534db000f9cfc3b8a23cc88f```

```ERROR: Disabling PEP 517 processing is invalid: project specifies a build backend of setuptools.build_meta in pyproject.toml```

So was unable to test

**Comment by jbarlow83** [comment]
Might be an old version of `pip`.

In any case you should be able to do `pip install -U pikepdf` and get the latest version.

**Comment by orotau** [comment]
Great I tried that command and it works fine.
The bug has gone, thanks and take care

**Comment by zikonde** [comment]
Have your python skills improved by any chance? I tried everything above byt still getting the error:
 value /workspaces/rpwd/document.pdf: invalid password
