### ISSUE TITLE
Apache license in licenses/

### ISSUE THREAD

**Issue by spwhitton** [pikepdf/pikepdf#9]
Hello,

So far as I can tell there is no Apache-licensed code in pikepdf.  So it is a bit confusing to have a copy of the Apache license in the licenses/ subdirectory.  Maybe it is leftover from something else and could be removed?

Thanks.

**Comment by spwhitton** [comment]
Ah, presumably this is for the Python wheel?

Given that the Apache license is contained within license.wheel.txt, it seems unnecessary to have a second copy in license.apache2.txt.

**Comment by jbarlow83** [comment]
Correct, it's for the wheel. I'll remove the copies.

**Comment by jbarlow83** [comment]
Fixed in 873b7fd72
