### ISSUE TITLE
Add watermark to PDF

### ISSUE THREAD

**Issue by joneug** [pikepdf/pikepdf#95]
I tried to add a watermark to a PDF file but unfortunately the resulting output PDF does not contain the watermark. I create the watermark on-the-fly using the [reportlab](https://pypi.org/project/reportlab/) library. Ideally, the following code snippet should generate the watermark PDF, add it to the first page of the input PDF and save it to an output PDF.

@jbarlow83 In issue #43 you mentioned that the watermark should be "entirely vector art". I assume that this could be the problem in this case. In your comment you refer to `weave.py` in ocrmypdf for an example how to add watermarks with text. Sadly, I cannot find this reference. Hopefully, you can give me a hint on how to achieve adding watermarks with text.

```python
from datetime import datetime

from reportlab.pdfgen import canvas
import pikepdf

INPUT_PDF = 'input.pdf'
WATERMARK_PDF = 'watermark.pdf'
OUTPUT_PDF = 'output.pdf'


def generate_watermark(timestamp):
    c = canvas.Canvas(WATERMARK_PDF, bottomup=0)
    c.setFontSize(12)
    c.setFillColorCMYK(0, 0, 0, 0, alpha=0.7)
    c.rect(14, 9, 157, 15, stroke=0, fill=1)
    c.setFillColorCMYK(0, 0, 0, 100, alpha=0.7)
    c.drawString(15, 20, 'Received %s' % timestamp.strftime('%d.%m.%Y'))
    c.save()


def add_watermark():
    with pikepdf.open(INPUT_PDF) as input_pdf, \
            pikepdf.open(WATERMARK_PDF) as watermark_pdf, \
            open(OUTPUT_PDF, 'wb') as output_stream:
        
        # Create new output PDF
        output_pdf = pikepdf.new()

        # Add watermark to first page of input PDF
        input_pdf.pages[0].page_contents_add(contents=watermark_pdf.pages[0].Contents)

        # Add input PDF to output PDF and save
        output_pdf.pages.extend(input_pdf.pages)
        output_pdf.save(output_stream)


generate_watermark(datetime.now())
add_watermark()
```

**Comment by jbarlow83** [comment]
This is the content stream reportlab generates

```
1 0 0 -1 0 841.8898 cm  BT /F1 12 Tf 14.4 TL ET
BT /F1 12 Tf 14.4 TL ET
0 0 0 0 k
/gRLs0 gs
n 14 9 157 15 re f*
0 0 0 100 k
BT 1 0 0 -1 15 20 Tm (Received 16.04.2020) Tj T* ET
```

The problems are that is that content stream references external objects, namely `/F1` (the font definition) and `/gRLs0` (the extended graphics state). You would have to copy those objects from `input_pdf.pages[0].Resources` to the output PDF.

For a simple example that will work try doing just a filled rectangle with no alpha channel and no text. The alpha channel implies an extended graphics state object.

There is an API in qpdf to add an overlay/underlay which is the easy approach for now, and you can do it from the command line. At some point I will add bindings to this API so pikepdf users can access it too - this would take care of the details of automatically copying the necessarily information.

**Comment by joneug** [comment]
Thank you! The [overlay/underlay options](http://qpdf.sourceforge.net/files/qpdf-manual.html#ref.overlay-underlay)  in QPDF work very well (and, by the way, this is much faster for larger files than using the merging functions of PyPDF2). Would be cool to see this in pikepdf in the future.

**Comment by jbarlow83** [comment]
Now implemented: https://pikepdf.readthedocs.io/en/latest/topics/overlays.html
