### ISSUE TITLE
[Help Request] Merge images into a PDF

### ISSUE THREAD

**Issue by zombie110year** [pikepdf/pikepdf#96]
How can I insert images into a Page, or merge images into a PDF just like the image file is a PDF file?

# What I want to do

```python
import pikepdf

pdfw = pikepdf.Pdf.new()
imagefile = function_to_read_file_as_a_PdfImage("path/to/image.png")
imagepage = function_to_convert_a_PdfImage_into_a_fullpage_image_as_a_Page(imagefile)
pdfw.pages.append(imagepage)
```

**Comment by jbarlow83** [comment]
For that use img2pdf.

pikepdf is more for editing and processing existing PDFs. Reading PDFs is hard. Writing them is easy, so there are a lot more tools available for that. img2pdf does exactly what what you need. reportlab might help too if you need text and images.

**Comment by zombie110year** [comment]
Thanks.
