### ISSUE TITLE
Update needed for qpdf 10

### ISSUE THREAD

**Issue by spwhitton** [pikepdf/pikepdf#97]
On Debian's CI infra:

    =================================== FAILURES ===================================
    __________________________ test_minimum_qpdf_version ___________________________
    
        def test_minimum_qpdf_version():
            from pikepdf import _qpdf
        
    >       assert _qpdf.qpdf_version() >= '7.0.0'
    E       AssertionError: assert '10.0.1' >= '7.0.0'
    E        +  where '10.0.1' = <built-in method qpdf_version of PyCapsule object at 0x7f385abd5d50>()
    E        +    where <built-in method qpdf_version of PyCapsule object at 0x7f385abd5d50> = <module 'pikepdf._qpdf' from '/usr/lib/python3/dist-packages/pikepdf/_qpdf.cpython-38-x86_64-linux-gnu.so'>.qpdf_version
    
    tests/test_sanity.py:27: AssertionError
    =============== 1 failed, 260 passed, 9 skipped in 6.75 seconds ================

**Comment by jbarlow83** [comment]
Already fixed in v1.11.0

**Comment by spwhitton** [comment]
Hello,

On Sun 19 Apr 2020 at 04:55PM -07, jbarlow83 wrote:

> Already fixed in v1.11.0

I'm sorry, I should have looked more carefully at the version numbers
being tested.  Thank you for your reply.

-- 
Sean Whitton
