### ISSUE TITLE
Stuck in between VC++ versions

### ISSUE THREAD

**Issue by epogrebnyak** [pikepdf/pikepdf#99]
I have several versions of Microsoft Visual C++ 2015-2019 installed, but `pikepdf` does not pick any of them up unfortunately. 

https://github.com/betatim/notebook-as-pdf/issues/1#issuecomment-616997905

When I got through [documentation link](https://pikepdf.readthedocs.io/en/latest/installation.html#windows-runtime-requirements) the specific [version of VC++](https://www.microsoft.com/en-us/download/details.aspx?id=48145) cannot install because there is a newer one on my machine.

I seem to be in one of Windows traps ) 

Anyone had a similar problem, maybe there are any suggestions?

**Comment by jbarlow83** [comment]
Perhaps you can run Dependency Walker on the pikepdf.dll and see what it symbols it is looking for?

I'm compiling pikepdf on the virtual machine image called "vs2017-win2016" on Azure, i.e. VC++2017 and Windows Server 2016. I believe the version I mentioned came from searching for what version of VC++ adds support for C++14 and confirming this on a virtual machine. This runtime is *not* explicitly involved in the build. 

Could be you hit this issue: https://answers.microsoft.com/en-us/windows/forum/all/visual-c-2015-2019-x64-failure-to-install/9eab23a5-df46-4b97-9be8-4e7dd5cd8d61?auth=1

You certainly can recompile pikepdf locally, using the build steps in the documentation or `azure-pipelines.yml` as a template. You do not have to use the wheel if it is giving you trouble. But I am interesting in finding out more precisely what can be done to ensure compatibility.

**Comment by epogrebnyak** [comment]
Thank you for the clues, lot of to go through. Silly question - where should `pikepdf.dll` be at? Somewhere in python installation folder or windows some system folder? I tried looking either place, but no success.

**Comment by jbarlow83** [comment]
The two files to search for are actually named `_qpdf.cp*.pyd` (wildcard) and `qpdf*.dll`.

The former's name will be slightly different based on your Windows version, e.g. `_qpdf.cp37-win_amd64.pyd` for Python 3.7 on 64-bit Windows.

**Comment by jbarlow83** [comment]
Did you find a solution?

**Comment by epogrebnyak** [comment]
I run dependecy Walker on qpdf28.dll, the following files are reported as missing:

```
API-MS-WIN-CORE-APIQUERY-L1-1-0.DLL
API-MS-WIN-CORE-APIQUERY-L1-1-1.DLL
API-MS-WIN-CORE-APPCOMPAT-L1-1-0.DLL
API-MS-WIN-CORE-APPCOMPAT-L1-1-1.DLL
API-MS-WIN-CORE-COMM-L1-1-0.DLL
```

I think I'm loosing a struggle with Windows and hope to resort to WSL. Should I close the issue?

**Comment by jbarlow83** [comment]
Apparently those dependencies are false positives
https://ofekshilon.com/2016/03/27/on-api-ms-win-xxxxx-dll-and-other-dependency-walker-glitches/

Can you install qpdf for Windows and run it?

**Comment by jbarlow83** [comment]
I was able to install the "2015, 2017 and 2019" runtime on a fresh Windows 10 VM:
https://aka.ms/vs/16/release/vc_redist.x64.exe
and get pikepdf to work. I used x64 versions of everything.

In any event, I'm pretty sure I can legally bundle these MSVCRT files into the pikepdf wheel for Windows. So I did. Hopefully that will do it!

**Comment by epogrebnyak** [comment]
I updated pikepdf to v1.12.0 and it works like a charm! Thank you for spotting and going though the issue, I'm hoping there are dozens of happier Windows useres now!
